## 실제 활용해보면 익히는 mysql 기본 문법이다. + 중급 문법
- 다양한 문법을 나열하기보다는, 실제 예제를 통해, 그때 그때 문법을 익혀야 이해가 빠르다.

In [3]:
### 1. 스키마 정의
- TABLE을 두개로 만든다. FOREIGN KEY, PRIMARY KEY 사용

In [ ]:
CREATE TABLE ranking (
    num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    main_category VARCHAR(50) NOT NUL,
    sub_category VARCHAR(50) NOT NULL,
    item_ranking TINYINT UNSIGNED NOT NULL,
    item_code VARCHAR(20) NOT NULL,
    FOREIGN KEY (item_code) REFERENCES items(item_code)
)

In [ ]:
CREATE TABLE items (
    item_code VARCHAR(20) NOT NULL PRIMARY KEY, 
    title VARCHAR(200) NOT NULL,
    ori_price INT NOT NULL,
    dis_price INT NOT NULL,
    discount_percent INT NOT NULL, 
    provider VARCHAR(200)
)

In [ ]:
DROP DATABASE IF EXISTS bestproducts 

CREATE DATABASE bestproducts DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

In [6]:
import pymysql

db = pymysql.connect(host='localhost', port=3306, user='root', passwd='choi30133!', charset='utf8')
cursor = db.cursor()

sql = "DROP DATABASE IF EXISTS bestproducts;"
cursor.execute(sql)

sql = "CREATE DATABASE bestproducts DEFAULT CHARSET=utf8 COLLATE=utf8_bin;"
cursor.execute(sql)

db.commit()
db.close()

In [9]:
db = pymysql.connect(host='localhost', port=3306, user='root', passwd='choi30133!', db = 'bestproducts', charset='utf8')
bestproducts = db.cursor()

sql = """
CREATE TABLE items (
    item_code VARCHAR(20) NOT NULL PRIMARY KEY, 
    title VARCHAR(200) NOT NULL,
    ori_price INT NOT NULL,
    dis_price INT NOT NULL,
    discount_percent INT NOT NULL, 
    provider VARCHAR(200)
);
"""

bestproducts.execute(sql)

sql = """
CREATE TABLE ranking (
    num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    main_category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(50) NOT NULL,
    item_ranking TINYINT UNSIGNED NOT NULL,
    item_code VARCHAR(20) NOT NULL,
    FOREIGN KEY (item_code) REFERENCES items(item_code)
);
"""

bestproducts.execute(sql)

db.commit()
db.close()

### 2. 크롤링
- Beautiful soup(bs4), Selenium, Scrapy

#### main category 정보 가져오기

In [39]:
import requests
from bs4 import BeautifulSoup

response = requests.get("http://corners.gmarket.co.kr/Bestsellers")
soup = BeautifulSoup(response.content, 'html.parser')

categories = soup.select('div.gbest-cate ul.by-group li a')
# print(categories)

for category in categories : 
    get_category('http://corners.gmarket.co.kr' + category['href'], category.get_text())

http://corners.gmarket.co.kr/Bestsellers ALL
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류 브랜드 여성의류 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01&subGroupCode=S161
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류 브랜드 남성의류 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01&subGroupCode=S162
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류 브랜드 진/캐쥬얼  http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01&subGroupCode=S163
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류 여성의류 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01&subGroupCode=S102
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류 남성의류 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01&subGroupCode=S002
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류 언더웨어 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01&subGroupCode=S088
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 브랜드 신발/가방 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S166
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 브랜드 쥬얼리/시계 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S167
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 여성신발 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S004
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 남성신발 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S005
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 운동화 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S007
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 가방/지갑 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S008
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 잡화/액세서리 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S127
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 수입명품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S134
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화 여행가방 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02&subGroupCode=S172
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 화장품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S011
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 보습제품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S081
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 남성화장품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S055
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 향수 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S012
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 화장소품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S016
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 바디클렌져/바디로션 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S013
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 샴푸/헤어에센스/스타일링 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S014
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03 화장품/헤어 제모/데오드란트/슬리밍 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G03&subGroupCode=S069
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 기저귀 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S017
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 분유/이유식 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S063
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 물티슈 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S020
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 신생아의류/잡화 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S131
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 유아동의류 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S064
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 유아동신발  http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S132
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 유아동가방/잡화  http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S133
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 출산/유아용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S018
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 장난감/완구 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S076
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 임부복/용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S062
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산 홈플러스 베이비 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04&subGroupCode=S158
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G04 유아동/출산  http://corners.gmarket.co.kr/bestseller/BestSellerList.asp?group_kind=G&group_cd=G10&groupSub_kind=GS&groupSub_cd=S073
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 과일/견과 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S103
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 쌀/잡곡 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S031
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 축산 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S089
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 수산 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S090
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 김치/반찬 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S104
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 생수/커피/음료 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S105
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 간편조리/간식 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S106
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 캔/오일/조미료 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S107
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 건강 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S033
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 다이어트 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S092
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 정관장/홍삼 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S108
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 채소 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S147
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품 홈플러스 식품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07&subGroupCode=S160
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G07 식품  http://corners.gmarket.co.kr/bestseller/BestSellerList.asp?group_kind=G&group_cd=G04&groupSub_kind=GS&groupSub_cd=S063
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강

http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 마스크(성인/유아동) http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S184
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 손소독제/소독기기 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S185
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 샤워기/필터/생활용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S035
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 주방용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S034
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 세제/세면용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S066
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 화장지/일용잡화 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S067
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 위생용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S037
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 악기/취미/원예용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S038
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 문구/사무용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S040
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 반려동물용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S137
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 공구설비/자재 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S145
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 건강/의료용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S146
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 홈플러스 리빙 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S159
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08 생활/주방/건강 렌탈 서비스 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G08&subGroupCode=S173
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09 가구/침구
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09 가구/침구 가구 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09&subGroupCode=S041
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09 가구/침구 침구 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09&subGroupCode=S042
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09 가구/침구 커튼/블라인드 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09&subGroupCode=S071
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09 가구/침구 홈패션/인테리어소품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09&subGroupCode=S043
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09 가구/침구 브랜드 가구/침구/인테리어 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G09&subGroupCode=S091
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 스포츠의류/운동화 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S174
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 휘트니스/수영 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S176
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 구기/라켓 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S177
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 골프 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S023
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 자전거/보드/기타레저 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S178
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 캠핑/낚시 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S179
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 등산/아웃도어 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S180
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05 스포츠/자동차 자동차용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G05&subGroupCode=S024
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 노트북/태블릿 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S141
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 모니터/프린터 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S140
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 컴퓨터/용품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S056
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 영상가전 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S059
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 저장장치  http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S138
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 주방가전 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S142
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 계절가전 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S061
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 생활/미용가전 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S060
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 카메라 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S057
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 휴대폰 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S065
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 헤드폰/이어폰 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S143
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 MP3/스피커 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S144
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 게임 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S058
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 디지털 액세서리 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S112
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 컴퓨터 사업자몰 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06&subGroupCode=S169
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G06 컴퓨터/전자 하이마트 http://corners.gmarket.co.krhttp://minishop.gmarket.co.kr/ehimart1
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 시/소설 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S044
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 경제/경영/개발 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S093
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 인문/사회/과학/IT http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S094
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 가정/생활/취미/레저 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S095
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 만화/잡지 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S096
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 해외원서 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S097
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 학습/수험 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S045
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 어린이 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S073
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 음반 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S046
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10 도서/음반 DVD http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G10&subGroupCode=S074
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11 여행

http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11 여행 국내여행 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11&subGroupCode=S047
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11 여행 해외여행 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11&subGroupCode=S048
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11 여행 여행소품 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11&subGroupCode=S049
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11 여행 G9 해외패키지 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G11&subGroupCode=S181
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12 e쿠폰/티켓
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12 e쿠폰/티켓 외식 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12&subGroupCode=S051
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12 e쿠폰/티켓 온라인컨텐츠 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12&subGroupCode=S052
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12 e쿠폰/티켓 생활쿠폰 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12&subGroupCode=S053
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12 e쿠폰/티켓 상품권 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12&subGroupCode=S148
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12 e쿠폰/티켓 모바일 상품권 http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G12&subGroupCode=S135

#### main/sub category 정보 가져오기

In [38]:
def get_category(category_link, category_name) :
    print(category_link, category_name)
    res = requests.get(category_link)
    soup = BeautifulSoup(res.content, 'html.parser')
    
    sub_categories = soup.select('div.navi.group ul li a')
    
    for sub_category in sub_categories : 
        print(category_link, category_name, sub_category.get_text(), 'http://corners.gmarket.co.kr' + sub_category['href'])

### main/sub category + 상품 정보 크롤링

In [138]:
import requests
from bs4 import BeautifulSoup
import pymysql

db = pymysql.connect(host='localhost', port=3306, user='root', passwd='choi30133!', db='bestproducts', charset='utf8')
bestproducts = db.cursor()

response = requests.get("http://corners.gmarket.co.kr/Bestsellers")
soup = BeautifulSoup(response.content, 'html.parser')

categories = soup.select('div.gbest-cate ul.by-group li a')
# print(categories)

for category in categories : 
    get_category('http://corners.gmarket.co.kr' + category['href'], category.get_text())
    
db.commit()
db.close()

http://corners.gmarket.co.kr/Bestsellers ALL
INSERT INTO items VALUES ('1941616635',
        '[컬럼비아](광주신세계)3종 택일 컬럼비아 남성 가볍고 따뜻한 경량 다운 조끼 C14-WE0952',
        45000,
        32850,
        27,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '1',
    '1941616635'
    )
INSERT INTO items VALUES ('1963022191',
        '[Aura]아우라 건조기용 드라이시트 윌유메리미 120매 +에코백',
        18900,
        15900,
        15,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '2',
    '1963022191'
    )
INSERT INTO items VALUES ('1980285072',
        '스마일케이 KF94 입체형 마스크 대형 개별포장 100매',
        21000,
        19380,
        7,
        'SIGMA')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '3',
    '1980285072'
    )
INSERT INTO items VALUES ('787562120',
        '글램공감/브라1+팬티2/속옷세트/A~D컵/빅사이즈',
        26300,
        7900,
        69,
        '버블돌2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '4',
    '787562120'
    )
INSERT INTO items VALUES ('1797053808',
        '[크리넥스]크리넥스 실크소프트 250매X3입X3팩 /곽티슈',
        30900,
        17900,
        42,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '5',
    '1797053808'
    )
INSERT INTO items VALUES ('1895819882',
        '[프레시지]바를정육 한입 LA갈비 2.0 kg (500g x 4)',
        35900,
        34180,
        4,
        '프레시지')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '6',
    '1895819882'
    )
INSERT INTO items VALUES ('1501650673',
        '1+1/김치옹심이만두1kg+고기옹심이만두1kg/만두',
        25800,
        13900,
        46,
        '미소푸드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '7',
    '1501650673'
    )
INSERT INTO items VALUES ('2002310720',
        '(현대Hmall)[크리넥스] KF94 데일리 마스크 블랙 대형 20P',
        21500,
        21290,
        0,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '8',
    '2002310720'
    )
INSERT INTO items VALUES ('1280233513',
        '티메이 겨울신상 니트 가디건 기모맨투맨 트레이',
        32900,
        9900,
        69,
        'T-MEI')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '9',
    '1280233513'
    )
INSERT INTO items VALUES ('1915042832',
        '르 꽁뜨 by 헤어 속볼륨 펌브러쉬',
        59900,
        59900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '10',
    '1915042832'
    )
INSERT INTO items VALUES ('2006957120',
        '이퓨쳐 스마트파닉스 리더스 1~5권 세트 선택구매(분권20권or합본5권)',
        120000,
        60350,
        49,
        'ohbook6')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '11',
    '2006957120'
    )
INSERT INTO items VALUES ('1728114361',
        '[동원에프앤비]동원 인포켓 치즈 오리지널 (스트링치즈) 20g x 40개',
        29100,
        20400,
        29,
        '동원_냉장냉동')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '12',
    '1728114361'
    )
INSERT INTO items VALUES ('1985717014',
        '(북큐레이션/토토북)세계책 시리즈 전3종',
        45000,
        42750,
        5,
        'G_맘챌')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '13',
    '1985717014'
    )
INSERT INTO items VALUES ('1580850427',
        '[닥터포헤어] 폴리젠 샴푸 500mlx3 + 100mlx3',
        41100,
        41100,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '14',
    '1580850427'
    )
INSERT INTO items VALUES ('1911502384',
        '국내산 삶은 돼지머리 (비절단) 3kg내외 대용량',
        29900,
        17900,
        40,
        '정직한밥상')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '15',
    '1911502384'
    )
INSERT INTO items VALUES ('1706867641',
        '밀크앤허니 베이커리 1+1 골라담기 (신세계푸드)',
        25800,
        12900,
        50,
        '(주)신세계푸드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '16',
    '1706867641'
    )
INSERT INTO items VALUES ('1730320554',
        '[모나리자]모나리자 프리미엄 화장지 30미터 90롤',
        26400,
        26400,
        0,
        '공영쇼핑TV')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '17',
    '1730320554'
    )
INSERT INTO items VALUES ('2008166546',
        '[20년] 양구 펀치볼 시래기',
        38900,
        38900,
        0,
        '공영쇼핑TV')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '18',
    '2008166546'
    )
INSERT INTO items VALUES ('1766184747',
        '[릴리유]릴리유 퓨어퍼플 물티슈 캡72매X10팩(1BOX)',
        30900,
        16900,
        45,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '19',
    '1766184747'
    )
INSERT INTO items VALUES ('1802922560',
        '(이쌀이다) [2020년산] 당진해나루 삼광 20kg',
        67800,
        65800,
        2,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '20',
    '1802922560'
    )
INSERT INTO items VALUES ('2005083336',
        '[삼성전자](사전예약판매) 갤럭시S21 5G 자급제폰 SM-G991N',
        999900,
        999900,
        0,
        '삼성공식온라인판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '21',
    '2005083336'
    )
INSERT INTO items VALUES ('2006641462',
        '당진 해나루 삼광쌀 20kg / 특등급 최근도정',
        67900,
        67900,
        0,
        'NS몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '22',
    '2006641462'
    )
INSERT INTO items VALUES ('1505445237',
        '[3M]후레쉬 위생장갑 100+100매 2개 총400매+사은품',
        12500,
        11250,
        10,
        '한국쓰리엠공식온라인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '23',
    '1505445237'
    )
INSERT INTO items VALUES ('2000624728',
        '[르 꽁뜨 by 헤어] 속볼륨 펌브러쉬',
        59900,
        56910,
        4,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '24',
    '2000624728'
    )
INSERT INTO items VALUES ('1951589736',
        '[더바디샵][더바디샵][현대단독구성] 진저 헤어 샴푸 세트',
        88000,
        79200,
        10,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '25',
    '1951589736'
    )
INSERT INTO items VALUES ('911450468',
        '[코코도르]BEST 디퓨저 선물세트/전옵션쇼핑백증정/디퓨저',
        15900,
        7900,
        50,
        '코코도르(주)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '26',
    '911450468'
    )
INSERT INTO items VALUES ('2005081916',
        '[삼성전자](사전예약판매) 갤럭시S21 5G 자급제폰 SM-G991N',
        999900,
        999900,
        0,
        '삼성공식온라인판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '27',
    '2005081916'
    )
INSERT INTO items VALUES ('542213367',
        '[리츠]리츠 크래커 120gx6박스/과자/오레오 /+사은품',
        19800,
        9900,
        50,
        '큐마트솔루션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '28',
    '542213367'
    )
INSERT INTO items VALUES ('1866947178',
        '멀티채반 (랜덤) 1+1',
        6900,
        3900,
        43,
        '크로바몰(주)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '29',
    '1866947178'
    )
INSERT INTO items VALUES ('214340838',
        '[겔업]겔업 고농축 액체세제 2.5L x 4개 세탁세제 총10000ml',
        25000,
        7900,
        68,
        '■바보몰■')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '30',
    '214340838'
    )

INSERT INTO items VALUES ('1686301103',
        '국내가공 오동통 가문어 통족 1kg / 오징어다리',
        23200,
        15500,
        33,
        '유쾌상회')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '31',
    '1686301103'
    )
INSERT INTO items VALUES ('1510637585',
        '[스파클]스파클생수 2L 30병',
        38700,
        12900,
        66,
        '스파클Mart')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '32',
    '1510637585'
    )
INSERT INTO items VALUES ('1969140335',
        '[아웃백스테이크하우스](아웃백/빕스)Pays 외식/카페 결합 금액권 5만원권',
        50000,
        44500,
        11,
        '한국페이즈서비스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '33',
    '1969140335'
    )
INSERT INTO items VALUES ('168998508',
        '우리네농산물 달콤한 왕만쥬빵 60gx30개입',
        21800,
        10900,
        50,
        '우리네농산물')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '34',
    '168998508'
    )
INSERT INTO items VALUES ('1975005353',
        '태안 손질 꽃게 0.5kg 쿠폰가:10560원 (4~5미 손질)',
        17800,
        11900,
        33,
        '행복담은농장')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '35',
    '1975005353'
    )
INSERT INTO items VALUES ('1655242371',
        '[구글플레이](카드가능) 기프트코드 10만원 / 구글 기프트카드',
        100000,
        95000,
        5,
        '(주)한국선불카드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '36',
    '1655242371'
    )
INSERT INTO items VALUES ('701343009',
        '(행사상품)[20년산]The Plus 좋은쌀_20KG 포 ',
        56900,
        55480,
        2,
        '홈플러스당일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '37',
    '701343009'
    )
INSERT INTO items VALUES ('1659613059',
        '돈을 부르는 황금 코끼리상 인테리어소품 장식품 동상',
        11900,
        9900,
        16,
        '포케이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '38',
    '1659613059'
    )
INSERT INTO items VALUES ('484828506',
        '[아침농산]국산 농부의아침 쌀10kg  2020년산 햅쌀',
        41300,
        28900,
        30,
        '아침농산잡곡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '39',
    '484828506'
    )
INSERT INTO items VALUES ('965313589',
        '집콕엔 제이나나 수면잠옷/꿀잠 잠옷/파자마/홈웨어',
        33000,
        9900,
        70,
        '제이나나')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '40',
    '965313589'
    )
INSERT INTO items VALUES ('2007251567',
        '[엘지전자]   LG 코드제로 A9S 무선청소기 A9370 IK/SK/VK',
        899000,
        746070,
        17,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '41',
    '2007251567'
    )
INSERT INTO items VALUES ('1936857533',
        '[에이엠]am 멀티 다지기 FC-J18 (용기 3개  보관커버 포함) +',
        52900,
        49900,
        5,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '42',
    '1936857533'
    )
INSERT INTO items VALUES ('1661166132',
        ' 특집  1등급 친환경 오리로스 18팩+1팩 더 ',
        40900,
        40900,
        0,
        '공영쇼핑TV')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '43',
    '1661166132'
    )
INSERT INTO items VALUES ('221969619',
        '스마일클럽 12% 쿠폰 따뜻한 여성 기모 본딩 청바지',
        32900,
        9900,
        69,
        '진마니아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '44',
    '221969619'
    )
INSERT INTO items VALUES ('576442682',
        '{니트모아}  롱가디건/니트/폴라/원피스/빅사이즈',
        32900,
        9900,
        69,
        '니트모아.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '45',
    '576442682'
    )
INSERT INTO items VALUES ('1733997124',
        '[얌테이블]담백하고 쫄깃한 반건조 코다리 8미 /10%쿠폰: 10530원',
        17800,
        11900,
        33,
        '얌테이블')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '46',
    '1733997124'
    )
INSERT INTO items VALUES ('1943088289',
        '[플루]플루 바디스크럽 워시 무려 16개 최다 +스파브러쉬',
        64900,
        60710,
        6,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '47',
    '1943088289'
    )
INSERT INTO items VALUES ('1946778690',
        '(블루앤트리) 베이비애니멀 14종/세쌍둥이 Talk Play 13종/세쌍둥이 When I Grow Up 13종 세트별 선택구매',
        40000,
        33000,
        17,
        '토피카북스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '48',
    '1946778690'
    )
INSERT INTO items VALUES ('1824789344',
        '[유니프랜드]유니프랜드/오가닉/무형광/유아내의/실내복 특가모음',
        16300,
        4900,
        69,
        '유니프렌드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '49',
    '1824789344'
    )
INSERT INTO items VALUES ('1927705175',
        '[나이키]나이키 스우시 크루삭스 3팩 6팩 드라이핏 스포츠양말',
        10000,
        8900,
        11,
        'THESOX')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '50',
    '1927705175'
    )
INSERT INTO items VALUES ('1956768128',
        '그때그맛 김수미 낙지볶음 300gx4팩 + 쭈꾸미볶음 30',
        56900,
        49650,
        12,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '51',
    '1956768128'
    )
INSERT INTO items VALUES ('1962120972',
        '[스케쳐스](신세계강남점)[스케쳐스] 남여 운동화 딜라이트 에어리/에너지 7종 (SL0WC20X011/SL0UC20Y051)',
        49000,
        39110,
        20,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '52',
    '1962120972'
    )
INSERT INTO items VALUES ('1890212643',
        '[다이슨]본사  다이슨 에어랩 스타일러 컴플리트',
        599000,
        545090,
        9,
        '다이슨코리아유한회사')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '53',
    '1890212643'
    )
INSERT INTO items VALUES ('1766223216',
        '[금성농협] 20년산 대숲맑은담양쌀 20kg/새청무/특등급/당일도정',
        61500,
        61500,
        0,
        '홈앤쇼핑MALL')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '54',
    '1766223216'
    )
INSERT INTO items VALUES ('1782687491',
        '[에쓰오일](S-OIL) 모바일주유권 5만원권',
        50000,
        49000,
        2,
        '쿠프마케팅')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '55',
    '1782687491'
    )
INSERT INTO items VALUES ('1929003406',
        '[탑텐키즈](신세계하남점)[탑텐키즈] 20FW 신상 아동 온에어세트',
        7900,
        5610,
        28,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '56',
    '1929003406'
    )
INSERT INTO items VALUES ('2006772371',
        '[삼성전자](사전판매) 갤럭시S21 플러스 5G 자급제폰 SM-G996N',
        1199000,
        1199000,
        0,
        '삼성공식온라인판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '57',
    '2006772371'
    )
INSERT INTO items VALUES ('1675104974',
        '[갤럭시]핸드폰케이스 S20 S10 노트20 노트10 노트9 노트8',
        20000,
        9900,
        50,
        '제로큐브')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '58',
    '1675104974'
    )
INSERT INTO items VALUES ('1856830289',
        '본사공식 풀무원 샘물 생수 2Lx24 무료배송',
        24900,
        12900,
        48,
        'DWHOME')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '59',
    '1856830289'
    )
INSERT INTO items VALUES ('1490019603',
        '센스물티슈 악어 캡형 100매 10팩+10팩 / 한장씩톡톡',
        27800,
        13900,
        50,
        '중원(주)2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '60',
    '1490019603'
    )

INSERT INTO items VALUES ('1494979529',
        '[이지바이]겨울베스트아이템균일가/후리스/패딩/자켓/조끼/기모',
        26300,
        7900,
        69,
        '(주)이지바이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '61',
    '1494979529'
    )
INSERT INTO items VALUES ('1986969051',
        '[지프][지프] 20FW 겨울 인기상품 특가전',
        29900,
        29900,
        0,
        'NC_백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '62',
    '1986969051'
    )
INSERT INTO items VALUES ('1601184876',
        '[불닭볶음면]불닭볶음면 큰컵 6개+까르보 불닭볶음면 큰컵 6개',
        16000,
        12900,
        19,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '63',
    '1601184876'
    )
INSERT INTO items VALUES ('1912227495',
        '[샤오미]샤오미 미밴드5 여우미 공식수입 정식 한글판(미개봉)',
        38900,
        38900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '64',
    '1912227495'
    )
INSERT INTO items VALUES ('1783303725',
        '[크리넥스안심]유한킴벌리 안심 클래식 키친타올 140매x12롤X2팩',
        35900,
        18900,
        47,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '65',
    '1783303725'
    )
INSERT INTO items VALUES ('1992589858',
        '[맛있는우유GT]맛있는우유GT 멸균 흰우유 180ml 48팩',
        30000,
        23700,
        21,
        '남양월드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '66',
    '1992589858'
    )
INSERT INTO items VALUES ('1945772215',
        '[NeeGee]7DAYS 일주일 7종 주얼리 세트 한정판 리미티드 에디션',
        39900,
        16900,
        57,
        '니지쥬얼리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '67',
    '1945772215'
    )
INSERT INTO items VALUES ('1711339174',
        '통통생굴 2kg / 횟감용 지금이 제철 가장 맛있는 시기',
        23900,
        23670,
        0,
        'Fresh_바다내음')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '68',
    '1711339174'
    )
INSERT INTO items VALUES ('1578966236',
        '[칠성사이다]칠성 사이다 210ml x 30캔',
        17900,
        10900,
        39,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '69',
    '1578966236'
    )
INSERT INTO items VALUES ('1747419672',
        '[Aura]아우라 건조기용 드라이시트 만다린 120매 +에코백',
        18900,
        15900,
        15,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '70',
    '1747419672'
    )
INSERT INTO items VALUES ('1124083462',
        '[아이러브베베]아이러브베베물티슈핑크100매캡형X20팩',
        31900,
        13900,
        56,
        '아기물티슈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '71',
    '1124083462'
    )
INSERT INTO items VALUES ('1945578222',
        '[닥터방기원]비어이스트 맥주효모 탈모샴푸 1Lx2+토닉+사은품 2종',
        79900,
        28900,
        63,
        '닥터방기원')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '72',
    '1945578222'
    )
INSERT INTO items VALUES ('1631652678',
        '[브레프]브레프 파워 액티브 변기세정제 3px3개 화장실방향제',
        30000,
        10900,
        63,
        '지엑스몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '73',
    '1631652678'
    )
INSERT INTO items VALUES ('2004307521',
        '[플루][NEW 골드에디션] 플루스크럽 시즌11 최대용량 파격패키지',
        77000,
        77000,
        0,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '74',
    '2004307521'
    )
INSERT INTO items VALUES ('1607527508',
        '[동원참치]라이트 스탠다드 참치 100g 15캔 원터치',
        20900,
        18900,
        9,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '75',
    '1607527508'
    )
INSERT INTO items VALUES ('1714476696',
        '새해 첫 미샤데이 색조 best up to 70%',
        34000,
        17000,
        50,
        '미샤(본사직영)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '76',
    '1714476696'
    )
INSERT INTO items VALUES ('2006783420',
        '[삼성전자](사전판매) 갤럭시S21 울트라 5G 자급제폰 SM-G998N',
        1452000,
        1452000,
        0,
        '삼성공식온라인판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '77',
    '2006783420'
    )
INSERT INTO items VALUES ('1606293717',
        '수맘 12%쿠폰 겨울 신상 수면 기모 홈웨어 잠옷 세트',
        33000,
        9900,
        70,
        '(수맘)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '78',
    '1606293717'
    )
INSERT INTO items VALUES ('1108678685',
        '12%쿠폰 기모/융털/모직/트레이닝팬츠/빅사이즈~4XL',
        26300,
        7900,
        69,
        '엠스트럭처')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '79',
    '1108678685'
    )
INSERT INTO items VALUES ('1986796870',
        '꿀당도 서귀포 한라봉 4.5kg내외/(25-28과/중소과)',
        28350,
        18900,
        33,
        '삼무몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '80',
    '1986796870'
    )
INSERT INTO items VALUES ('1605115571',
        '[프렌치카페]프렌치카페 카페믹스/믹스커피 200Tx2 (400T)',
        36900,
        33900,
        8,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '81',
    '1605115571'
    )
INSERT INTO items VALUES ('1723934570',
        '[부산어묵][부산어묵] 8종 28팩 종합 세트',
        42900,
        38610,
        10,
        '홈앤쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '82',
    '1723934570'
    )
INSERT INTO items VALUES ('2007637756',
        '동국 마데카 최신상 풀패키지 크림 대12+중4+ 콜라겐 기초 4종',
        169000,
        169000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '83',
    '2007637756'
    )
INSERT INTO items VALUES ('1964113036',
        '자연 모짜렐라 슈레드치즈 1kg  /피자치즈/대용량',
        19800,
        9900,
        50,
        '슈퍼맨푸드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '84',
    '1964113036'
    )
INSERT INTO items VALUES ('1503353718',
        '[오뚜기밥]맛있는 오뚜기밥 210g 24개',
        33000,
        19900,
        39,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '85',
    '1503353718'
    )
INSERT INTO items VALUES ('2000249425',
        '휴먼어린이-나의 첫 역사책 세트 (전20권)',
        286000,
        260000,
        9,
        '다책')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '86',
    '2000249425'
    )
INSERT INTO items VALUES ('221218898',
        '코코비 겨울 상하복 티셔츠 팬츠 원피스 아동복',
        26300,
        7900,
        69,
        '코코비키즈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '87',
    '221218898'
    )
INSERT INTO items VALUES ('1501667618',
        '[베이비베이비]베이비베이비 아기물티슈 트윙클120매 20팩 캡형',
        29800,
        14900,
        50,
        '아기물티슈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '88',
    '1501667618'
    )
INSERT INTO items VALUES ('1791565626',
        '[에그머니](카드가능)(에그머니) 온라인 게임상품권 5만원',
        50000,
        45000,
        10,
        '(주)한국선불카드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '89',
    '1791565626'
    )
INSERT INTO items VALUES ('1760826797',
        '[애플]Apple 정품 에어팟 프로 MWP22KH/A',
        283000,
        257530,
        9,
        'Apple공식판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '90',
    '1760826797'
    )

INSERT INTO items VALUES ('1648830344',
        '원서읽는 리도보카 패키지 B 7000 여권의 원서별 단어학습 리도보카',
        100000,
        60000,
        40,
        '원서읽는리도보카')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '91',
    '1648830344'
    )
INSERT INTO items VALUES ('1655242060',
        '[구글플레이](카드가능) 기프트코드 5만원 / 구글 기프트카드',
        50000,
        47500,
        5,
        '(주)한국선불카드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '92',
    '1655242060'
    )
INSERT INTO items VALUES ('1907138648',
        '[적재적소]더 선명한 에탄올워셔액 1.8L 12개',
        30000,
        16900,
        43,
        '적재적소')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '93',
    '1907138648'
    )
INSERT INTO items VALUES ('2002078749',
        '[로지텍]로지텍코리아 C270 HD 웹캠 온라인수업 노이즈감소',
        32630,
        31000,
        4,
        '기가바이트공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '94',
    '2002078749'
    )
INSERT INTO items VALUES ('1992758228',
        '(커블체어) 2+1EVENT 커블체어 와이더 자세교정 의자 정품AS보증',
        126600,
        124710,
        1,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '95',
    '1992758228'
    )
INSERT INTO items VALUES ('1110065309',
        '[너트리]볶음땅콩 3.75kg 대용량 햇 20년산',
        26850,
        17900,
        33,
        '너트리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '96',
    '1110065309'
    )
INSERT INTO items VALUES ('659262319',
        '돌게장 2.2kg 특가/30년전통 백용준 밥도둑간장돌게장',
        28300,
        18900,
        33,
        '후레쉬빌')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '97',
    '659262319'
    )
INSERT INTO items VALUES ('1802922498',
        '(이쌀이다) [2020년산] 당진해나루 삼광 10kg',
        35500,
        34010,
        4,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '98',
    '1802922498'
    )
INSERT INTO items VALUES ('1780237414',
        '[올곧은]프리미엄  캡형 70매 10팩_Z509',
        65300,
        19600,
        69,
        '메디앙스-직영')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '99',
    '1780237414'
    )
INSERT INTO items VALUES ('1964215669',
        '2020년 햅쌀 신김포농협 특등급 김포금쌀 추청 20kg',
        70800,
        70800,
        0,
        '공영쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '100',
    '1964215669'
    )
INSERT INTO items VALUES ('1651273917',
        '[햇반]CJ 햇반 210g 36개 (1박스)',
        31900,
        31900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '101',
    '1651273917'
    )
INSERT INTO items VALUES ('1561822286',
        '[고소한아몬드후레이크]아몬드후레이크620g x2개입 +사은품랜덤',
        21800,
        10900,
        50,
        'l더마트l')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '102',
    '1561822286'
    )
INSERT INTO items VALUES ('1506397372',
        '전남 무안 김진원님의 자색양파즙 100포 / 특가',
        22900,
        20900,
        8,
        '농업회사_행복한밥상')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '103',
    '1506397372'
    )
INSERT INTO items VALUES ('1832583294',
        '앙블랑 아기물티슈 세이프 인디핑크 캡72매10팩N-IC10',
        18900,
        13900,
        26,
        '(주)앙블랑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '104',
    '1832583294'
    )
INSERT INTO items VALUES ('2007911354',
        '미래엔 개념잡는 초등시리즈8종/초등 입학준비 끝 5종 선택구매',
        56000,
        53200,
        5,
        '콘텐트리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '105',
    '2007911354'
    )
INSERT INTO items VALUES ('1899274105',
        '[미래생활]미래생활 순수PURE천연펄프 25m 30롤 x 3팩',
        31900,
        26900,
        15,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '106',
    '1899274105'
    )
INSERT INTO items VALUES ('203771527',
        '[보성농협]보성다향미20kg/쌀20kg 2020햅쌀 백미 상등급 당일도정',
        82800,
        57900,
        30,
        '우리곡물')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '107',
    '203771527'
    )
INSERT INTO items VALUES ('1914829196',
        '[아토세이프]고농축 라벤더 액체세제 2.5L X 4개 세탁 총10000ml',
        26300,
        7900,
        69,
        '아토세이프본사')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '108',
    '1914829196'
    )
INSERT INTO items VALUES ('174719105',
        '[뉴케어]뉴케어 구수한맛 200ml x 30팩 /친숙한맛 균형영양식',
        41900,
        41900,
        0,
        '에스엔에스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '109',
    '174719105'
    )
INSERT INTO items VALUES ('1756169729',
        '(투썸플레이스) 스트로베리 초콜릿 생크림',
        34000,
        31430,
        7,
        '쿠프마케팅')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '110',
    '1756169729'
    )
INSERT INTO items VALUES ('1808928096',
        '[삼성전자]더플레이트 NZ31T3703PWB 인덕션 용기 패키지 인증점',
        236260,
        207910,
        11,
        '삼성공식파트너KDL')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '111',
    '1808928096'
    )
INSERT INTO items VALUES ('1839957094',
        '[순수식품]리얼 석류 저분자 콜라겐 젤리 스틱 1박스(총 45포)',
        47280,
        22560,
        52,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '112',
    '1839957094'
    )
INSERT INTO items VALUES ('1992687537',
        '[브리타]막스트라 플러스 필터 3개월분',
        25500,
        18750,
        26,
        '한국브리타공식몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '113',
    '1992687537'
    )
INSERT INTO items VALUES ('1848719835',
        '[닌텐도]정품닌텐도스위치 동물의 숲에디션(타이틀제외) 바이고',
        440000,
        440000,
        0,
        '주식회사바이고')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '114',
    '1848719835'
    )
INSERT INTO items VALUES ('1495278850',
        '(12%할인)겨울시즌OFF/기모티/패딩/조끼/후리스/바지',
        22600,
        6800,
        69,
        '(주)이지바이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '115',
    '1495278850'
    )
INSERT INTO items VALUES ('637636954',
        '(20%쿠폰)클럽클리오 선물세트/리미티드/베스트템~50%',
        46000,
        14000,
        69,
        '클럽클리오본사직영')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '116',
    '637636954'
    )
INSERT INTO items VALUES ('1503231163',
        '(12%쿠폰)남여공용 후리스 팬츠 기모티 점퍼 양털모음',
        19600,
        5900,
        69,
        'podogood')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '117',
    '1503231163'
    )
INSERT INTO items VALUES ('806338693',
        '[바브키즈]바브키즈 겨울신상 데일리 아동복 국내생산 100%',
        33000,
        9900,
        70,
        '바브키즈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '118',
    '806338693'
    )
INSERT INTO items VALUES ('1567169398',
        '[GNM자연의품격]칼슘 마그네슘 아연 비타민D 2통/6개월분',
        23900,
        19900,
        16,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '119',
    '1567169398'
    )
INSERT INTO items VALUES ('1567156109',
        '[웅진]빅토리아  플레인 500ml x 40개입',
        21800,
        18500,
        15,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '120',
    '1567156109'
    )

INSERT INTO items VALUES ('1500350503',
        '[쏘피]안심숙면팬티 오버나이트 생리대 L 5Px3팩+무표백10P',
        21800,
        10900,
        50,
        'LG생활건강공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '121',
    '1500350503'
    )
INSERT INTO items VALUES ('2004156304',
        '[에잇컨셉]대구백화점 I관   에잇컨셉 여성 맨투맨/원피스/자켓 17종 모음',
        23000,
        20700,
        10,
        '대구백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '122',
    '2004156304'
    )
INSERT INTO items VALUES ('1926116893',
        '[센텔리안24]마데카크림 시즌4 50ml 2개 +선 에센스 1ml 5매',
        48000,
        24000,
        50,
        '동국제약공식판매처')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '123',
    '1926116893'
    )
INSERT INTO items VALUES ('1884705733',
        '[센텔리안24]엑스퍼트 마데카 멜라캡처 앰플 7ml 4개입 (단품4개)',
        87800,
        43900,
        50,
        '동국제약공식판매처')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '124',
    '1884705733'
    )
INSERT INTO items VALUES ('1373777190',
        '쉬블림로브 12%쿠폰 균일가 기모 맨투맨 니트 가디건',
        26300,
        7900,
        69,
        '쉬블림로브')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '125',
    '1373777190'
    )
INSERT INTO items VALUES ('1775171803',
        '[모나리자]모나리자 미용티슈 250매 3입 4개 총12개 각티슈 휴지',
        18900,
        18900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '126',
    '1775171803'
    )
INSERT INTO items VALUES ('1920642031',
        '[맥심]모카골드 커피믹스 160T+160T : 쿠폰가 31800원 ~',
        46000,
        34800,
        24,
        '큐마트솔루션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '127',
    '1920642031'
    )
INSERT INTO items VALUES ('1957397595',
        'KF94 국산 마스크 100매 식약처인증 의약외품 개별포장',
        27900,
        25800,
        7,
        '다샵몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '128',
    '1957397595'
    )
INSERT INTO items VALUES ('1895097525',
        'kf94 마스크 블랙 대형 100매 + 스트랩 1개 합리적인',
        35900,
        33900,
        5,
        '대건_daegeon')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '129',
    '1895097525'
    )
INSERT INTO items VALUES ('2004062312',
        'SKT 기변/번이 아이폰12 MINI_128G 완납/선약',
        1012000,
        718520,
        29,
        '피에스앤마케팅')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '130',
    '2004062312'
    )
INSERT INTO items VALUES ('1577510972',
        '[종근당]락토핏 생유산균 골드 50포 3개',
        41900,
        38900,
        7,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '131',
    '1577510972'
    )
INSERT INTO items VALUES ('1708266282',
        '[쉬크]면도기 하이드로5 프리미엄 면도기1+날17+사은품3',
        55800,
        27900,
        50,
        'LG생활건강온라인몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '132',
    '1708266282'
    )
INSERT INTO items VALUES ('2004086459',
        '[삼성전자]갤럭시버즈 프로 블루투스이어폰 ANC SM-R190 바이올렛',
        239800,
        239800,
        0,
        'jeyoumall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '133',
    '2004086459'
    )
INSERT INTO items VALUES ('1899473527',
        '시매쓰  빨라지고 강해지는 이것이 연산이다 A~F단계 세트 선택구매(전4권)',
        56000,
        28000,
        50,
        'ohbook6')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '134',
    '1899473527'
    )
INSERT INTO items VALUES ('1103681365',
        '[맥심]모카골드 커피믹스 160T+160T /쿠폰적용가31800원',
        46000,
        34800,
        24,
        '이티마트')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '135',
    '1103681365'
    )
INSERT INTO items VALUES ('1864626658',
        'KF94 국산 순풍 마스크 100매 식약처인증 의약외품',
        39900,
        39900,
        0,
        '왓더쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '136',
    '1864626658'
    )
INSERT INTO items VALUES ('1524852178',
        '영암 꿀달고구마 무농약 5kg(특상) 30년고구마재배',
        27900,
        27400,
        1,
        '싱그런')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '137',
    '1524852178'
    )
INSERT INTO items VALUES ('1500016536',
        '[포스트]그래놀라 크랜베리 아몬드 570gX3개+사은품/쿠폰 15100',
        37000,
        18500,
        50,
        '큐마트솔루션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '138',
    '1500016536'
    )
INSERT INTO items VALUES ('1954465467',
        'KF94 국산 마스크 의약외품 식약처인증 개별포장 100EA',
        28500,
        28500,
        0,
        '다샵몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '139',
    '1954465467'
    )
INSERT INTO items VALUES ('1630740718',
        '[센소다인]센소다인 오리지날 치약 2개+후레쉬 2개+멀티케어 2개',
        62700,
        22900,
        63,
        '주식회사오렌지')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '140',
    '1630740718'
    )
INSERT INTO items VALUES ('1955584051',
        '브레스마스크 KF-94 대형 / 100매입',
        27900,
        27900,
        0,
        'W쇼핑TV홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '141',
    '1955584051'
    )
INSERT INTO items VALUES ('1947674863',
        '[돌]Dole 마녀 비법 레드 190ml 1박스 24팩 야채주스+증정',
        33800,
        16900,
        50,
        '돌코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '142',
    '1947674863'
    )
INSERT INTO items VALUES ('1933734746',
        '[베리썸]베리썸 립 틴트팩 8총 + 립오일 1종',
        59000,
        53940,
        8,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '143',
    '1933734746'
    )
INSERT INTO items VALUES ('1816294717',
        '김나운더키친  슬기로운밥상 갈비탕 600g X 10팩',
        36900,
        36900,
        0,
        'NS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '144',
    '1816294717'
    )
INSERT INTO items VALUES ('1841478509',
        '[플레이도우]해즈브로 플레이도 미니쉐프 - 마스터쉐프 코스',
        65900,
        24900,
        62,
        '해즈브로공식온라인몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '145',
    '1841478509'
    )
INSERT INTO items VALUES ('1846363850',
        '[행텐주니어]행텐X행텐주니어 인기 패딩/후드/맨투맨/니트/팬츠',
        69000,
        20700,
        70,
        '행텐공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '146',
    '1846363850'
    )
INSERT INTO items VALUES ('858294811',
        '황금미가 쌀 20kg 20년산 햅쌀 (당일도정)',
        77000,
        53900,
        30,
        '홍천철원물류센터2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '147',
    '858294811'
    )
INSERT INTO items VALUES ('1654805524',
        '[구글플레이](카드가능) 기프트코드 1만원 / 구글 기프트카드',
        10000,
        9500,
        5,
        '(주)한국선불카드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '148',
    '1654805524'
    )
INSERT INTO items VALUES ('628809631',
        '감귤나라 10kg 중대과(L~2L) 전상품 특가찬스',
        13900,
        13900,
        0,
        '감귤나라.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '149',
    '628809631'
    )
INSERT INTO items VALUES ('1567171985',
        '[GNM자연의품격]건조한눈엔 루테인 + 오메가3 4박스(총 4개월분)',
        24900,
        19900,
        20,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '150',
    '1567171985'
    )

INSERT INTO items VALUES ('1924938065',
        '[다우니]초고농축 다우니 섬유유연제 엑스퍼트 실내건조 1L 3개',
        23400,
        18000,
        23,
        '피앤지샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '151',
    '1924938065'
    )
INSERT INTO items VALUES ('1686035302',
        '[제주삼다수]제주삼다수 2L 12병/생수전문배송',
        13400,
        11900,
        11,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '152',
    '1686035302'
    )
INSERT INTO items VALUES ('1925875290',
        '제주감귤 맛있는 제주 감귤 10kg 소과/로얄 2S-M',
        22350,
        14900,
        33,
        '티제이팜')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '153',
    '1925875290'
    )
INSERT INTO items VALUES ('1682819381',
        '[모다아울렛][나이키] 기모 맨투맨/후드/팬츠 특가',
        39000,
        39000,
        0,
        'MODA아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '154',
    '1682819381'
    )
INSERT INTO items VALUES ('1945464077',
        '착한떡 제주해풍쑥개떡 1kg (1+1) / 개별포장떡 /설기',
        23800,
        12900,
        45,
        '착한떡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '155',
    '1945464077'
    )
INSERT INTO items VALUES ('2006782792',
        '[삼성전자](사전판매) 갤럭시S21 울트라 5G 자급제폰 SM-G998N',
        1452000,
        1452000,
        0,
        '삼성공식온라인판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '156',
    '2006782792'
    )
INSERT INTO items VALUES ('1311171220',
        '12%쿠폰 밀크기모 성인/주니어 홈웨어 잠옷세트',
        39600,
        11900,
        69,
        '모스트맘')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '157',
    '1311171220'
    )
INSERT INTO items VALUES ('1879059262',
        '[탑텐키즈](신세계타임스퀘어점패션관)[탑텐키즈] 20FW 신상 아동 온에어세트',
        7900,
        6010,
        23,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '158',
    '1879059262'
    )
INSERT INTO items VALUES ('1779696398',
        '[테크]테크 파워 액체세제(겸용) 대용량 8L',
        14900,
        11900,
        20,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '159',
    '1779696398'
    )
INSERT INTO items VALUES ('1754154663',
        '[크리오]덴티메이트시즌2 초극세모 5+5+5+5입',
        14900,
        9900,
        33,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '160',
    '1754154663'
    )
INSERT INTO items VALUES ('1649311897',
        '[비비고]비비고 사골곰탕 500g 18개',
        18900,
        18900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '161',
    '1649311897'
    )
INSERT INTO items VALUES ('1544490436',
        '[퍼펙트바이오틱스]퍼펙트바이오틱스 슈퍼 프로바이오틱스 19 6박스',
        19900,
        17900,
        10,
        '(주)비타민마을')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '162',
    '1544490436'
    )
INSERT INTO items VALUES ('1754998124',
        '[크리넥스]크리넥스 3겹 데코소프트 33MX24롤 X2팩화장지/휴지',
        57900,
        33900,
        41,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '163',
    '1754998124'
    )
INSERT INTO items VALUES ('1548083569',
        '[팬콧키즈]22%중복쿠폰 팬콧키즈 맨투맨/셋업/실내복/레깅스',
        35800,
        17900,
        50,
        '팬콧공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '164',
    '1548083569'
    )
INSERT INTO items VALUES ('189842449',
        '요즘에/주말특가+12%/융털/기모팬츠/슬랙스/빅사이즈',
        33000,
        9900,
        70,
        '요즘에')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '165',
    '189842449'
    )
INSERT INTO items VALUES ('1502793298',
        '2봉/산동고기왕만두1.4kg+김치왕만두1.4kg/만두 간식',
        29800,
        15900,
        46,
        '미소푸드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '166',
    '1502793298'
    )
INSERT INTO items VALUES ('1151854785',
        '[블루스카이]인증점 삼성 공기청정기 AX60N5580WDD 전국무료배송',
        429000,
        286000,
        33,
        '삼성공식다원')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '167',
    '1151854785'
    )
INSERT INTO items VALUES ('231172986',
        '[아침농산]국산 서리태 2kg 속청 2020년산 햇곡',
        32800,
        22900,
        30,
        '아침농산잡곡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '168',
    '231172986'
    )
INSERT INTO items VALUES ('898903185',
        '[우르오스]우르오스 올인원 스킨밀크/스킨로션 200ml 택1',
        26730,
        24070,
        9,
        'CJmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '169',
    '898903185'
    )
INSERT INTO items VALUES ('1321028651',
        'NEW땡큐 화장지 (30롤 x 2팩) / 3겹 두루마리 휴지',
        30000,
        9700,
        67,
        '올다룸')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '170',
    '1321028651'
    )
INSERT INTO items VALUES ('2004391422',
        '(풀빛)풀빛 핀두스의 아주 특별한 이야기 시리즈 전9권+워크북/재정가세트',
        72000,
        71000,
        1,
        'G_맘챌')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '171',
    '2004391422'
    )
INSERT INTO items VALUES ('1888337932',
        '[필립스]PHILIPS 전기면도기 SkinIQ 5000 S5581/10 버건디레드',
        199000,
        129000,
        35,
        '(주)필립스코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '172',
    '1888337932'
    )
INSERT INTO items VALUES ('1398744808',
        '하누소 왕갈비탕(650gX6팩) 세트',
        36000,
        34200,
        5,
        '하누소푸드시스템')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '173',
    '1398744808'
    )
INSERT INTO items VALUES ('2006773691',
        '[삼성전자](사전판매) 갤럭시S21 플러스 5G 자급제폰 SM-G996N',
        1199000,
        1199000,
        0,
        '삼성공식온라인판매점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '174',
    '2006773691'
    )
INSERT INTO items VALUES ('1980473673',
        '닌텐도 스위치 동물의 숲 에디션 배터리 개선판',
        439000,
        439000,
        0,
        '아이게임몰1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '175',
    '1980473673'
    )
INSERT INTO items VALUES ('1721987198',
        '[스타벅스]네스프레소 호환 스타벅스 100캡슐',
        69900,
        52900,
        24,
        '플라이유로')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '176',
    '1721987198'
    )
INSERT INTO items VALUES ('1473200826',
        '[스팸]스팸 클래식 340g 10개',
        32900,
        32900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '177',
    '1473200826'
    )
INSERT INTO items VALUES ('1853404348',
        '(G) KF94 노이몬 마스크 중형 50매 새부리형 미세먼지',
        28900,
        28900,
        0,
        '해밀컴퍼니')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '178',
    '1853404348'
    )
INSERT INTO items VALUES ('1877047648',
        '킹코어 3종 코어운동 복근운동 뱃살제거 아이큐샵',
        29800,
        29800,
        0,
        '아이큐샵홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '179',
    '1877047648'
    )
INSERT INTO items VALUES ('1918255274',
        '(숏핑) 5분OK  미식모험 다돼지 수육(국내산) 돼지 국밥 8팩+깍두기 1팩 증정',
        29900,
        23920,
        20,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '180',
    '1918255274'
    )

INSERT INTO items VALUES ('1837727066',
        '[마이키즈]그린핑거 마이키즈 수분산뜻워시1000ml',
        27900,
        13900,
        50,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '181',
    '1837727066'
    )
INSERT INTO items VALUES ('1896085655',
        '[늘바른]블랙 앵거스 등심 척아이롤(등심/목심)200g4팩g+참소스',
        28500,
        19900,
        30,
        '아이푸드라이프2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '182',
    '1896085655'
    )
INSERT INTO items VALUES ('2007047473',
        '[푸마]푸마 푸마 심리스 드로즈 12종 패키지',
        89900,
        88900,
        1,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '183',
    '2007047473'
    )
INSERT INTO items VALUES ('805459425',
        '[슈프림]남녀공용 후드티 남성여성 빅사이즈티셔츠 기모맨투맨',
        33000,
        9900,
        70,
        '문컬렉션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '184',
    '805459425'
    )
INSERT INTO items VALUES ('1807976048',
        '[비달사순]비달사순 2000W 전문가용 헤어드라이기 VSD5129K',
        20800,
        20800,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '185',
    '1807976048'
    )
INSERT INTO items VALUES ('1493501531',
        '[3M]스카치 테이프 원터치 디스펜서(핑크) +리필 2롤증정',
        16900,
        15550,
        7,
        '3Monline')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '186',
    '1493501531'
    )
INSERT INTO items VALUES ('1806038557',
        '[락앤락]골드마스터/스팀에어프라이어/ 쿡에어 모음',
        189000,
        60900,
        67,
        '본사직영-락앤락몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '187',
    '1806038557'
    )
INSERT INTO items VALUES ('1813546417',
        '[램프쿡] 자동회전냄비 HS-0010',
        109000,
        99000,
        9,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '188',
    '1813546417'
    )
INSERT INTO items VALUES ('1911977722',
        '한입에 쏙 오란다 800g 옛날과자 대용량 MD6',
        9400,
        4700,
        50,
        '미다몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '189',
    '1911977722'
    )
INSERT INTO items VALUES ('1895033274',
        '[키즈마루]국산 3중 비말차단 마스크 300매 KF-AD MB필터 마스크',
        20000,
        19430,
        2,
        '굿셀goodsell')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '190',
    '1895033274'
    )
INSERT INTO items VALUES ('667938939',
        '이니스프리 1월 이니데이 설세트 기초라인 UP TO 30%',
        24000,
        19200,
        20,
        '이니스프리직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '191',
    '667938939'
    )
INSERT INTO items VALUES ('1920641521',
        '[맥심]화이트골드 커피믹스  160T+160T : 쿠폰가 29900원~',
        44000,
        32900,
        25,
        '큐마트솔루션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '192',
    '1920641521'
    )
INSERT INTO items VALUES ('1103688403',
        '[맥심]화이트골드 커피믹스 160Tx2 /쿠폰적용가29900원',
        44000,
        32900,
        25,
        '이티마트')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '193',
    '1103688403'
    )
INSERT INTO items VALUES ('173366583',
        '가정식 생포기김치10Kg /총각 /배추김치/ HACCP인증',
        30900,
        30900,
        0,
        '푸~드 뱅크')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '194',
    '173366583'
    )
INSERT INTO items VALUES ('1759598140',
        '탄탄한 문법으로 쓰기와 말하기 수행평가까지/The Best Grammar/The Best Grammar PLUS',
        120000,
        99900,
        16,
        '수퍼맘북스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '195',
    '1759598140'
    )
INSERT INTO items VALUES ('1791739177',
        '[스마트에코]아기물티슈 모데라토 캡형 80매X20팩 엠보물티슈',
        29800,
        14900,
        50,
        '제이니시')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '196',
    '1791739177'
    )
INSERT INTO items VALUES ('1604479096',
        '[베베앙]베베앙 아기물티슈  시그니처 대용량 100매 캡형 10팩',
        27400,
        13430,
        50,
        '아기물티슈베베앙')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '197',
    '1604479096'
    )
INSERT INTO items VALUES ('1904599145',
        '[온더바디]퓨어시카 베이비파우더 바디로션 1000ml  2개',
        25800,
        16900,
        34,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '198',
    '1904599145'
    )
INSERT INTO items VALUES ('1703899783',
        '[아토세이프]고농축 액체세제 2.5L X 4개 세탁세제 총10000ml',
        26300,
        7900,
        69,
        '아토세이프본사')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '199',
    '1703899783'
    )
INSERT INTO items VALUES ('1991966006',
        '에어데이즈 KF94 새부리형 국산 마스크 대형 50매',
        31500,
        29000,
        7,
        '블루택스토리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL',
    'ALL',
    '200',
    '1991966006'
    )
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G01 패션의류
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '1',
    '1986969051'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '2',
    '787562120'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '3',
    '189842449'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '4',
    '1280233513'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '5',
    '1606293717'
    )
INSERT INTO items VALUES ('1284344651',
        '데이뮤즈 9900균일 원피스/양털/코트/패딩/맨투맨/롱',
        33000,
        9900,
        70,
        '데이뮤즈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '6',
    '1284344651'
    )
INSERT INTO items VALUES ('810518655',
        '성진  원피스 코트 팬츠 롱패딩',
        32900,
        9900,
        69,
        '성진패션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '7',
    '810518655'
    )
INSERT INTO items VALUES ('776582823',
        '엄마옷로즈맘 인기상품70종세일 5060중년여성의류',
        43000,
        12900,
        70,
        '엄마옷로즈맘')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '8',
    '776582823'
    )
INSERT INTO items VALUES ('1688200696',
        '12%쿠폰 겨울한파특가 니트/코트/기모티/패딩',
        36300,
        10900,
        69,
        '메이시스1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '9',
    '1688200696'
    )
INSERT INTO items VALUES ('1551794470',
        '데이데이 균일가 양털/맨투맨/후드/기모/원피스/니트',
        33000,
        9900,
        70,
        '데이데이-dayday')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '10',
    '1551794470'
    )
INSERT INTO items VALUES ('1430266775',
        '시크루즈/12%/기모원피스/SET상품/니트/빅사이즈',
        33000,
        9900,
        70,
        '시크루즈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '11',
    '1430266775'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '12',
    '576442682'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '13',
    '1108678685'
    )

INSERT INTO items VALUES ('373058782',
        '다온샵 시즌오프+12%/기모팬츠/융털/슬랙스/빅사이즈',
        33000,
        9900,
        70,
        '다온샵.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '14',
    '373058782'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '15',
    '1495278850'
    )
INSERT INTO items VALUES ('1409488407',
        '스웨덴세탁소 겨울신상/빅사이즈/롱원피스/니트/코트',
        59600,
        17900,
        69,
        '스웨덴세탁소')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '16',
    '1409488407'
    )
INSERT INTO items VALUES ('1718416286',
        '티탁 12%쿠폰/맨투맨/후드/원피스/롱티/빅사이즈/세트',
        39600,
        11900,
        69,
        '주식회사티탁')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '17',
    '1718416286'
    )
INSERT INTO items VALUES ('753970658',
        '제니트 겨울신상 84종 니트 폴라 스웨터 터틀넥',
        43000,
        12900,
        70,
        'JENIT')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '18',
    '753970658'
    )
INSERT INTO items VALUES ('1817237042',
        '루즈델리 12%쿠폰 빅사이즈/기모/원피스/스커트/세트',
        43000,
        12900,
        70,
        '루즈델리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '19',
    '1817237042'
    )
INSERT INTO items VALUES ('1481263644',
        '코코블랑 가을신상 블라우스 원피스 가디건',
        63000,
        18900,
        70,
        '코코블랑1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '20',
    '1481263644'
    )
INSERT INTO items VALUES ('1309233372',
        '프라이데이 겨울신상 기모맨투맨/후드티/빅사이즈',
        43000,
        12900,
        70,
        '프라이데이7')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '21',
    '1309233372'
    )
INSERT INTO items VALUES ('1615409666',
        '에이블린/12%할인/기모원피스/티셔츠/맨투맨/스커트',
        43000,
        12900,
        70,
        '에이블린A')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '22',
    '1615409666'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '23',
    '221969619'
    )
INSERT INTO items VALUES ('1517719492',
        '메이킹유 쿠폰12% 니트원피스/뽀글이/맨투맨/코트',
        33000,
        9900,
        70,
        '메이킹유')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '24',
    '1517719492'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '25',
    '1311171220'
    )
INSERT INTO items VALUES ('972418391',
        '[BYC]여성팬티/노라인/위생생리/보정/엉뽕/요실금/최다종류',
        19600,
        5900,
        69,
        '주)언더라인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '26',
    '972418391'
    )
INSERT INTO items VALUES ('1727198869',
        '12%쿠폰 달리샵 겨울 기모원피스/세트/티셔츠/니트',
        33000,
        9900,
        70,
        '달리샵1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '27',
    '1727198869'
    )
INSERT INTO items VALUES ('197555399',
        '투투 기모빵빵 청바지/슬랙스/배기/골덴 5XL',
        33000,
        9900,
        70,
        '투투22')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '28',
    '197555399'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '29',
    '1373777190'
    )
INSERT INTO items VALUES ('1322490033',
        '로드스타 필수아이템 순면 긴팔/반팔 무지티셔츠',
        13000,
        3900,
        70,
        '로드스타14')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '30',
    '1322490033'
    )
INSERT INTO items VALUES ('166590237',
        '[BYC]내의/내복/남자/남성/여자/여성/기모/겨울/발열',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '31',
    '166590237'
    )
INSERT INTO items VALUES ('1517019865',
        '메이킹유 쿠폰12% 니트원피스/뽀글이/맨투맨/코트',
        33000,
        9900,
        70,
        '메이킹유')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '32',
    '1517019865'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '33',
    '965313589'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '34',
    '805459425'
    )
INSERT INTO items VALUES ('1670609306',
        '비니수 기획특가 겨울 신상모음전',
        12900,
        3900,
        69,
        '비니수1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '35',
    '1670609306'
    )
INSERT INTO items VALUES ('215673140',
        '스위트바니 겨울신상 롱원피스/맨투맨/후드/빅사이즈',
        43000,
        12900,
        70,
        '스위트바니')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '36',
    '215673140'
    )
INSERT INTO items VALUES ('1487774180',
        '시스터 겨울한파 세일~ 빅사이즈롱티/후드/원피스',
        19600,
        5900,
        69,
        '케이엠컴퍼니01')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '37',
    '1487774180'
    )
INSERT INTO items VALUES ('1975776752',
        '쇼인더룸 12% 5900/11360특가 맨투맨/니트/빅사이즈',
        42900,
        12900,
        69,
        '로드블링')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '38',
    '1975776752'
    )
INSERT INTO items VALUES ('1162884079',
        '한파세일+12%/1+1 융털기모 레깅스/팬츠/빅사이즈~4XL',
        9000,
        7900,
        12,
        '비비드글램_VIVIDGLAM')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '39',
    '1162884079'
    )
INSERT INTO items VALUES ('1917953479',
        '단비샵 겨울신상/뽀글이집업/패딩/가디건/코트/니트',
        36300,
        10900,
        69,
        '단비샵입니다')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '40',
    '1917953479'
    )
INSERT INTO items VALUES ('1789464964',
        '[디키즈]22%추가쿠폰_디키즈 겨울 아우터/기모 상품 마감 세일',
        53000,
        15900,
        70,
        '디키즈코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '41',
    '1789464964'
    )
INSERT INTO items VALUES ('1975613741',
        '예쁜걸 겨울신상/기모/후드/맨투맨/원피스/세트/하의',
        23000,
        6900,
        70,
        'voguegirl')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '42',
    '1975613741'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '43',
    '1494979529'
    )
INSERT INTO items VALUES ('2001008782',
        '[닥스셔츠][대구백화점 II관] [닥스셔츠]닥스 봄상품 체크 긴팔남방 14종택1(DHG2SHCL110-N1외)',
        60000,
        47400,
        21,
        '대구백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '44',
    '2001008782'
    )
INSERT INTO items VALUES ('166590202',
        '[트라이]여성팬티 5매/여자/여성/속옷/미디/맥시/위생/삼각/면',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '45',
    '166590202'
    )
INSERT INTO items VALUES ('929105077',
        '(12%쿠폰)한파대비 융털바지/기모트레이닝/기모양말',
        23000,
        6900,
        70,
        '(주)상상투')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '46',
    '929105077'
    )
INSERT INTO items VALUES ('1566013256',
        '시크루즈/12%/기모티셔츠/맨투맨/니트/빅사이즈',
        23000,
        6900,
        70,
        '시크루즈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '47',
    '1566013256'
    )

INSERT INTO items VALUES ('1725467202',
        '루나샵  시즌오프 붐신상추가 티셔츠/맨투맨/원피스',
        33000,
        9900,
        70,
        '루나샵2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '48',
    '1725467202'
    )
INSERT INTO items VALUES ('731274728',
        '[데일리앤]겨울 기모 루즈핏 맨투맨 목폴라 니트 티셔츠',
        32000,
        9800,
        69,
        '데일리앤')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '49',
    '731274728'
    )
INSERT INTO items VALUES ('628153284',
        '체리온 12%쿠폰 기모롱티/빅사이즈/후드티/기모맨투맨',
        39300,
        11800,
        69,
        '체리온')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '50',
    '628153284'
    )
INSERT INTO items VALUES ('2000376043',
        '[엘레쎄](대구신세계)[엘레쎄] 남녀 공용 맨투맨 후드티 모음 7종 (EJ4UHTR357 EJ4UHTR359 EJ4UHTR365 EJ4UHTR36...',
        15000,
        12120,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '51',
    '2000376043'
    )
INSERT INTO items VALUES ('1913148836',
        '[디키즈](광주신세계)디키즈 기모후드 6종택1 (DSQ3UTHT441 DSR3UTHT346 DMR3UTHT508 DSQ3UTHT442 DSQ3UTHT430 D...',
        35000,
        28270,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '52',
    '1913148836'
    )
INSERT INTO items VALUES ('1677882956',
        '12% 남녀 융기모스웨트4종세트/기모바지/코트/니트',
        99600,
        29900,
        69,
        '리베레츠')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '53',
    '1677882956'
    )
INSERT INTO items VALUES ('1895164110',
        '[에비수]에비수 브랜드 겨울 니트/맨투맨/다운/점퍼/패딩/데님',
        63000,
        18900,
        70,
        '에비수샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '54',
    '1895164110'
    )
INSERT INTO items VALUES ('974668803',
        '한파세일+12%/1+1 융기모 레깅스/팬츠/빅사이즈~4XL',
        29600,
        8900,
        69,
        '퍼스트클로')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '55',
    '974668803'
    )
INSERT INTO items VALUES ('1802651142',
        '발레리 라이크라 V리프팅 컬렉션 6+2세트',
        79900,
        79900,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '56',
    '1802651142'
    )
INSERT INTO items VALUES ('1288386776',
        '[보니알렉스]코트/점퍼/자켓/원피스 4900원부터',
        9500,
        9500,
        0,
        'Fashion_Outlet')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '57',
    '1288386776'
    )
INSERT INTO items VALUES ('1760154947',
        '[닉스]1월 겨울 클라이언스 다운점퍼/후리스/기모데님 특가',
        99600,
        29900,
        69,
        'NIX_HUM-본사직영')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '58',
    '1760154947'
    )
INSERT INTO items VALUES ('1823978020',
        '12%쿠폰+균일가/보아털/융털/트레이닝복세트',
        66000,
        19800,
        70,
        '세빈옴므')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '59',
    '1823978020'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '60',
    '1503231163'
    )
INSERT INTO items VALUES ('1158276673',
        '겨울신상 홈웨어 잠옷특가 사은품',
        29600,
        8900,
        69,
        '메이시스1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '61',
    '1158276673'
    )
INSERT INTO items VALUES ('801815493',
        '1+1 트레이닝바지 기모 등산바지 티셔츠 남성 작업복',
        43000,
        12900,
        70,
        '에스비스토어-')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '62',
    '801815493'
    )
INSERT INTO items VALUES ('1786992530',
        '(12% 중복쿠폰)4XL빅사이즈 기모팬츠/슬랙스 시즌오프',
        22900,
        6900,
        69,
        'yaaho')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '63',
    '1786992530'
    )
INSERT INTO items VALUES ('1806509264',
        '홈쇼핑 남녀 겨울패딩코트 기모바지 울니트 원피스',
        49600,
        14900,
        69,
        '코리타2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '64',
    '1806509264'
    )
INSERT INTO items VALUES ('1693435807',
        '폴로 하이넥 후드집업 1+1 대한민국1등 10만장돌파기념',
        133000,
        39900,
        70,
        '가오간지')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '65',
    '1693435807'
    )
INSERT INTO items VALUES ('166590234',
        '[비버리힐스폴로클럽]1매2900원/드로즈/사각/팬티/남성/남자/세트/면/속옷',
        26000,
        7800,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '66',
    '166590234'
    )
INSERT INTO items VALUES ('1444224360',
        '[머스트비]머스트비 겨울 신상 핸드메이드/코트/경량/다운/니트',
        100000,
        30000,
        70,
        '머스트비KF')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '67',
    '1444224360'
    )
INSERT INTO items VALUES ('777247382',
        '패션라인 겨울신상 블라우스/원피스/니트/가디건/양털',
        66300,
        19900,
        69,
        '패션라인11')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '68',
    '777247382'
    )
INSERT INTO items VALUES ('1934828459',
        '[크리스티나앤코] 물결 패딩+후드 베스트 세트',
        39900,
        36800,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '69',
    '1934828459'
    )
INSERT INTO items VALUES ('1923553682',
        '[이너리즘]1+1 이너리즘 극세사 홈웨어 밍크 융털 수면바지 잠옷',
        29600,
        8900,
        69,
        '이너리즘')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '70',
    '1923553682'
    )
INSERT INTO items VALUES ('166590241',
        '[트라이]국산 5매/트렁크/사각/팬티/남자/남성/빅사이즈/속옷',
        39600,
        11900,
        69,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '71',
    '166590241'
    )
INSERT INTO items VALUES ('1879126178',
        '어반더룸 집콕룩/기모원피스/투피스/코듀로이/니트 등',
        49600,
        14900,
        69,
        '어반더룸')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '72',
    '1879126178'
    )
INSERT INTO items VALUES ('169295221',
        '신상/기모/남자청바지/남성/빅사이즈/스판/바지',
        46000,
        13800,
        70,
        '위드진1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '73',
    '169295221'
    )
INSERT INTO items VALUES ('907967540',
        '[핫코드]겨울신상 남자 기모청바지/빅사이즈/스판/면바지/행사',
        59600,
        17900,
        69,
        '핫코드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '74',
    '907967540'
    )
INSERT INTO items VALUES ('2000911667',
        '[트라이엄프](신세계강남점)[트라이엄프] 4종 택1 브라햄팬티 세트 (TWB0513TWB0609TWB0615TWB0622)',
        18000,
        13970,
        22,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '75',
    '2000911667'
    )
INSERT INTO items VALUES ('1985585454',
        '타미힐피거남녀공용기모맨투맨6종택1',
        29900,
        29570,
        1,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '76',
    '1985585454'
    )
INSERT INTO items VALUES ('1725153067',
        '단하루12%할인쿠폰 기모 후드티 집업 티셔츠 빅사이즈',
        26300,
        7900,
        69,
        '이프지.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '77',
    '1725153067'
    )

INSERT INTO items VALUES ('192173793',
        '겨울세일/하객룩/오피스/원피스/빅사이즈',
        50000,
        49800,
        0,
        '시크라인(CHICLINE)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '78',
    '192173793'
    )
INSERT INTO items VALUES ('1873175246',
        '에이앤디 아뜰리에 1st 호주산 양모 100% 솜사탕 베스트',
        59900,
        53910,
        10,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '79',
    '1873175246'
    )
INSERT INTO items VALUES ('1912374335',
        '12%쿠폰/균일가/숏패딩/하프패딩/패딩조끼/트레이닝복',
        66000,
        19800,
        70,
        '세빈옴므')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '80',
    '1912374335'
    )
INSERT INTO items VALUES ('960753074',
        '브라썸/브라팬티세트 ABCD컵/왕뽕/빅사이즈/여성속옷',
        36300,
        10900,
        69,
        '파란언더웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '81',
    '960753074'
    )
INSERT INTO items VALUES ('1345149344',
        '브리치x럭키567 F/W 맨투맨/원피스/패딩/후드',
        49300,
        14800,
        69,
        'brich')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '82',
    '1345149344'
    )
INSERT INTO items VALUES ('161861192',
        '[아날도바시니]드로즈10매 세트 남자 남성 팬티 속옷 빅사이즈 스판',
        63000,
        18900,
        70,
        '비앤비미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '83',
    '161861192'
    )
INSERT INTO items VALUES ('1663724654',
        '[스위브]다운/패딩 새해특가 19900원~',
        30600,
        30600,
        0,
        'Fashion_Outlet')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '84',
    '1663724654'
    )
INSERT INTO items VALUES ('1987470777',
        ' 감사특가 [yunni.G] 유니지 리얼 양모100 하프코트 ',
        79000,
        72700,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '85',
    '1987470777'
    )
INSERT INTO items VALUES ('1993510431',
        '듀즈파파/남성겨울/패딩/뽀글이집업/조거팬츠/청바지',
        66300,
        19900,
        69,
        '단비샵입니다')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '86',
    '1993510431'
    )
INSERT INTO items VALUES ('1570637302',
        '데이데이 맨투맨/기모/후드티/양털집업/팬츠/니트',
        33000,
        9900,
        70,
        '데이데이-dayday')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '87',
    '1570637302'
    )
INSERT INTO items VALUES ('898007895',
        '5+1 긴팔티 긴팔 티셔츠 남성남자 무지 면티 빅사이즈',
        26300,
        7900,
        69,
        '문컬렉션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '88',
    '898007895'
    )
INSERT INTO items VALUES ('266575292',
        '겨울바지/기모/남성/남자청바지/융본딩/빅사이즈',
        52600,
        15800,
        69,
        '위드진1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '89',
    '266575292'
    )
INSERT INTO items VALUES ('1502725511',
        '[Rosebud][히트상품]남영비비안 판도라/로즈버드 티나지 않는 여성 노라인 헴팬티 5종 세트(90~105)/ 비비안 로즈버',
        18900,
        17900,
        5,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '90',
    '1502725511'
    )
INSERT INTO items VALUES ('1987041955',
        '연말 집콕파티 잠옷90종 겨울 극세사 파자마 원피스',
        19900,
        8900,
        55,
        '어나더뷰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '91',
    '1987041955'
    )
INSERT INTO items VALUES ('744192338',
        '12%할인쿠폰 롱패딩 숏패딩 여성점퍼자켓 빅사이즈',
        99000,
        29900,
        69,
        '이프지.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '92',
    '744192338'
    )
INSERT INTO items VALUES ('528849355',
        '[핫코드]겨울신상 남자 기모청바지/빅사이즈/면바지/스판/행사',
        46300,
        13900,
        69,
        '핫코드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '93',
    '528849355'
    )
INSERT INTO items VALUES ('1498699891',
        '[이지바이]겨울 베스트 아이템/기모티/플리스/자켓/패딩/바지',
        19600,
        5900,
        69,
        '(주)이지바이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '94',
    '1498699891'
    )
INSERT INTO items VALUES ('1682892413',
        '[캘빈클라인]CK언더웨어 남여 FW20신상 선물특가전 4천원대~',
        92000,
        27900,
        69,
        'ckmall1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '95',
    '1682892413'
    )
INSERT INTO items VALUES ('787245581',
        '[체리빌레]겨울 기모쉬폰원피스/니트원피스/모직/롱/미니/미디',
        49600,
        14900,
        69,
        'CHERRYVILLE')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '96',
    '787245581'
    )
INSERT INTO items VALUES ('1983920906',
        '씨티지 (CityGee) 호주산 양모100 투웨이 하프코트',
        129000,
        118700,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '97',
    '1983920906'
    )
INSERT INTO items VALUES ('720658634',
        '[비버리힐스폴로클럽]10종세트/드로즈 남성 남자 팬티 속옷 빅사이즈 스판',
        66000,
        19800,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '98',
    '720658634'
    )
INSERT INTO items VALUES ('156577461',
        'BYC 보디히트 外 남녀 내복/내의 기모 발열 남자 여자',
        33000,
        9900,
        70,
        '♡이너샵♡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '99',
    '156577461'
    )
INSERT INTO items VALUES ('1430261089',
        '[반에이크][모다아울렛]반에이크 백화점동일상품 신년특가 이너/팬츠 外 1만원대부터',
        30000,
        27300,
        9,
        'MODA아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    'ALL',
    '100',
    '1430261089'
    )
패션의류 브랜드 여성의류
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '1',
    '1986969051'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '2',
    '1288386776'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '3',
    '1444224360'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '4',
    '1934828459'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '5',
    '1987470777'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '6',
    '1983920906'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '7',
    '1430261089'
    )
INSERT INTO items VALUES ('1116258684',
        '[모카썸]겨울 BEST50종 후리스/조거팬츠/기모후드/원피스',
        26300,
        7900,
        69,
        '모카썸')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '8',
    '1116258684'
    )
INSERT INTO items VALUES ('1924647458',
        '핏짱 소재짱   [TAG me] 태그미 짱짱 기모팬츠4종 ',
        59900,
        55200,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '9',
    '1924647458'
    )
INSERT INTO items VALUES ('1693435171',
        '[미센스]최대22%쿠폰 FW 시즌오프/베스트 코트/니트/원피스 외',
        133000,
        39900,
        70,
        '미센스/반에이크')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '10',
    '1693435171'
    )

INSERT INTO items VALUES ('1234579017',
        '[SOUP]SOUP外 겨울 아우터 신상 패딩/코트/이너',
        113000,
        33900,
        70,
        'SOUP-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '11',
    '1234579017'
    )
INSERT INTO items VALUES ('1889123974',
        '[예쎄][인기초특가] 예쎄(YESSE) 경량 다운 롱 후드 재킷+ 베스트 세트 ',
        49000,
        45100,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '12',
    '1889123974'
    )
INSERT INTO items VALUES ('1916658645',
        '[쿠즈텡] 터틀 리브 니트5종',
        39900,
        39900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '13',
    '1916658645'
    )
INSERT INTO items VALUES ('1256823118',
        '[블루레이스]블루레이스 20FW HOT SALE 니트/티셔츠/팬츠 외',
        59300,
        17800,
        69,
        'BLUREISS')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '14',
    '1256823118'
    )
INSERT INTO items VALUES ('1992658937',
        '에이앤디 아뜰리에 1st 프리미엄 밍크 x 양모 100% 트리플 베스트',
        69000,
        69000,
        0,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '15',
    '1992658937'
    )
INSERT INTO items VALUES ('1655774766',
        '[올리비아로렌]최대22%쿠폰 FW 시즌오프 다운/패딩/코트외',
        119600,
        35900,
        69,
        '올리비아로렌 공식')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '16',
    '1655774766'
    )
INSERT INTO items VALUES ('1953682087',
        '[르오트][르오트] [홈쇼핑방송/(LeOT)] 다이아퀼팅 천연라쿤퍼 구스다운',
        44800,
        37190,
        16,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '17',
    '1953682087'
    )
INSERT INTO items VALUES ('1738553102',
        '론칭가99 000원 로렌비달 타스마니아 울100% 홀가먼트 니트2종',
        39000,
        39000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '18',
    '1738553102'
    )
INSERT INTO items VALUES ('1742526138',
        '[페이지플린]22%중복+무배 아우터맛집~패딩/코트/니트 핵특가전',
        82000,
        24600,
        70,
        '페이지플린')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '19',
    '1742526138'
    )
INSERT INTO items VALUES ('1912447101',
        '[카시바디][카시바디] 호주  양모 하프코트',
        99000,
        98000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '20',
    '1912447101'
    )
INSERT INTO items VALUES ('1896690653',
        '[모르간]런칭가 99 000원  MORGAN 테일러드 울 코트',
        69000,
        69000,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '21',
    '1896690653'
    )
INSERT INTO items VALUES ('2004463068',
        '론칭가89 900원 더엣지 FW 윈터올데이셋업 4PCS',
        49900,
        49900,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '22',
    '2004463068'
    )
INSERT INTO items VALUES ('1991377945',
        '기존가89 900 더엣지 FW 울블렌딩 터틀넥 니트 4종',
        49900,
        49900,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '23',
    '1991377945'
    )
INSERT INTO items VALUES ('1493559466',
        '[SOUP]SOUP外 베스트 상품 겨울 클리어런스 시작',
        116300,
        34900,
        69,
        'SOUP-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '24',
    '1493559466'
    )
INSERT INTO items VALUES ('1860040091',
        '론칭가79 900원 지오송지오 20FW FAUX 레더자켓',
        39900,
        39900,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '25',
    '1860040091'
    )
INSERT INTO items VALUES ('1828316105',
        '크로커외 겨울 정기세일 니트/점퍼/코트/팬츠+17%쿠폰',
        166300,
        49900,
        69,
        '형지리테일온라인몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '26',
    '1828316105'
    )
INSERT INTO items VALUES ('1789831079',
        '[나인스텝]독점 겨울세일~22%쿠폰+무배 패딩/니트外',
        76330,
        22900,
        69,
        '나인스텝')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '27',
    '1789831079'
    )
INSERT INTO items VALUES ('1590756556',
        '[올리비에스클로젯]WINTER CLEARANCE SALE 7900~',
        46000,
        13900,
        69,
        '올리비에스클로젯')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '28',
    '1590756556'
    )
INSERT INTO items VALUES ('1955891431',
        '최신상  VOLL 벨라인 덕 다운 푸퍼 숏패딩 점퍼',
        59900,
        58900,
        1,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '29',
    '1955891431'
    )
INSERT INTO items VALUES ('2000311551',
        '[플라스틱아일랜드](신세계강남점)[플라스틱아일랜드] 올 겨울 아우터 끝판왕  데일리 코트3종 (PL4EC081 PL4EC082 PL4EC083)',
        109000,
        83830,
        23,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '30',
    '2000311551'
    )
INSERT INTO items VALUES ('1958876991',
        '[yunni.G] 유니지 양모100 폭스퍼 후드 하프코트 ',
        149000,
        137100,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '31',
    '1958876991'
    )
INSERT INTO items VALUES ('1876041513',
        '[랩][LAP][ 20가을]랩 우븐허리끈 7부 롱원피스 AL3WO881',
        69000,
        66240,
        4,
        'AK플라자1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '32',
    '1876041513'
    )
INSERT INTO items VALUES ('1916901284',
        '론칭가129 000원 지스튜디오 20FW 톨레뇨社 울100%니트+숄세트',
        69000,
        69000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '33',
    '1916901284'
    )
INSERT INTO items VALUES ('1986454499',
        '3만원인하 더엣지 FW 라이크라 릴렉스핏 기모데님 2종',
        39900,
        39900,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '34',
    '1986454499'
    )
INSERT INTO items VALUES ('1972587296',
        '셀렙샵에디션 20FW 양모100% 하프코트',
        139000,
        139000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '35',
    '1972587296'
    )
INSERT INTO items VALUES ('1940764072',
        '[블랙마틴싯봉][블랙마틴싯봉] 캐시미어 울 블렌디드 맥시롱코트',
        70000,
        69000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '36',
    '1940764072'
    )
INSERT INTO items VALUES ('1953217325',
        '[바네사리찌] 스노우 기모 블라우스4종',
        59900,
        59900,
        0,
        '공영쇼핑TV')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '37',
    '1953217325'
    )
INSERT INTO items VALUES ('1859647292',
        '[에이비플러스]쿠폰+무료배송 꾸안꾸 데일리룩 모음',
        196600,
        59000,
        69,
        'ab.plus본사직영')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '38',
    '1859647292'
    )
INSERT INTO items VALUES ('1951867440',
        '기존가99 000 더엣지 FW 스트레이트핏 기모데님 3종',
        69000,
        69000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '39',
    '1951867440'
    )

INSERT INTO items VALUES ('1946488627',
        '[카시바디]카시바디  리얼 사가폭스 호주 양모 100  하프코트',
        148000,
        136200,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '40',
    '1946488627'
    )
INSERT INTO items VALUES ('1930768723',
        '[플라스틱아일랜드](신세계강남점)코쿤핏 다운점퍼(PL4NZ162)',
        159000,
        114170,
        28,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '41',
    '1930768723'
    )
INSERT INTO items VALUES ('1930649363',
        '마르엘라로사티 겨울 여성 보아퍼 본딩팬츠3종',
        39900,
        37910,
        4,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '42',
    '1930649363'
    )
INSERT INTO items VALUES ('1885549191',
        '[모르간]런칭가 89 900원  MORGAN 울 헤링본 재킷',
        59900,
        59900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '43',
    '1885549191'
    )
INSERT INTO items VALUES ('2000933249',
        '[도티] [DOTTI] 여성 기모 레깅스 팬츠 3종',
        29900,
        29900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '44',
    '2000933249'
    )
INSERT INTO items VALUES ('1940098871',
        '키스해링 20FW 아이코닉 터틀넥니트 3종',
        39900,
        39510,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '45',
    '1940098871'
    )
INSERT INTO items VALUES ('1682888827',
        '[랩](신세계강남점)박시 더블 코트 (AK4WTE65)',
        59500,
        58490,
        1,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '46',
    '1682888827'
    )
INSERT INTO items VALUES ('1693433901',
        '[미센스]최대22%쿠폰 FW 베스트 아우터/원피스/니트 외',
        133000,
        39900,
        70,
        '미센스/반에이크')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '47',
    '1693433901'
    )
INSERT INTO items VALUES ('1352620754',
        '[에이비플러스]쿠폰+무료배송 편안하고 예쁜 갓성비템 SALE',
        159000,
        59000,
        62,
        'ab.plus본사직영')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '48',
    '1352620754'
    )
INSERT INTO items VALUES ('996247441',
        '[샐리]겨울 HOT 신상 + BEST 아이템까지 니트/기모/패딩 外',
        66000,
        19900,
        69,
        '(주)컨트롤케이앤제이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '49',
    '996247441'
    )
INSERT INTO items VALUES ('1906973367',
        '[라포프] 울 블렌디드 체크 자켓 1종',
        39000,
        39000,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '50',
    '1906973367'
    )
INSERT INTO items VALUES ('1874189953',
        '론칭가79 900원 타하리 20FW 카멜울 샤인 니트 2종',
        39900,
        39900,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '51',
    '1874189953'
    )
INSERT INTO items VALUES ('1966255344',
        '[머스트비][초특가] 머스트비 세미배기핏 본딩 팬츠 4종 ',
        39900,
        36800,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '52',
    '1966255344'
    )
INSERT INTO items VALUES ('1907744905',
        '[나인식스뉴욕]런칭가 89 900원 나인식스뉴욕 96ny 마이크로볼 숏',
        69900,
        69900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '53',
    '1907744905'
    )
INSERT INTO items VALUES ('1923691558',
        '[ENC 오조크 비지트인뉴욕] FW 니트  원피스  아우터 최종할인전 최대 70%',
        29900,
        29900,
        0,
        'NC_백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '54',
    '1923691558'
    )
INSERT INTO items VALUES ('1918254075',
        '[범퍼]범퍼 여성 플리스 재킷 3종',
        59900,
        56910,
        4,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '55',
    '1918254075'
    )
INSERT INTO items VALUES ('1927088191',
        '[씨티지] STELLA  호주 양모 베스트',
        77000,
        67000,
        12,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '56',
    '1927088191'
    )
INSERT INTO items VALUES ('1791730168',
        '[씨]씨/베스띠벨리 외 겨울 최종특가 패딩/코트/이너/팬츠',
        131200,
        39900,
        69,
        '(주)신원')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '57',
    '1791730168'
    )
INSERT INTO items VALUES ('1274167241',
        '[블루레이스]블루레이스외 최종가 Big sale 니트/팬츠/원피스 외',
        59300,
        17800,
        69,
        'BLUREISS')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '58',
    '1274167241'
    )
INSERT INTO items VALUES ('1826401517',
        '[지센]지센 새해맞이 세일 점퍼/코트/티셔츠+12%중복쿠폰',
        99600,
        29900,
        69,
        '웹뜰공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '59',
    '1826401517'
    )
INSERT INTO items VALUES ('1671312140',
        '알파카 니트 롱코트/ 엔엔에프',
        9900,
        9500,
        4,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '60',
    '1671312140'
    )
INSERT INTO items VALUES ('1916741497',
        '[머스트비][머스트비] 롱 경량 후드 다운 코트 1종',
        39900,
        39900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '61',
    '1916741497'
    )
INSERT INTO items VALUES ('1655673244',
        '[알트베니]알트베니여성 빅사이즈 원피스/티셔츠/블라우스/셔츠',
        33000,
        9900,
        70,
        'Altbeny')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '62',
    '1655673244'
    )
INSERT INTO items VALUES ('1862234561',
        '[LBL] 20FW NEW 퓨어 듀베 캐시미어100 카라 브이넥 홀가먼트 니트',
        59000,
        58000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '63',
    '1862234561'
    )
INSERT INTO items VALUES ('1892810884',
        '[모르간]런칭가 89 900원  MORGAN 울 더블버튼 코트',
        59900,
        59900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '64',
    '1892810884'
    )
INSERT INTO items VALUES ('2001334749',
        '오플  VW베라왕 20FW 시즌리스 패딩코트',
        79000,
        79000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '65',
    '2001334749'
    )
INSERT INTO items VALUES ('1971051439',
        '셀렙샵에디션 20FW 양모100% 퍼 베스트',
        79000,
        79000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '66',
    '1971051439'
    )
INSERT INTO items VALUES ('1971401959',
        '[르오트][르오트] 빅토리아 퀼팅 롱패딩코트+퀼팅 베스트 2종세트',
        23800,
        20950,
        11,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '67',
    '1971401959'
    )
INSERT INTO items VALUES ('1910240544',
        '[라우렐] 메리노울100 핸드메이드 하프 케이프 코트',
        69000,
        68000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '68',
    '1910240544'
    )

INSERT INTO items VALUES ('1862234563',
        '[LBL] 20FW NEW 퓨어 듀베 캐시미어100 브이넥 홀가먼트 니트',
        59000,
        58000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '69',
    '1862234563'
    )
INSERT INTO items VALUES ('1926016394',
        '일시불2만원 더엣지 FW 울블렌디드 자켓+팬츠 SET',
        59000,
        59000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '70',
    '1926016394'
    )
INSERT INTO items VALUES ('1933732463',
        'C2 여성 윈터 기모 레이저 데님 3종',
        49000,
        46550,
        5,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '71',
    '1933732463'
    )
INSERT INTO items VALUES ('1941977158',
        '[라우렐] 홀가먼트 캐시미어100 니트 풀오버',
        89000,
        88000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '72',
    '1941977158'
    )
INSERT INTO items VALUES ('1817713133',
        '[라인]해핑 시스루 러플 원피스(NWOPJF04)',
        47000,
        39950,
        15,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '73',
    '1817713133'
    )
INSERT INTO items VALUES ('1994446694',
        '앱20%적립/기획가 타하리20FW 시그니처 글렌체크 수트자켓+팬츠',
        59900,
        58710,
        1,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '74',
    '1994446694'
    )
INSERT INTO items VALUES ('1590243621',
        '[올리비에스클로젯]겨울마감 인기 이너 티셔츠 시즌오프 특가',
        26000,
        7900,
        69,
        '올리비에스클로젯')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '75',
    '1590243621'
    )
INSERT INTO items VALUES ('1764397632',
        '홈쇼핑 유명브랜드 F/W 신상이월 특가전/무료배송',
        26300,
        7900,
        69,
        '주식회사건원')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '76',
    '1764397632'
    )
INSERT INTO items VALUES ('1894670702',
        '[모르간]런칭가 99 000원 MORGAN 경량 구스다운 재킷',
        69000,
        69000,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '77',
    '1894670702'
    )
INSERT INTO items VALUES ('1975880314',
        '[미쏘]인조퍼후드 벨티드 여성형패딩 MIWJDAC10B',
        79900,
        79900,
        0,
        '이랜드몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '78',
    '1975880314'
    )
INSERT INTO items VALUES ('1762834084',
        '[베네통]갤러리아   19F/W  투톤 폭스퍼 덕다운 롱패딩 BAPD81961',
        199600,
        147710,
        25,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '79',
    '1762834084'
    )
INSERT INTO items VALUES ('1899549669',
        '[LBL] 20FW NEW 울캐시미어 머플러',
        20000,
        20000,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '80',
    '1899549669'
    )
INSERT INTO items VALUES ('1914409247',
        '[라우렐] 울 블렌딩 메탈 카라 니트 3종',
        49000,
        49000,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '81',
    '1914409247'
    )
INSERT INTO items VALUES ('1653525261',
        '[몰리올리] TISSAVEL FAUX 슈에뜨 자켓',
        59000,
        58000,
        1,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '82',
    '1653525261'
    )
INSERT INTO items VALUES ('1940857328',
        '[폴앤조][폴앤조] 코튼 블렌디드 코듀로이 팬츠 3종',
        39900,
        39900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '83',
    '1940857328'
    )
INSERT INTO items VALUES ('1890348842',
        '론칭가99 000원 타하리 20FW 릴렉스 니트 셋업 4종',
        49000,
        39000,
        20,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '84',
    '1890348842'
    )
INSERT INTO items VALUES ('1920166990',
        '[SOUP](신세계경기점)숲 코듀로이 밴딩 팬츠 (SWALP80)',
        31200,
        22230,
        28,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '85',
    '1920166990'
    )
INSERT INTO items VALUES ('1913922243',
        'VW베라왕  20FW 클래시 하프다운코트',
        89000,
        89000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '86',
    '1913922243'
    )
INSERT INTO items VALUES ('1918189367',
        '오야니 밍크카라 양가죽 구스다운 코트',
        139000,
        139000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '87',
    '1918189367'
    )
INSERT INTO items VALUES ('1925329351',
        '[랩](신세계타임스퀘어점리빙관)더블 루즈핏 핸디 코트 (AL4WTB61)',
        143400,
        119030,
        16,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '88',
    '1925329351'
    )
INSERT INTO items VALUES ('1704903100',
        '[마담엘레강스] 세실 밍크카라 알파카코트',
        199000,
        199000,
        0,
        '공영쇼핑TV')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '89',
    '1704903100'
    )
INSERT INTO items VALUES ('1906276287',
        '[씨씨콜렉트]버튼 포인트 루즈핏 벨티드 핸드메이드 코트(C204MSG574)',
        284500,
        210530,
        26,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '90',
    '1906276287'
    )
INSERT INTO items VALUES ('2000417895',
        '루시앙 여성 캐시터치 니트 4종 택1 ',
        10000,
        9800,
        2,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '91',
    '2000417895'
    )
INSERT INTO items VALUES ('1957072779',
        '[카라](현대Hmall)KARRA (77까지)리얼밍크양모배색퍼베스트_KB0WVT523M',
        94900,
        74980,
        20,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '92',
    '1957072779'
    )
INSERT INTO items VALUES ('1975206397',
        '3만원인하 더엣지 FW 윈터 심플리 셋업 4PCS',
        59900,
        59310,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '93',
    '1975206397'
    )
INSERT INTO items VALUES ('1872272530',
        '[아이젤] [izel]  20FW FAUX 무스탕',
        45000,
        45000,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '94',
    '1872272530'
    )
INSERT INTO items VALUES ('1927941264',
        '2만원 인하 에셀리아 20FW 윈터수트',
        69000,
        69000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '95',
    '1927941264'
    )
INSERT INTO items VALUES ('1126294117',
        '[샐리]새해맞이 겨울완벽혜택가 패딩/니트/융기모 外',
        66000,
        19900,
        69,
        '(주)컨트롤케이앤제이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '96',
    '1126294117'
    )
INSERT INTO items VALUES ('1933658954',
        '[여성] DOTTI 도티 No Stress 스트레치 기모 팬츠 4종 ',
        39900,
        36800,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '97',
    '1933658954'
    )

INSERT INTO items VALUES ('1946488351',
        '[블랙 2종이나   단 28 900원  ] 스넬리 국민 기모 레깅스 5종',
        29900,
        27600,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '98',
    '1946488351'
    )
INSERT INTO items VALUES ('1916141877',
        '앱20%적립+10만원인하 타하리20FW이태리소재 울혼방 헤링본코트',
        79000,
        79000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '99',
    '1916141877'
    )
INSERT INTO items VALUES ('1917123461',
        '[SOUP](신세계경기점)더블 버튼 핸드메이드 코트 SWBHC83',
        99000,
        70540,
        28,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 여성의류',
    '100',
    '1917123461'
    )
패션의류 브랜드 남성의류
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '1',
    '1985585454'
    )
INSERT INTO items VALUES ('1335600461',
        '[휴아이지옴므]울트라스판 기모슬랙스 HUIZ_SL576',
        18800,
        18800,
        0,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '2',
    '1335600461'
    )
INSERT INTO items VALUES ('1899400375',
        '[헤지스]헤지스 카라티/티셔츠/긴팔티/니트/맨투맨/셔츠 +20%',
        236100,
        70850,
        69,
        'LF몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '3',
    '1899400375'
    )
INSERT INTO items VALUES ('1999576564',
        '[제스](현대백화점)[제스] F/W 캐주얼 웰론 초경량 패딩조끼 X9LBL9901',
        9900,
        8620,
        12,
        '현대백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '4',
    '1999576564'
    )
INSERT INTO items VALUES ('1998234203',
        '[지이크](신세계강남점)F/W 프리미엄 [덕다운/구스다운] 점퍼 4종 택1 [PYD6561 6503 6504 6505]',
        129000,
        104170,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '5',
    '1998234203'
    )
INSERT INTO items VALUES ('1137995278',
        '[마운틴벨리][1+1] [라스트행사] 남자 여자 겨울 기모 베이직 팬츠/ 마운틴 벨리',
        23200,
        19260,
        16,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '6',
    '1137995278'
    )
INSERT INTO items VALUES ('1999241445',
        '[라코스테]남성 빅크록 라운드 티셔츠 LCST TH9579-20B58V',
        53400,
        48060,
        10,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '7',
    '1999241445'
    )
INSERT INTO items VALUES ('1295698550',
        '[지이크](22%) 지이크 한파대비 패딩/코트/니트/정장외~91%',
        208300,
        62500,
        69,
        '(주)신원')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '8',
    '1295698550'
    )
INSERT INTO items VALUES ('1947767192',
        '[올젠](신세계경기점)[올젠] 20FW 뉴테라에어 구스다운 브이넥 베스트 10종 택1 (ZOA4VP1303)',
        30000,
        24230,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '9',
    '1947767192'
    )
INSERT INTO items VALUES ('1976662561',
        '[올젠](올젠)융 본딩으로 따뜻하게 입을수 있는 반짚업 스웨터 ZOA4EU1315',
        51000,
        40800,
        20,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '10',
    '1976662561'
    )
INSERT INTO items VALUES ('1605140067',
        '[by파크랜드]by파크랜드_겨울 BEST 최종가 아우터/니트/정장 외',
        199300,
        59800,
        69,
        'by(주)파크랜드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '11',
    '1605140067'
    )
INSERT INTO items VALUES ('1991904789',
        '베이직 기모 맨투맨 5컬러 택1 (CB)/ 타미힐피거',
        33900,
        32890,
        2,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '12',
    '1991904789'
    )
INSERT INTO items VALUES ('1867664152',
        '[라코스테라이브]남성 라운드 맨투맨 SH940E-20C_CCA',
        111300,
        94610,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '13',
    '1867664152'
    )
INSERT INTO items VALUES ('1924803930',
        '[바쏘옴므]바쏘옴므 신상 티셔츠/스웨터/팬츠 외 BEST특집전',
        250000,
        75000,
        70,
        'sgbasso')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '14',
    '1924803930'
    )
INSERT INTO items VALUES ('2000253643',
        '[테이트][테이트] 남성 인생슬랙스 5종 (KAAW9-MPL010 020 030 040 050)',
        39950,
        27580,
        30,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '15',
    '2000253643'
    )
INSERT INTO items VALUES ('1958069460',
        '[올젠](광주신세계)[올젠] FW 기모소재 스판팬츠 4종 택1 [ZOZ4PP1302]',
        35000,
        28270,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '16',
    '1958069460'
    )
INSERT INTO items VALUES ('1931600523',
        '타미힐피거 남녀공용 자수기모맨투맨 4종 택1',
        35800,
        35410,
        1,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '17',
    '1931600523'
    )
INSERT INTO items VALUES ('1486754865',
        '[by파크랜드]by파크랜드 겨울 추가 가격 인하 아우터/니트/정장 외',
        229600,
        68900,
        69,
        'by(주)파크랜드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '18',
    '1486754865'
    )
INSERT INTO items VALUES ('1933733496',
        'CERINI by PAT 남성 웜 기모 릴렉스 팬츠3종',
        59800,
        56810,
        5,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '19',
    '1933733496'
    )
INSERT INTO items VALUES ('1964013325',
        '[올젠](신세계강남점)아웃퀼팅 구스다운 코트 2종 택1 (ZOA4CP1302)',
        95000,
        76720,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '20',
    '1964013325'
    )
INSERT INTO items VALUES ('1950067100',
        '[잭필드]잭필드 2020 WINTER 남성 스웨터 본딩 레이어드 셔츠 3종 패키지',
        59800,
        58800,
        1,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '21',
    '1950067100'
    )
INSERT INTO items VALUES ('1317485430',
        '[by파크랜드]by파크랜드_겨울 최종 인하가 정장/아우터/니트 외',
        166000,
        49800,
        70,
        'by(주)파크랜드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '22',
    '1317485430'
    )
INSERT INTO items VALUES ('1991341799',
        '타운젠트 라미네이티드 구스다운 발마칸 코트',
        69000,
        69000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '23',
    '1991341799'
    )
INSERT INTO items VALUES ('1919626390',
        '[올젠](신세계마산점)[올젠] 20FW 가먼트 워싱 스탠다드핏 새틴 치노팬츠 3종 택1 (ZPA4PP1502)',
        35000,
        25820,
        26,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '24',
    '1919626390'
    )
INSERT INTO items VALUES ('1867662899',
        '[라코스테라이브]남성 라운드 맨투맨 SH940E-20C_166',
        111300,
        94610,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '25',
    '1867662899'
    )
INSERT INTO items VALUES ('1788869038',
        '[닥스](신세계김해점)2020 F/W 닥스 겨울신상품 기모 캐쥬얼셔츠 남방 15종택1',
        60000,
        43680,
        27,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '26',
    '1788869038'
    )

INSERT INTO items VALUES ('1889846879',
        '4만원 세일  남성용 푸마골프 골드구스 무봉제 구스',
        109900,
        109900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '27',
    '1889846879'
    )
INSERT INTO items VALUES ('1872582969',
        '[레노마옴므][레노마셔츠 ]하이퀼리티 50종 드레스셔츠',
        30000,
        23700,
        21,
        'AK플라자2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '28',
    '1872582969'
    )
INSERT INTO items VALUES ('1996601566',
        '[예작][대구백화점 II관] [예작]일반핏 긴소매 16종 택 1(YJ1SBR101 외)',
        33000,
        22110,
        33,
        '대구백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '29',
    '1996601566'
    )
INSERT INTO items VALUES ('1940757298',
        '체스터 바이 체스터베리 20FW 울 퀼팅자켓',
        59000,
        56050,
        5,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '30',
    '1940757298'
    )
INSERT INTO items VALUES ('1985392191',
        '[남성] DOTTI 도티 No Stress 스트레치 기모 팬츠 3종 ',
        39900,
        36800,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '31',
    '1985392191'
    )
INSERT INTO items VALUES ('1953762399',
        '[헤지스][헤지스] [HAZZYS_wh][19FW]WHTS9D021G2 그레이 컬러배색 면혼방 긴팔',
        76450,
        59640,
        21,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '32',
    '1953762399'
    )
INSERT INTO items VALUES ('1946488444',
        '2020 겨울 오지호의  V.CUT(브이컷) 파워 기모 올인원 남팬츠 3종',
        69900,
        64400,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '33',
    '1946488444'
    )
INSERT INTO items VALUES ('1928297764',
        '안감 기모 맨투맨 SH7613/ 라코스테',
        69000,
        69000,
        0,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '34',
    '1928297764'
    )
INSERT INTO items VALUES ('1867660691',
        '[라코스테라이브]남성 라운드 맨투맨 SH940E-20C_Z0W',
        111300,
        94610,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '35',
    '1867660691'
    )
INSERT INTO items VALUES ('1913495624',
        '[앤드지 바이 지오지아](신세계강남점)20FW 경량 하이넥 구스다운 코트 3종 택1 [BLA4CP1181]',
        99000,
        79950,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '36',
    '1913495624'
    )
INSERT INTO items VALUES ('1909832327',
        '[앤드지 바이 지오지아](신세계타임스퀘어점패션관)[앤드지] 20FW 캐시미어 블랜디드 베이직 터틀넥 5종 택1 [BLA4EU1082]',
        35000,
        28270,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '37',
    '1909832327'
    )
INSERT INTO items VALUES ('1910918760',
        '[닥스]닥스셔츠캐쥬얼기모남방7종(선물포장가능)',
        60000,
        50400,
        16,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '38',
    '1910918760'
    )
INSERT INTO items VALUES ('1892331477',
        '[라코스테]공용 베이직 크루넥 티셔츠 TH0123-20C_001',
        59500,
        50580,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '39',
    '1892331477'
    )
INSERT INTO items VALUES ('1874704137',
        '남)푸마골프 에이론텍스 스웨터 플렉스 4종 20FW',
        59000,
        59000,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '40',
    '1874704137'
    )
INSERT INTO items VALUES ('1280319791',
        '[by파크랜드]by파크랜드_겨울 최종 가격 인하 아우터/니트 외',
        166000,
        49800,
        70,
        'by(주)파크랜드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '41',
    '1280319791'
    )
INSERT INTO items VALUES ('1678818885',
        '[레노마](레노마(셔츠))20년 신상 인기드레스셔츠 일반핏 20종 0924',
        30000,
        23400,
        22,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '42',
    '1678818885'
    )
INSERT INTO items VALUES ('1992222829',
        '[폴햄]폴햄 20FW최신상 남녀공용 지코 푸퍼 덕패딩 점퍼',
        49900,
        49900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '43',
    '1992222829'
    )
INSERT INTO items VALUES ('1931582606',
        '[탑텐](현대Hmall)[탑텐] 남녀공용 경량 오리털 푸퍼 숏패딩 덕패딩 리얼라이트다운 MSA4JP3901A',
        40900,
        36900,
        9,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '44',
    '1931582606'
    )
INSERT INTO items VALUES ('1877206523',
        '[Komodo] 코모도 블랙 후드 아웃포켓구스다운 점퍼 9519408580',
        119000,
        97580,
        18,
        'HDC아이파크몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '45',
    '1877206523'
    )
INSERT INTO items VALUES ('1871680493',
        '[빈폴](현대Hmall)[빈폴] 20FW unisex 옥스포드 셔츠 5종 택1 (BC0764N01Q/BC0764N01M/BC0764N013/BC0764N02S/BC0764N023)',
        76300,
        57990,
        23,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '46',
    '1871680493'
    )
INSERT INTO items VALUES ('1918258065',
        '[범퍼]범퍼 남성 플리스 재킷 3종',
        59900,
        56910,
        4,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '47',
    '1918258065'
    )
INSERT INTO items VALUES ('1918992058',
        '[라코스테]공용 베이직 크루넥 티셔츠 TH0123-20C_031',
        59500,
        50580,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '48',
    '1918992058'
    )
INSERT INTO items VALUES ('1632202735',
        '임히어로 추천 니트/터틀/티셔츠/팬츠 등 실속템',
        48100,
        28900,
        39,
        '세정글로벌')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '49',
    '1632202735'
    )
INSERT INTO items VALUES ('1942684036',
        '[빈폴맨]빈폴멘 20FW 시즌오프 니트/티셔츠/가디건 30%+20%',
        208800,
        125300,
        39,
        '삼성물산빈폴')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '50',
    '1942684036'
    )
INSERT INTO items VALUES ('1896445570',
        '[헤지스][헤지스] [HAZZYS_wh][19FW]WHTS9D021BK 블랙 컬러블록 면혼방 긴팔티',
        76450,
        59640,
        21,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '51',
    '1896445570'
    )
INSERT INTO items VALUES ('1964119985',
        '체스터 바이 체스터베리 20W 본딩팬츠3종',
        39900,
        37910,
        4,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '52',
    '1964119985'
    )
INSERT INTO items VALUES ('2002163387',
        '[코모도스퀘어] W몰 [LOVE] 20FW 헤비게이지 러브 자수 짜임 니트 3col/ 9530417723   9530417721  9560417722 (5284061602)',
        67600,
        60840,
        10,
        'fashionplus')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '53',
    '2002163387'
    )
INSERT INTO items VALUES ('1776513437',
        '[레노마셔츠]갤러리아  (레노마 베스트/선물포장 가능) 20년 FW 긴소매 슬림핏 13종 RKFSL410',
        35000,
        25900,
        26,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '54',
    '1776513437'
    )

INSERT INTO items VALUES ('1999601382',
        '올젠 HY 울혼방 기모바지 3종 1택 ZOZ4PP1303',
        29000,
        29000,
        0,
        '현대아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '55',
    '1999601382'
    )
INSERT INTO items VALUES ('1985398484',
        '[올젠]갤러리아  남자 겨울 기모 본딩 스판 팬츠 청바지 ZOA4DP1305',
        49000,
        38220,
        22,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '56',
    '1985398484'
    )
INSERT INTO items VALUES ('1807969766',
        '[바쏘]백화점 퀄리티 프리미엄 바쏘 캐시미어 특가전',
        330000,
        99000,
        70,
        'sgbasso')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '57',
    '1807969766'
    )
INSERT INTO items VALUES ('1978114246',
        '[올젠]갤러리아   올젠 20년 겨울신상 남방 7종 ZOA4WC1302/1303',
        39000,
        29250,
        25,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '58',
    '1978114246'
    )
INSERT INTO items VALUES ('1961814807',
        '[잭필드][20년 최신상]잭필드 패딩 팬츠 3종',
        69800,
        64300,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '59',
    '1961814807'
    )
INSERT INTO items VALUES ('1919707444',
        '[레노마셔츠]갤러리아  20년 F/W겨울신상품 긴소매기모셔츠 베스트16종 (일반 슬림)RKWSG0-1',
        40000,
        29600,
        26,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '60',
    '1919707444'
    )
INSERT INTO items VALUES ('1877163511',
        '[Komodo] 코모도 실버폭스 프리미엄구스다운 점퍼 9519408056',
        179000,
        146780,
        18,
        'HDC아이파크몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '61',
    '1877163511'
    )
INSERT INTO items VALUES ('1925150693',
        '남녀공용 겨울기모 맨투맨티셔츠 4종 (08578A1575)',
        36800,
        35330,
        3,
        'fashionplus')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '62',
    '1925150693'
    )
INSERT INTO items VALUES ('1940771955',
        '체스터 바이 체스터베리 20FW 울 퀼팅자켓',
        59000,
        59000,
        0,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '63',
    '1940771955'
    )
INSERT INTO items VALUES ('1978214395',
        '[올젠]남성용 캐시미어 터틀넥 니트 3종 택1  ZOA4EU1316',
        51000,
        39270,
        23,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '64',
    '1978214395'
    )
INSERT INTO items VALUES ('1975678021',
        '올젠 시보리넥 구스다운 경량 베스트 ZOA4VP1302',
        37000,
        33670,
        9,
        '엔터식스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '65',
    '1975678021'
    )
INSERT INTO items VALUES ('1957000381',
        '[세르지오][모다아울렛]모다행담도점 오리털 패딩 허리밴딩 스판바지 3종 J4916',
        59000,
        54870,
        7,
        'MODA아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '66',
    '1957000381'
    )
INSERT INTO items VALUES ('1927071820',
        '[잭필드]잭필드 2020 WINTER 남성 보아퍼 니트패키지 3종',
        59800,
        59800,
        0,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '67',
    '1927071820'
    )
INSERT INTO items VALUES ('1914570687',
        '[범퍼]범퍼 남성 플리스 재킷 3종',
        59900,
        56910,
        4,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '68',
    '1914570687'
    )
INSERT INTO items VALUES ('1932886713',
        '[휴아이지옴므]HU 히든밴딩 따슨 기모슬랙스_SL709',
        19800,
        19800,
        0,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '69',
    '1932886713'
    )
INSERT INTO items VALUES ('1992561896',
        '[앤드지 바이 지오지아](신세계의정부점)[ANDZ] 20FW 베이직 기본 긴팔티 6종 택1 (BZA4TR1102)',
        20000,
        17100,
        14,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '70',
    '1992561896'
    )
INSERT INTO items VALUES ('1933649608',
        '[레노마][레노마(남성)] F/W 가을 겨울 데일리 슬랙스 정장바지 6종택1 RJSP00A MS54',
        39000,
        31980,
        18,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '71',
    '1933649608'
    )
INSERT INTO items VALUES ('1939639290',
        '[킨록]F/W 폭스울 브이넥 풀오버 니트 RAY326 bk3453',
        49000,
        37730,
        23,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '72',
    '1939639290'
    )
INSERT INTO items VALUES ('1837958218',
        '[예작]갤러리아  예작 긴소매 남방셔츠 17종 택 1    YJ0FBS915WH외16종',
        33000,
        24420,
        26,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '73',
    '1837958218'
    )
INSERT INTO items VALUES ('1234054688',
        '[레노마옴므][레노마_셔츠(남성)] 2020 롯데본점 NEW  긴소매 유니크한 남방셔츠33가지',
        35000,
        23800,
        32,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '74',
    '1234054688'
    )
INSERT INTO items VALUES ('1658917139',
        '[예작][예작셔츠] 남성 슬림핏 와이셔츠 29종 택1',
        33000,
        26070,
        21,
        'AK플라자2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '75',
    '1658917139'
    )
INSERT INTO items VALUES ('1399522115',
        '[닥스][닥스] 감사품증정)신사의품격레귤러핏 PREMIUM 기모 봄 남방 DGW2SHCL128-G',
        60000,
        60000,
        0,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '76',
    '1399522115'
    )
INSERT INTO items VALUES ('1908064336',
        '[에디션앤드지]몽골피에 프리미엄 구스다운90:10 초경량 브이넥 패딩베스트 6칼라 NEA4VP1891',
        30000,
        23400,
        22,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '77',
    '1908064336'
    )
INSERT INTO items VALUES ('1985210857',
        '타미힐피거남녀공용기모맨투맨6종택1 (20201222)',
        29900,
        29900,
        0,
        'fashionplus')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '78',
    '1985210857'
    )
INSERT INTO items VALUES ('1928682340',
        '타미힐피거 남녀공용 자수기모후드티 4종 택1 (202010301)',
        45800,
        45800,
        0,
        'fashionplus')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '79',
    '1928682340'
    )
INSERT INTO items VALUES ('1931600456',
        '타미힐피거 남녀공용 자수기모후드티 4종 택1',
        45800,
        45300,
        1,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '80',
    '1931600456'
    )
INSERT INTO items VALUES ('1867669937',
        '[라코스테라이브]남성 라운드 맨투맨 SH940E-20C_HBM',
        111300,
        94610,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '81',
    '1867669937'
    )
INSERT INTO items VALUES ('1970851297',
        '[인디안] 겨울 기모/본딩팬츠 균일가 26 800원',
        26800,
        26800,
        0,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '82',
    '1970851297'
    )
INSERT INTO items VALUES ('1895893424',
        '(현대백화점)킨록by 20F/W  캐시미어피니싱 프리미엄 터틀넥니트 7종[EAY0915md2951]',
        39000,
        32370,
        17,
        '현대백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '83',
    '1895893424'
    )

INSERT INTO items VALUES ('1677151365',
        '[란체티](신세계경기점)F/W  베이직 비즈니스 셔츠 (일반핏/슬림핏) 25종 택 1',
        13500,
        11340,
        16,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '84',
    '1677151365'
    )
INSERT INTO items VALUES ('1890491685',
        '[앤드지 바이 지오지아][앤드지] ANDZ BY ZIOZIA 20F/W 캐주얼 체크 셋업 슈트[BZA3KG1151',
        159000,
        116070,
        27,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '85',
    '1890491685'
    )
INSERT INTO items VALUES ('1867117018',
        '[라코스테라이브]남성 빅크록 맨투맨 SH963E-20C_031',
        118300,
        100560,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '86',
    '1867117018'
    )
INSERT INTO items VALUES ('1980671769',
        '[지이크](여주점)[여주점][지이크] 브라운 체크 핸드메이트 후드 코트 PAHA7021',
        119000,
        107100,
        10,
        '신세계프리미엄아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '87',
    '1980671769'
    )
INSERT INTO items VALUES ('1975520551',
        '[예작]예작셔츠 F/W 드레스셔츠 특집전 슬림핏 20종 (YJ0FBS96123WH)',
        22500,
        20700,
        8,
        '마리오몰_')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '88',
    '1975520551'
    )
INSERT INTO items VALUES ('1985403891',
        '[코모도스퀘어][코모도스퀘어]3-WAY 다운코트',
        159000,
        146300,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '89',
    '1985403891'
    )
INSERT INTO items VALUES ('1878715619',
        '[잭필드]잭필드 겨울 남성 숨쉬는 바지 3종',
        59800,
        52820,
        11,
        '쇼핑엔티')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '90',
    '1878715619'
    )
INSERT INTO items VALUES ('1928420785',
        '[폴햄]남성용_캐시미어 블랜디드 스웨터(PHA4EU1010)',
        19900,
        15530,
        21,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '91',
    '1928420785'
    )
INSERT INTO items VALUES ('1932016215',
        '[워모(LUOMO)] 워모 프리미엄라벨 20FW 울 캐시미어 혼방  패딩 자켓',
        118000,
        118000,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '92',
    '1932016215'
    )
INSERT INTO items VALUES ('1893176091',
        '[라코스테]라코스테 기모 안감 맨투맨 SH7613 3종 택1',
        69000,
        67620,
        2,
        'AKmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '93',
    '1893176091'
    )
INSERT INTO items VALUES ('1870657610',
        '[예작]갤러리아  예작(슬림핏)카라스냅 솔리드 스트레치 긴팔셔츠 YJ0FBP589WH/BL/BK',
        55000,
        40700,
        26,
        '갤러리아백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '94',
    '1870657610'
    )
INSERT INTO items VALUES ('1969228892',
        '[케이투][케이투] 남녀 고어텍스 야상형 롱다운 고스트롱 KMW19565',
        263000,
        241960,
        8,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '95',
    '1969228892'
    )
INSERT INTO items VALUES ('1892332809',
        '[라코스테]공용 베이직 크루넥 티셔츠 TH0123-20C_166',
        59500,
        50580,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '96',
    '1892332809'
    )
INSERT INTO items VALUES ('1960723310',
        '[앤드지 바이 지오지아](신세계경기점)20F/W 실버폭스퍼 다운점퍼 4종 택1 (BZA4FP1103 )',
        139000,
        122320,
        12,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '97',
    '1960723310'
    )
INSERT INTO items VALUES ('1205469646',
        '[레노마옴므][레노마셔츠] 2020 신상 드레스셔츠 특집전',
        35000,
        27300,
        22,
        'AK플라자1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '98',
    '1205469646'
    )
INSERT INTO items VALUES ('1922468435',
        '[리얼지오지아][지오지아] AAZ4KG1602 프리미엄 캐주얼 자켓 3종 택1',
        60030,
        60030,
        0,
        'GlobalHmall2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '99',
    '1922468435'
    )
INSERT INTO items VALUES ('1471095616',
        '[마운틴벨리][무료배송 / 3장세트] 겨울 남자 기모 본딩 데일리 베이직 팬츠/ 마운틴 벨리',
        34500,
        28640,
        16,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 남성의류',
    '100',
    '1471095616'
    )
패션의류 브랜드 진/캐쥬얼
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '1',
    '1789464964'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '2',
    '2000376043'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '3',
    '1913148836'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '4',
    '1895164110'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '5',
    '1760154947'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '6',
    '1693435807'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '7',
    '1663724654'
    )
INSERT INTO items VALUES ('1888687070',
        '[테이트]테이트 남여 티셔츠/니트/팬츠_TTMWTPBT0115',
        66300,
        19900,
        69,
        '테 이 트')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '8',
    '1888687070'
    )
INSERT INTO items VALUES ('1675108009',
        '[지오다노][지오다노]  파격혜택  379907 여 초경량 퀼팅 숏자켓',
        22000,
        19800,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '9',
    '1675108009'
    )
INSERT INTO items VALUES ('1994714291',
        '[모다아울렛][타미힐피거] 맨투맨/니트/터틀넥  外 겨울베스트 특가전',
        29900,
        29900,
        0,
        'MODA아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '10',
    '1994714291'
    )
INSERT INTO items VALUES ('1904148907',
        '[폴햄]폴햄 패딩/점퍼 외 아우터 모음_PHOTET0112',
        166000,
        49900,
        69,
        'POLHAM_MALL')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '11',
    '1904148907'
    )
INSERT INTO items VALUES ('1914158208',
        '[지오다노][지오다노]  특별혜택  020920 브러시드 클래식 맨투맨',
        18000,
        16200,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '12',
    '1914158208'
    )
INSERT INTO items VALUES ('2002012509',
        '카카오프렌즈 남여공용 기모 맨투맨 후드티 세트',
        39000,
        38000,
        2,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '13',
    '2002012509'
    )
INSERT INTO items VALUES ('1983993163',
        '어썸핏 여성 벨벳 코듀로이 릴렉스 팬츠 3종',
        49900,
        45410,
        8,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '14',
    '1983993163'
    )
INSERT INTO items VALUES ('2005904819',
        '[흄(HUM)] 흄 남성 컬러 트렌치 다운 코트 1종',
        49900,
        49900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '15',
    '2005904819'
    )

INSERT INTO items VALUES ('678530627',
        '[칼카니]마블 칼카니 성인/아동 기모맨투맨 후드티 팬츠99종',
        36300,
        10900,
        69,
        'KARLKANI')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '16',
    '678530627'
    )
INSERT INTO items VALUES ('1895169358',
        '[에비수]에비수 브랜드 기모/맨투맨/후드티/다운/점퍼/데님',
        66300,
        19900,
        69,
        '에비수샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '17',
    '1895169358'
    )
INSERT INTO items VALUES ('1652387921',
        '[니]NII 겨울인기아이템 맨투맨외 50종+최대22%추가할인',
        25000,
        7500,
        70,
        'NII크리스크리스티')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '18',
    '1652387921'
    )
INSERT INTO items VALUES ('1674006850',
        '[캘빈클라인]CK 아울렛 특가전 후드/맨투맨/패딩/데님 1만원대~',
        165000,
        49500,
        70,
        'ckmall1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '19',
    '1674006850'
    )
INSERT INTO items VALUES ('1994558896',
        '[디키즈]Dickies[DHP4UTFJ154]디키즈 남녀공용 솔리드 빅포켓 다운 필 롱패딩',
        25230,
        25230,
        0,
        'GlobalHmall2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '20',
    '1994558896'
    )
INSERT INTO items VALUES ('1986559269',
        '[폴햄]남여 덤블 보아 후드집업 점퍼 4종택1 (PHA4TC3910외3종)',
        30000,
        25200,
        16,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '21',
    '1986559269'
    )
INSERT INTO items VALUES ('1161403967',
        '[뱅뱅]12%쿠폰 구스/덕다운/기모팬츠 겨울시즌오프 최대 92%',
        86300,
        25900,
        69,
        '웹뜰공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '22',
    '1161403967'
    )
INSERT INTO items VALUES ('1116129648',
        '[지오다노][지오다노] 243801 코튼 져지 크루넥 3pcs 패키지',
        19800,
        17820,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '23',
    '1116129648'
    )
INSERT INTO items VALUES ('2005904818',
        '[흄(HUM)] 흄 여성 컬러 트렌치 다운 코트 1종',
        49900,
        49900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '24',
    '2005904818'
    )
INSERT INTO items VALUES ('1992612605',
        '[지지피엑스][지지피엑스] GGPX  아우터 12종 택1 특별가 (GKDBCT421F GKDBCT923',
        139000,
        129270,
        7,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '25',
    '1992612605'
    )
INSERT INTO items VALUES ('1932959543',
        '[타미힐피거][타미힐피거] 남녀공용 자수기모맨투맨 4종 택1',
        35800,
        35800,
        0,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '26',
    '1932959543'
    )
INSERT INTO items VALUES ('1927026222',
        '[뱅뱅]뱅뱅 남성 이중직 기모 데님 3종',
        88000,
        80840,
        8,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '27',
    '1927026222'
    )
INSERT INTO items VALUES ('1984000148',
        '어썸핏 남성 벨벳 코듀로이 릴렉스 팬츠 2종',
        49900,
        45410,
        8,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '28',
    '1984000148'
    )
INSERT INTO items VALUES ('1267464808',
        '[게스]25%중복 GUESS 겨울 세일전+신규아이템 오픈',
        130000,
        39000,
        70,
        'GUESSKOREAMALL')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '29',
    '1267464808'
    )
INSERT INTO items VALUES ('1647202240',
        '[니]NII 겨울 아우터외50종 시즌오프+최대추가22%할인',
        65000,
        19500,
        70,
        'NII크리스크리스티')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '30',
    '1647202240'
    )
INSERT INTO items VALUES ('1984746529',
        '타미힐피거 스몰로고 양면기모 맨투맨 8컬러 택1 (UO) (UO002)',
        29900,
        29900,
        0,
        'fashionplus')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '31',
    '1984746529'
    )
INSERT INTO items VALUES ('2005090315',
        '[트루젠]3계절 출퇴근 및 캐주얼 룩 퀼팅 패딩 코트 다크카키0010',
        90000,
        90000,
        0,
        'NC_백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '32',
    '2005090315'
    )
INSERT INTO items VALUES ('1999126223',
        '[뱅뱅]뱅뱅 남성 히트 웜 본딩 데님 3종',
        79000,
        72470,
        8,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '33',
    '1999126223'
    )
INSERT INTO items VALUES ('1992787592',
        '[앤드지 바이 지오지아][앤드지] 20F/W 세미루즈핏 싱글코트 7종택1 BZA4CG1102',
        125000,
        88750,
        29,
        '롯데백화점2관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '34',
    '1992787592'
    )
INSERT INTO items VALUES ('1912088006',
        '[지오다노][지오다노] 410924 여 브러시드 테리 조거 팬츠',
        29800,
        26820,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '35',
    '1912088006'
    )
INSERT INTO items VALUES ('1687516789',
        '[지오다노][지오다노]  한정특가  329915 여 목넥 플리스 집업',
        19000,
        17100,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '36',
    '1687516789'
    )
INSERT INTO items VALUES ('1945736448',
        '커플추천 겨울 기모 맨투맨 (jqint2)',
        36900,
        35430,
        3,
        'fashionplus')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '37',
    '1945736448'
    )
INSERT INTO items VALUES ('1917857271',
        '[잠뱅이]잠뱅이 겨울SALE 최대12%할인/아우터/기모데님/맨투맨',
        66300,
        19900,
        69,
        '힐크릭 공식몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '38',
    '1917857271'
    )
INSERT INTO items VALUES ('1725548978',
        '[리바이스]리바이스 패딩/플리스/청자켓/데님팬츠/맨투맨티셔츠',
        173000,
        53000,
        69,
        '리바이스 코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '39',
    '1725548978'
    )
INSERT INTO items VALUES ('1970288604',
        '아리스토우 남성 씬클라우드 패딩점퍼 베스트 2종 세',
        39900,
        36110,
        9,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '40',
    '1970288604'
    )
INSERT INTO items VALUES ('2000929620',
        '(프로젝트M(PROJECT M)) (광주신세계)프로젝트엠 기본 드레스 셔츠 6종 택1 (EPA5WC1901 EPA5WC1902 EPA...',
        12000,
        8850,
        26,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '41',
    '2000929620'
    )
INSERT INTO items VALUES ('1920643631',
        '(남성)탑텐(TOP10) 온에어 웜티 6종',
        27900,
        25700,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '42',
    '1920643631'
    )
INSERT INTO items VALUES ('1925227893',
        '[지오다노]남 스포츠 후드 롱 다운 078921',
        63000,
        56700,
        10,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '43',
    '1925227893'
    )

INSERT INTO items VALUES ('1913787840',
        '[지오다노][지오다노] 320930 여 브러쉬드 테리 크루넥 풀오버 (솔리드)',
        19000,
        17100,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '44',
    '1913787840'
    )
INSERT INTO items VALUES ('1914597355',
        '[흄]유니 리버시블 후리스 롱점퍼 FHNWCUH764',
        38000,
        30400,
        20,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '45',
    '1914597355'
    )
INSERT INTO items VALUES ('1917954286',
        '[지오다노]지오다노 020920 브러시드 클래식 맨투맨',
        18000,
        18000,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '46',
    '1917954286'
    )
INSERT INTO items VALUES ('1923771894',
        '[클라이드앤]클라이드앤 중복쿠폰22% 코트/점퍼/플리스외',
        130000,
        39000,
        70,
        '클라이드앤')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '47',
    '1923771894'
    )
INSERT INTO items VALUES ('1920643676',
        '(여성)탑텐(TOP10) 온에어 웜티 6종',
        27900,
        25700,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '48',
    '1920643676'
    )
INSERT INTO items VALUES ('1994672181',
        '[도티] [DOTTI] 여성 벨벳 코듀로이 릴랙스 팬츠 3종',
        49900,
        49900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '49',
    '1994672181'
    )
INSERT INTO items VALUES ('1882656595',
        '[지오다노]남 테이퍼드 링클프리 팬츠 110501',
        27000,
        24300,
        10,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '50',
    '1882656595'
    )
INSERT INTO items VALUES ('1687798612',
        '[지오다노]지오다노 079920 숏 푸파 다운',
        94000,
        94000,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '51',
    '1687798612'
    )
INSERT INTO items VALUES ('1867632468',
        '게스 20FW 미니 삼각 맨투맨 NK3K0141',
        30000,
        22800,
        24,
        '엔터식스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '52',
    '1867632468'
    )
INSERT INTO items VALUES ('1721030712',
        '[디키즈](광주신세계)디키즈 남여공용 TRANSFORMABLE 다운 자켓 (DHQ4UTDJ177)',
        69000,
        58650,
        15,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '53',
    '1721030712'
    )
INSERT INTO items VALUES ('1884527479',
        '[게스]여성 M톤 NEW 스트레이트 OK3D9600외 6종 택1',
        40000,
        30400,
        24,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '54',
    '1884527479'
    )
INSERT INTO items VALUES ('1800098983',
        '[흄]흄 여성 U넥 덕다운 경량 베스트 FHOWCVE541',
        16900,
        13190,
        21,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '55',
    '1800098983'
    )
INSERT INTO items VALUES ('1938085576',
        '[올젠]경량 리버시블 구스다운 점퍼 ZOB1JP1303',
        69000,
        52440,
        24,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '56',
    '1938085576'
    )
INSERT INTO items VALUES ('1864338156',
        '[모그]런칭가69 900원 모그 20F/W 리오셀 블라우스 4종',
        39900,
        39900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '57',
    '1864338156'
    )
INSERT INTO items VALUES ('1675193831',
        '지오다노 379907 여 초경량 퀼팅 숏 다운',
        22000,
        19800,
        10,
        'CJmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '58',
    '1675193831'
    )
INSERT INTO items VALUES ('1872402986',
        '[디키즈](신세계의정부점)디키즈남녀공용 STANDARD FIT-BIG COLEAGE SWEATSHIRT 빅로고 기모 맨투맨 (DMR3UTMT523)',
        28000,
        20650,
        26,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '59',
    '1872402986'
    )
INSERT INTO items VALUES ('1942751693',
        '폴로 북극곰 융털 후리스 집업 자켓 남여공용자체발열',
        20000,
        19800,
        1,
        '가오간지')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '60',
    '1942751693'
    )
INSERT INTO items VALUES ('1687834702',
        '[지오다노]지오다노 029918 플리스 집업 가디건 양털플리스',
        25000,
        25000,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '61',
    '1687834702'
    )
INSERT INTO items VALUES ('2001220629',
        '[지오다노]지오다노 371503 어니언 퀄팅 하프 다운자켓',
        89800,
        89800,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '62',
    '2001220629'
    )
INSERT INTO items VALUES ('1945766638',
        '(크루비) [단독할인][CARHARTT] 칼하트 포켓맨투맨 103852 (3컬러)',
        49900,
        49900,
        0,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '63',
    '1945766638'
    )
INSERT INTO items VALUES ('1188568285',
        '겨울인기템 연말특가 맨투맨 후드 패딩 다운 9300원~',
        18500,
        18500,
        0,
        'Fashion_Outlet')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '64',
    '1188568285'
    )
INSERT INTO items VALUES ('1991412670',
        'C2 남성 윈터 기모 레이저 데님 3종 초특가',
        49000,
        44570,
        9,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '65',
    '1991412670'
    )
INSERT INTO items VALUES ('1920528727',
        '[지오다노][지오다노] 110945 브러시드 슬림 데님',
        25000,
        22500,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '66',
    '1920528727'
    )
INSERT INTO items VALUES ('2005090196',
        '[트루젠]3계절 출퇴근 및 캐주얼 룩 퀼팅 패딩 코트 다크 네이비0020',
        90000,
        90000,
        0,
        'NC_백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '67',
    '2005090196'
    )
INSERT INTO items VALUES ('1678403975',
        '[지오다노][지오다노] 059920 터틀넥 풀오버 (12GG)',
        25000,
        22500,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '68',
    '1678403975'
    )
INSERT INTO items VALUES ('1955562969',
        '[클라이드앤](신세계김해점)[클라이드]남여 롱패딩/구스다운 3종(FJDDU456U/FJDDU951F/FJDDU952F)',
        40000,
        31200,
        22,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '69',
    '1955562969'
    )
INSERT INTO items VALUES ('1892972997',
        '[지오다노]여 초경량 웨이브퀼팅 자켓 370907',
        62800,
        56520,
        10,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '70',
    '1892972997'
    )
INSERT INTO items VALUES ('1994548661',
        '[디키즈](현대백화점)Dickies[DHP4UTFJ154]디키즈 남녀공용 솔리드 빅포켓 다운 필 롱패딩',
        29000,
        25230,
        13,
        '현대백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '71',
    '1994548661'
    )
INSERT INTO items VALUES ('1893262244',
        '[지오다노]지오다노 110951 트레이닝 조거팬츠 (김영광착장)',
        29800,
        29800,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '72',
    '1893262244'
    )

INSERT INTO items VALUES ('1927459898',
        '[컨셉원](신세계의정부점)[컨셉원] 겨울용 브러시드 테이퍼드핏 슬랙스 10110908/110908',
        35000,
        29750,
        15,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '73',
    '1927459898'
    )
INSERT INTO items VALUES ('1682850115',
        '[지오다노]지오다노 119915 브러시드 테이퍼드 슬랙스',
        20000,
        20000,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '74',
    '1682850115'
    )
INSERT INTO items VALUES ('1975925545',
        '[폴햄키즈]에어 구스 롱다운 점퍼 (G90/10)PKA4JP1030MSS',
        99000,
        76230,
        23,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '75',
    '1975925545'
    )
INSERT INTO items VALUES ('1970290480',
        '아리스토우 여성 씬클라우드 패딩점퍼 베스트 2종 세',
        39900,
        36110,
        9,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '76',
    '1970290480'
    )
INSERT INTO items VALUES ('2001834576',
        '[네파키즈]프리미아구스다운자켓 KG82008',
        148000,
        112480,
        24,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '77',
    '2001834576'
    )
INSERT INTO items VALUES ('1979907151',
        '[디스커버리]남성여성 반슬리 다운 롱패딩 DMDJ65061DWDJ66061',
        230300,
        230300,
        0,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '78',
    '1979907151'
    )
INSERT INTO items VALUES ('1794605911',
        '[흄]HUM 여성 다운 경량베스트 FHOWCVE541',
        16900,
        13020,
        22,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '79',
    '1794605911'
    )
INSERT INTO items VALUES ('1989989666',
        '[올젠]클래식 뉴테라 후드사파리점퍼 3종 택 1 ZOA4FP1309',
        197000,
        149720,
        24,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '80',
    '1989989666'
    )
INSERT INTO items VALUES ('1758803559',
        '폴햄 이너웨어 순면 100% 반팔티셔츠 4PACK PHA5TR3900K',
        19900,
        16320,
        17,
        '엔터식스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '81',
    '1758803559'
    )
INSERT INTO items VALUES ('1920780088',
        '[디키즈](현대백화점)Dickies[DSR3UTMT350]디키즈 남여공용 컬러 블록 기모 스웨트셔츠',
        25000,
        21750,
        13,
        '현대백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '82',
    '1920780088'
    )
INSERT INTO items VALUES ('1938108218',
        '[비버리힐스폴로클럽]비버리힐즈폴로클럽 매직 밴드 본딩 팬츠 3종',
        59800,
        54620,
        8,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '83',
    '1938108218'
    )
INSERT INTO items VALUES ('1794605788',
        '[뱅뱅]남녀공용초경량구스다운조끼(NEE624)',
        19900,
        15920,
        20,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '84',
    '1794605788'
    )
INSERT INTO items VALUES ('1907430552',
        '[써스데이아일랜드 ] [하프클럽/써스데이아일랜드]여성 솔리드 롱기장 다운 점퍼(T188MD',
        62250,
        58520,
        5,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '85',
    '1907430552'
    )
INSERT INTO items VALUES ('2004279963',
        'CK  남 J313836 1BY 블랙 스키니핏 스판 데님',
        26730,
        26730,
        0,
        'ckmall1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '86',
    '2004279963'
    )
INSERT INTO items VALUES ('1710738140',
        '[클라이드앤]여성 후드배색 롱다운 점퍼 (FIDDU809F)',
        30000,
        24000,
        20,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '87',
    '1710738140'
    )
INSERT INTO items VALUES ('1615651445',
        '[팬콧]팬콧 남녀 겨울신상 50종 택1',
        49900,
        49900,
        0,
        '팬콧공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '88',
    '1615651445'
    )
INSERT INTO items VALUES ('1932631427',
        '[파타고니아] p 6 로고 리스판서빌리 기모 후드티셔츠_P089284612',
        54800,
        54800,
        0,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '89',
    '1932631427'
    )
INSERT INTO items VALUES ('1687837056',
        '[지오다노]지오다노 329915 여 플리스 집업 가디건',
        19000,
        19000,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '90',
    '1687837056'
    )
INSERT INTO items VALUES ('1909777136',
        '[써스데이아일랜드 ] [하프클럽/써스데이아일랜드]여성 6골 코듀로이 와이드 팬츠(T188M',
        33910,
        31880,
        5,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '91',
    '1909777136'
    )
INSERT INTO items VALUES ('1942967387',
        '폴로 북극곰 융털 하이넥 후드 집업 1+1한정수량빅세일',
        40000,
        39900,
        0,
        '가오간지')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '92',
    '1942967387'
    )
INSERT INTO items VALUES ('1946956382',
        '[지오다노]지오다노 020933 브러시드 긴팔 면티',
        9000,
        9000,
        0,
        '지오다노-본사직영샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '93',
    '1946956382'
    )
INSERT INTO items VALUES ('1924944251',
        '[클라이드앤]클라이드앤 클리어런스 최대 81%off 패딩/코트/기모外',
        149000,
        49000,
        67,
        '클라이드앤')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '94',
    '1924944251'
    )
INSERT INTO items VALUES ('1963392790',
        '[폴햄](광주신세계)라운드넥/브이넥 구스 경량 베스트 4종 택1',
        19900,
        16080,
        19,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '95',
    '1963392790'
    )
INSERT INTO items VALUES ('1979403447',
        '체이스컬트 새해쇼핑 기모맨투맨/터틀넥니트/팬츠 외',
        43000,
        12900,
        70,
        '지에스지엠(주)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '96',
    '1979403447'
    )
INSERT INTO items VALUES ('1711705345',
        '[지오다노][지오다노]  특별혜택  079914 싱글 울 코트',
        39000,
        35100,
        10,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '97',
    '1711705345'
    )
INSERT INTO items VALUES ('1907430608',
        '[써스데이아일랜드 ] [하프클럽/써스데이아일랜드]여성 파자마 변형 원피스(T188MOP24',
        40390,
        37970,
        5,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '98',
    '1907430608'
    )
INSERT INTO items VALUES ('1802873515',
        '[디키즈]22%추가쿠폰_디키즈 아우터/플리스 마감 세일',
        133000,
        39900,
        70,
        '디키즈코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '99',
    '1802873515'
    )
INSERT INTO items VALUES ('1967917838',
        '[에프알제이][에프알제이] 유니 리버시블 숏기장 구스다운점퍼(F94U-MD01XA)',
        32900,
        32900,
        0,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '브랜드 진/캐쥬얼 ',
    '100',
    '1967917838'
    )
패션의류 여성의류

INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '1',
    '1986969051'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '2',
    '189842449'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '3',
    '1280233513'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '4',
    '1606293717'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '5',
    '1284344651'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '6',
    '810518655'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '7',
    '776582823'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '8',
    '1688200696'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '9',
    '1551794470'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '10',
    '1430266775'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '11',
    '576442682'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '12',
    '1108678685'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '13',
    '373058782'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '14',
    '1409488407'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '15',
    '1718416286'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '16',
    '753970658'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '17',
    '1817237042'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '18',
    '1481263644'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '19',
    '1309233372'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '20',
    '1615409666'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '21',
    '221969619'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '22',
    '1517719492'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '23',
    '1311171220'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '24',
    '1727198869'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '25',
    '197555399'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '26',
    '1373777190'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '27',
    '1517019865'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '28',
    '965313589'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '29',
    '1670609306'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '30',
    '215673140'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '31',
    '1487774180'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '32',
    '1975776752'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '33',
    '1917953479'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '34',
    '1162884079'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '35',
    '1975613741'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '36',
    '1566013256'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '37',
    '1725467202'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '38',
    '731274728'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '39',
    '628153284'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '40',
    '1677882956'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '41',
    '974668803'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '42',
    '1288386776'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '43',
    '1158276673'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '44',
    '1786992530'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '45',
    '1806509264'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '46',
    '1444224360'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '47',
    '777247382'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '48',
    '1934828459'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '49',
    '1879126178'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '50',
    '1725153067'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '51',
    '1873175246'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '52',
    '192173793'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '53',
    '1345149344'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '54',
    '1987470777'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '55',
    '1570637302'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '56',
    '744192338'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '57',
    '787245581'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '58',
    '1983920906'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '59',
    '1430261089'
    )
INSERT INTO items VALUES ('336411659',
        '요즘에/10%추가할인/융기모 청바지/슬랙스/면팬츠/3XL',
        32900,
        9900,
        69,
        '요즘에')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '60',
    '336411659'
    )

INSERT INTO items VALUES ('1835916262',
        '브리치x바이미쓰리 10% F/W 니트/맨투맨/아우터',
        47600,
        14300,
        69,
        'brich')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '61',
    '1835916262'
    )
INSERT INTO items VALUES ('1700695496',
        '브리치X씨샵인더룸 F/W 맨투맨/니트/팬츠/패딩',
        73000,
        21900,
        70,
        'brich')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '62',
    '1700695496'
    )
INSERT INTO items VALUES ('1879551119',
        '반반한샵 겨울패션/뽀글이집업/코트/자켓/니트',
        36300,
        10900,
        69,
        '반반한샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '63',
    '1879551119'
    )
INSERT INTO items VALUES ('1695778430',
        '[솔로이스트]22%쿠폰 겨울 그랜드 세일 최대 71%할인 UTCJ2H01',
        133000,
        39900,
        70,
        '솔로이스트-의류')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '64',
    '1695778430'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '65',
    '1116258684'
    )
INSERT INTO items VALUES ('1916639772',
        '론칭가179 000원 타하리 20FW 트렌치 구스다운 코트',
        79000,
        79000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '66',
    '1916639772'
    )
INSERT INTO items VALUES ('1956767142',
        '태그미 포근 기모 벨벳 코듀로이 팬츠 3종',
        69900,
        61220,
        12,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '67',
    '1956767142'
    )
INSERT INTO items VALUES ('502114157',
        '코코리겨울신상박스롱후드맨투맨',
        33000,
        9900,
        70,
        '코코리cocolee')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '68',
    '502114157'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '69',
    '1924647458'
    )
INSERT INTO items VALUES ('1513973750',
        '메이킹유 니트원피스/뽀글이/맨투맨/코트',
        33000,
        9900,
        70,
        '메이킹유')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '70',
    '1513973750'
    )
INSERT INTO items VALUES ('932044429',
        '로드블링 12% 신상/롱원피스/니트/맨투맨/빅사이즈',
        42900,
        12900,
        69,
        '로드블링')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '71',
    '932044429'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '72',
    '1693435171'
    )
INSERT INTO items VALUES ('860889295',
        '대박난박양 겨울원피스 롱니트원피스 투피스 니트',
        34900,
        34900,
        0,
        '대박난박양')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '73',
    '860889295'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '74',
    '1234579017'
    )
INSERT INTO items VALUES ('175144308',
        '[올시즌]기모팬츠특가/여자청바지/빅사이즈~3XL/여성데님',
        29000,
        8900,
        69,
        '올시즌.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '75',
    '175144308'
    )
INSERT INTO items VALUES ('1912631990',
        '[Humming 허밍by 현영] 롱 벨벳 플리츠 스커트 3종 / 주름치마 / 밴딩 스커트 ',
        39000,
        39000,
        0,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '76',
    '1912631990'
    )
INSERT INTO items VALUES ('779656750',
        '쏭스타일 신상추가.빅사이즈.롱티.루즈핏',
        33000,
        9900,
        70,
        'ssongstyle')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '77',
    '779656750'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '78',
    '1889123974'
    )
INSERT INTO items VALUES ('602009751',
        '빅사이즈여성티 후드티 겨울니트기모 롱티면티 맨투맨',
        20200,
        14900,
        26,
        '미르마루')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '79',
    '602009751'
    )
INSERT INTO items VALUES ('1345137474',
        '[팍티오]hello2021 사은품증정/할인전/융밴딩팬츠/패딩/무배',
        46300,
        13900,
        69,
        'factiomall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '80',
    '1345137474'
    )
INSERT INTO items VALUES ('125513674',
        '홀복/핑크별사탕/섹시홀복/미니원피스/파티복/클럽복',
        35900,
        34010,
        5,
        '핑크별사탕')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '81',
    '125513674'
    )
INSERT INTO items VALUES ('224669541',
        '제이피플/기모치마레깅스/빅사이즈/피치/융털밍크',
        19500,
        6900,
        64,
        '★제이피플★')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '82',
    '224669541'
    )
INSERT INTO items VALUES ('1686097835',
        '트레이닝바지 극세사 융털 수면바지 밍크 홈웨어 1+1',
        29600,
        8900,
        69,
        '내마우스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '83',
    '1686097835'
    )
INSERT INTO items VALUES ('750072105',
        '쏭스타일 신상추가 롱티/박스티/루즈핏/ 특가찬스~',
        33000,
        9900,
        70,
        'ssongstyle')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '84',
    '750072105'
    )
INSERT INTO items VALUES ('1923917533',
        '집안에만 있어도 놓칠수없는 스타일 홈 웨어 ~62%세일',
        110000,
        33000,
        70,
        'LAP공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '85',
    '1923917533'
    )
INSERT INTO items VALUES ('1965384641',
        '훼르자 기모레깅스6종',
        39900,
        36910,
        7,
        'K쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '86',
    '1965384641'
    )
INSERT INTO items VALUES ('232065619',
        '애프리콧 신상니트가디건~/여자/여성/울폴라/롱브이넥',
        33000,
        9900,
        70,
        '애프리콧')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '87',
    '232065619'
    )
INSERT INTO items VALUES ('165003300',
        '[지기젠]겨울 여자청바지/기모/일자/와이드/슬랙스/빅사이즈',
        33000,
        9900,
        70,
        '지기젠')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '88',
    '165003300'
    )
INSERT INTO items VALUES ('399815051',
        '달리샵 원피스/롱니트/기모/후드티/양털조끼',
        33000,
        9900,
        70,
        '달리샵1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '89',
    '399815051'
    )
INSERT INTO items VALUES ('1274265022',
        '요즘에/10%추가할인/융기모 면팬츠/슬랙스/청바지/3XL',
        32900,
        9900,
        69,
        '요즘에')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '90',
    '1274265022'
    )
INSERT INTO items VALUES ('1669385151',
        '오리털100% 경량패딩조끼 조끼패딩 경량조끼 빅사이즈',
        12900,
        12840,
        0,
        'JYCOMPANY_')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '91',
    '1669385151'
    )
INSERT INTO items VALUES ('202940857',
        '+겨울신상 트레이닝SET 빅사이즈/추리닝/조거/밴딩+',
        99500,
        29900,
        69,
        '갠소')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '92',
    '202940857'
    )
INSERT INTO items VALUES ('1737122108',
        '투피앤 겨울신상 니트 원피스 스커트 여름 블라우스롱',
        29400,
        19400,
        34,
        '투피앤')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '93',
    '1737122108'
    )

INSERT INTO items VALUES ('1989147538',
        ' 특가 [yunni.G] 유니지 웜업 플리스 풀코디 3종-여성',
        39000,
        35900,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '94',
    '1989147538'
    )
INSERT INTO items VALUES ('595619167',
        '제니트 루즈핏 가디건 니트 조끼 여성 코트 스웨터',
        43000,
        12900,
        70,
        'JENIT')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '95',
    '595619167'
    )
INSERT INTO items VALUES ('229991698',
        '[공구우먼]겨울 봄 신상 롱 원피스 모음 밴딩 빅사이즈 여성의류',
        33800,
        33470,
        0,
        '공구우먼.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '96',
    '229991698'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '97',
    '1916658645'
    )
INSERT INTO items VALUES ('183421338',
        'M1B 네모 겨울코디완성 날씬템 빅사이즈 스커트',
        20900,
        17900,
        14,
        '네모(Nemo)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '98',
    '183421338'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '99',
    '1256823118'
    )
INSERT INTO items VALUES ('1999193017',
        '마넬뉴욕 이중지 기모 하프코트 셋업 2종',
        39900,
        38900,
        2,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '여성의류',
    '100',
    '1999193017'
    )
패션의류 남성의류
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '1',
    '1495278850'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '2',
    '1322490033'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '3',
    '805459425'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '4',
    '1789464964'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '5',
    '1494979529'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '6',
    '2001008782'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '7',
    '929105077'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '8',
    '2000376043'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '9',
    '1913148836'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '10',
    '1895164110'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '11',
    '1760154947'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '12',
    '1503231163'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '13',
    '1823978020'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '14',
    '801815493'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '15',
    '1693435807'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '16',
    '169295221'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '17',
    '907967540'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '18',
    '1985585454'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '19',
    '1912374335'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '20',
    '1663724654'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '21',
    '1993510431'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '22',
    '898007895'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '23',
    '266575292'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '24',
    '528849355'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '25',
    '1498699891'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '26',
    '1888687070'
    )
INSERT INTO items VALUES ('856191474',
        '기모 맨투맨티셔츠오버핏 남성 남자 여성빅사이즈긴팔',
        33000,
        9900,
        70,
        '문컬렉션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '27',
    '856191474'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '28',
    '1335600461'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '29',
    '1675108009'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '30',
    '1899400375'
    )
INSERT INTO items VALUES ('1985685819',
        '[올젠]스탠드 카라 퍼 덕다운 코트 ZOA4CP1303',
        109000,
        83930,
        23,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '31',
    '1985685819'
    )
INSERT INTO items VALUES ('1644625234',
        '[인디안]남성 신사룩 추천~자켓/셔츠 외 인기상품 GET',
        132300,
        39700,
        69,
        '세정글로벌')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '32',
    '1644625234'
    )
INSERT INTO items VALUES ('1978004633',
        '[뱅뱅]남녀공용 구스다운 점퍼2종택GUE704.GUE705',
        30000,
        24300,
        19,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '33',
    '1978004633'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '34',
    '1994714291'
    )
INSERT INTO items VALUES ('621704616',
        '맨투맨/빅사이즈/기모/티셔츠/긴팔티/남자/남성/티',
        33000,
        9900,
        70,
        '버클리클')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '35',
    '621704616'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '36',
    '1999576564'
    )
INSERT INTO items VALUES ('1561046761',
        '[엠블러]20FW 신상 엠블러 오버핏 남녀 맨투맨/후드티/티셔츠',
        27900,
        26510,
        4,
        '엠블러코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '37',
    '1561046761'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '38',
    '1904148907'
    )
INSERT INTO items VALUES ('1492344533',
        '로드스타 남녀공용 가벼운 후리스자켓/패딩조끼/니트',
        36300,
        10900,
        69,
        '로드스타14')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '39',
    '1492344533'
    )
INSERT INTO items VALUES ('1971262665',
        '[버커루]20%중복쿠폰 BUCKAROO외 남녀 FW 아우터/의류 SALE',
        82500,
        25000,
        69,
        '아이스타일24')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '40',
    '1971262665'
    )

INSERT INTO items VALUES ('166496775',
        '신상/남자면바지/슬랙스/빅사이즈/조거팬츠/카고',
        46000,
        13800,
        70,
        '위드진1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '41',
    '166496775'
    )
INSERT INTO items VALUES ('1609013291',
        '긴팔티셔츠 95~140 빅사이즈/기모/맨투맨/후드티',
        23000,
        6900,
        70,
        '비토컴퍼니')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '42',
    '1609013291'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '43',
    '1998234203'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '44',
    '1914158208'
    )
INSERT INTO items VALUES ('1849758173',
        '[라코스테라이브]남성 삼선 포켓 티셔츠 LCST TH355E-20BF9F',
        53400,
        45390,
        15,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '45',
    '1849758173'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '46',
    '1137995278'
    )
INSERT INTO items VALUES ('1823976106',
        '12%쿠폰+균일가/융털/보아털/트레이닝복/패딩',
        66000,
        19800,
        70,
        '세빈옴므')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '47',
    '1823976106'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '48',
    '1999241445'
    )
INSERT INTO items VALUES ('1930572460',
        '[케이스위스]다운프루프기능 남녀 오리털 숏다운 4종 1택 4219JD405 4219JD406',
        45000,
        37350,
        17,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '49',
    '1930572460'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '50',
    '2002012509'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '51',
    '1983993163'
    )
INSERT INTO items VALUES ('1979269679',
        '한정수량특가29900 남여 헤비경량 패딩 점퍼 조끼16종',
        29900,
        29900,
        0,
        '90퍼센트')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '52',
    '1979269679'
    )
INSERT INTO items VALUES ('1991821020',
        '[폴햄]남여 그래픽 플리스 맨투맨 4종택1(PHA4TR3020 PHA4TR1200 PHA4TR2020 PHA4TR2030)',
        19900,
        16720,
        15,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '53',
    '1991821020'
    )
INSERT INTO items VALUES ('893744011',
        '[핫코드]신상 남자셔츠/빅사이즈/체크/오버핏/와이/청/옷/행사',
        46300,
        13900,
        69,
        '핫코드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '54',
    '893744011'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '55',
    '2005904819'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '56',
    '678530627'
    )
INSERT INTO items VALUES ('1369906351',
        '새해 시즌마감 홈쇼핑 후드티/트레이닝/후리스/패딩',
        33000,
        9900,
        70,
        '파라고나')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '57',
    '1369906351'
    )
INSERT INTO items VALUES ('1551175965',
        '[Komodo]코모도I  시즌 best 데일리 정장 상/하의 특가',
        25000,
        23500,
        6,
        'HDC아이파크몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '58',
    '1551175965'
    )
INSERT INTO items VALUES ('603138170',
        '[핫코드]겨울 남자 기모면바지/빅사이즈/슬랙스/조거바지/행사',
        43000,
        12900,
        70,
        '핫코드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '59',
    '603138170'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '60',
    '1295698550'
    )
INSERT INTO items VALUES ('1896851239',
        '(여성)탑텐(TOP10) 경량 구스다운 자켓+플러피플리스 점퍼',
        39900,
        36800,
        7,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '61',
    '1896851239'
    )
INSERT INTO items VALUES ('125749989',
        '[지기젠]남자청바지/기모본딩/슬림핏/일자/면바지/빅사이즈',
        19900,
        19900,
        0,
        '지기젠')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '62',
    '125749989'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '63',
    '1947767192'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '64',
    '1895169358'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '65',
    '1652387921'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '66',
    '1976662561'
    )
INSERT INTO items VALUES ('658035837',
        '긴팔티셔츠/빅사이즈/티셔츠/남자/남성/면/반/단체/티',
        26300,
        7900,
        69,
        '버클리클')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '67',
    '658035837'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '68',
    '1605140067'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '69',
    '1674006850'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '70',
    '1991904789'
    )
INSERT INTO items VALUES ('399621950',
        '[블루포스]겨울신상 목폴라티/기모 남자옷/니트/터틀넥목티셔츠',
        32600,
        9800,
        69,
        '블루포스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '71',
    '399621950'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '72',
    '1994558896'
    )
INSERT INTO items VALUES ('1570578952',
        '[이지바이]시즌오프 득템하라/기모티/바지/후리스/조끼/패딩자켓',
        23000,
        6900,
        70,
        '(주)이지바이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '73',
    '1570578952'
    )
INSERT INTO items VALUES ('1722783769',
        '[이너리즘]남성 겨울 융털기모 웰론 패딩점퍼',
        22900,
        22900,
        0,
        '이너리즘')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '74',
    '1722783769'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '75',
    '1867664152'
    )
INSERT INTO items VALUES ('1485282105',
        '12%쿠폰 엘라모 BEST 국내제작 맨투맨 후드',
        66000,
        19800,
        70,
        '엘라모')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '76',
    '1485282105'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '77',
    '1116129648'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '78',
    '1161403967'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '79',
    '1924803930'
    )
INSERT INTO items VALUES ('1688530036',
        '로드스타 남녀공용 니트/스웨터/후리스/패딩조끼',
        23000,
        6900,
        70,
        '로드스타14')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '80',
    '1688530036'
    )

INSERT INTO items VALUES ('1510498029',
        '1+1 특가 기모바지 아웃도어 스판팬츠-남성 기모바지',
        23900,
        23590,
        1,
        '(주)포커스코리안')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '81',
    '1510498029'
    )
INSERT INTO items VALUES ('1945529173',
        '[흄]유니) 시베리아 지퍼 롱다운FHMWCUW766',
        29900,
        23330,
        21,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '82',
    '1945529173'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '83',
    '2000253643'
    )
INSERT INTO items VALUES ('1372301757',
        '4900원 시즌마감 발열타이즈/기모티셔츠/패딩조끼',
        16300,
        4900,
        69,
        '파라고나')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '84',
    '1372301757'
    )
INSERT INTO items VALUES ('1403513474',
        '[슈프림]반팔티 티셔츠 S~5XL 빅사이즈 남자 여성 단체티 롱티',
        29600,
        8900,
        69,
        '문컬렉션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '85',
    '1403513474'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '86',
    '2005904818'
    )
INSERT INTO items VALUES ('357692917',
        '[블루포스]겨울신상 맨투맨티/빅사이즈 기모 커플티셔츠 남자옷',
        36300,
        10900,
        69,
        '블루포스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '87',
    '357692917'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '88',
    '1992612605'
    )
INSERT INTO items VALUES ('1903930009',
        '[라코스테]남성 중경량 다운 블루종 BH382E-20C_166',
        349300,
        296910,
        14,
        '라코스테 공식스토어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '89',
    '1903930009'
    )
INSERT INTO items VALUES ('1710620156',
        '겨울신상 기모본딩바지/청바지/슬랙스/밴딩/면/골덴',
        20000,
        17800,
        11,
        '후앙스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '90',
    '1710620156'
    )
INSERT INTO items VALUES ('1954910424',
        '양털 뽀글이후드 집업 뽀글이후리스 플리스 기모 자켓',
        25000,
        25000,
        0,
        '베스트야')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '91',
    '1954910424'
    )
INSERT INTO items VALUES ('1761071169',
        '트레이닝모음 긴바지/조거/기모/츄리닝/빅사이즈/3XL',
        26900,
        26900,
        0,
        '그레이레이즈')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '92',
    '1761071169'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '93',
    '1958069460'
    )
INSERT INTO items VALUES ('122879433',
        '28~40 겨울 카고 기모 바지/본딩/남자/작업복',
        26100,
        22800,
        12,
        '비브레이커스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '94',
    '122879433'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '95',
    '1931600523'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '96',
    '1486754865'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '97',
    '1932959543'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '98',
    '1933733496'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '99',
    '1964013325'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '남성의류',
    '100',
    '1927026222'
    )
패션의류 언더웨어
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '1',
    '787562120'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '2',
    '972418391'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '3',
    '166590237'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '4',
    '166590202'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '5',
    '1802651142'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '6',
    '166590234'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '7',
    '1923553682'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '8',
    '166590241'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '9',
    '2000911667'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '10',
    '960753074'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '11',
    '161861192'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '12',
    '1502725511'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '13',
    '1987041955'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '14',
    '1682892413'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '15',
    '720658634'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '16',
    '156577461'
    )
INSERT INTO items VALUES ('1590223233',
        '[원더브라]원더브라/플레이텍스 WELCOME2021 2종 특별할인',
        73000,
        21900,
        70,
        '엠코르셋')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '17',
    '1590223233'
    )
INSERT INTO items VALUES ('166590194',
        '[트라이]3매 7900/생리/위생/팬티/여자/여성/속옷/학생/주니어',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '18',
    '166590194'
    )
INSERT INTO items VALUES ('166590246',
        '[트라이]런닝5매/남성/남자/여성/여자/아동/조끼/반팔/속옷/면',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '19',
    '166590246'
    )
INSERT INTO items VALUES ('1807685600',
        '[라페어][선택1] 백화점 동일  라페어 프리미엄 레이온 팬티 패키지 15종 ',
        49900,
        46500,
        6,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '20',
    '1807685600'
    )
INSERT INTO items VALUES ('1912211871',
        '[아디다스]아디다스/푸마 홈쇼핑 남녀 겨울 내복 단품/세트 특가',
        26300,
        7900,
        69,
        '코웰패션주식회사')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '21',
    '1912211871'
    )
INSERT INTO items VALUES ('1913401285',
        '아디다스 정품  클라이마쿨 블랙 패키지 기능성 드로즈 9종 (53차)',
        99000,
        87120,
        12,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '22',
    '1913401285'
    )
INSERT INTO items VALUES ('1624900645',
        '[이너리즘]심리스 스포츠 브라탑 4종기획세트/노라인팬티 5종',
        41300,
        12400,
        69,
        '이너리즘')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '23',
    '1624900645'
    )

INSERT INTO items VALUES ('1909621332',
        '[휠라언더웨어]리니어 블랙밴드 5종 드로즈 FI4DRC6419MBLK',
        47000,
        47000,
        0,
        '휠라코리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '24',
    '1909621332'
    )
INSERT INTO items VALUES ('1684676028',
        '[트라이]트라이 본사 무료배송 남여 동내의 특가전',
        25900,
        13900,
        46,
        '쌍방울본사')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '25',
    '1684676028'
    )
INSERT INTO items VALUES ('177571721',
        '[란제리아]남영 비비안외 국산주니어 브라 팬티 속옷 학생쥬니어',
        26300,
        7900,
        69,
        '란제리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '26',
    '177571721'
    )
INSERT INTO items VALUES ('112247167',
        '[BYC]국내산5매 트렁크 사각 팬티 남자 남성 빅사이즈 속옷',
        43000,
        12900,
        70,
        '비앤비미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '27',
    '112247167'
    )
INSERT INTO items VALUES ('1843603002',
        '[라페어](여주점)라페어 인견 나염 팬티 5종 오렌지무드 LWHSS212',
        19900,
        17910,
        10,
        '신세계프리미엄아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '28',
    '1843603002'
    )
INSERT INTO items VALUES ('1647796977',
        '[아디다스][아디다스] HOT 남성 트렁크 5차 1종 택일',
        13900,
        11210,
        19,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '29',
    '1647796977'
    )
INSERT INTO items VALUES ('339305669',
        '[라보라]기획패키지 노와이어 브라팬티 10종세트',
        39900,
        39900,
        0,
        '솔트라이트아이엔씨')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '30',
    '339305669'
    )
INSERT INTO items VALUES ('285003609',
        '[크리비아]국산/주니어브라/주니어속옷/쥬니어팬티/학생브라',
        26300,
        7900,
        69,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '31',
    '285003609'
    )
INSERT INTO items VALUES ('1648755763',
        '[비너스]노와이어브라/팬티/세트/빅사이즈/여성/여자/브래지어',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '32',
    '1648755763'
    )
INSERT INTO items VALUES ('2006727077',
        '최신상 론칭  라이크라 에스뷰티 COVERLETTE',
        169000,
        169000,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '33',
    '2006727077'
    )
INSERT INTO items VALUES ('166590219',
        '[트라이]3매 7900원/삼각/팬티/남성/남자/인견/쿨/세트/속옷',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '34',
    '166590219'
    )
INSERT INTO items VALUES ('262125865',
        '[BYC]주니어/팬티/초등/학생/아동/삼각/남자/드로즈/속옷',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '35',
    '262125865'
    )
INSERT INTO items VALUES ('125035325',
        '[비너스 자스민]A-D컵/브라/팬티/세트/노와이어/남영비비안 外',
        29600,
        8900,
        69,
        '♡이너샵♡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '36',
    '125035325'
    )
INSERT INTO items VALUES ('581785464',
        '[란제리아]비비안 외 브라 팬티 세트 여성 여자 브래지어 속옷',
        33000,
        9900,
        70,
        '란제리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '37',
    '581785464'
    )
INSERT INTO items VALUES ('189279759',
        '[BYC]런닝 5매/남자/남성/조끼/나시/반팔/난닝구/속옷/면',
        33000,
        9900,
        70,
        '비앤비미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '38',
    '189279759'
    )
INSERT INTO items VALUES ('174727827',
        '[란제리아]비너스외 노와이어브라 여자 여성 속옷 브래지어 세트',
        33000,
        9900,
        70,
        '란제리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '39',
    '174727827'
    )
INSERT INTO items VALUES ('1970499679',
        '[리복]리복 20FW 바디 컨트롤 심리스 드로즈 패키지 (11종)',
        79000,
        69310,
        12,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '40',
    '1970499679'
    )
INSERT INTO items VALUES ('1722057939',
        '[스위스밀리터리]스위스 밀리터리 남자팬티 드로즈 5종/7종/10종세트',
        30800,
        30800,
        0,
        'JW언더웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '41',
    '1722057939'
    )
INSERT INTO items VALUES ('1114973997',
        '파란/브라팬티세트 ABCD컵추가금NO/빅사이즈/여성속옷',
        36300,
        10900,
        69,
        '파란언더웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '42',
    '1114973997'
    )
INSERT INTO items VALUES ('174475544',
        '[란제리아]비비안 외 위생 생리 팬티 여성 여자 주니어 방수포',
        33000,
        9900,
        70,
        '란제리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '43',
    '174475544'
    )
INSERT INTO items VALUES ('629542884',
        '국내자체제작/순면잠옷/여성잠옷/남성잠옷/커플잠옷',
        32800,
        31530,
        3,
        'MayFLowers')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '44',
    '629542884'
    )
INSERT INTO items VALUES ('1887235391',
        '[푸마][푸마바디웨어] [푸마] 남성 면스판 드로즈 1종 택일 [ 인기상품리오더_115/120_S',
        7900,
        6920,
        12,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '45',
    '1887235391'
    )
INSERT INTO items VALUES ('1880659721',
        '레이프릴코튼 뽀송 보정팬티 12종 패키지',
        39900,
        29330,
        26,
        '쇼핑엔티')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '46',
    '1880659721'
    )
INSERT INTO items VALUES ('718629964',
        '[아날도바시니]타이즈5900원/내복/내의/남자/남성/기모/발열/양모/융',
        33000,
        9900,
        70,
        '비앤비미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '47',
    '718629964'
    )
INSERT INTO items VALUES ('176368626',
        '[란제리아]여성팬티5매 여자 미디 맥시 속옷 삼각 위생 면 스판',
        33000,
        9900,
        70,
        '란제리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '48',
    '176368626'
    )
INSERT INTO items VALUES ('1718628014',
        '[아디다스][아디다스] HOT 남성 39차 드로즈 5종 세트 택일',
        52000,
        40870,
        21,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '49',
    '1718628014'
    )
INSERT INTO items VALUES ('960822034',
        '브라썸/빅사이즈/C/D/E컵/F컵/브라팬티세트/여성속옷',
        36300,
        10900,
        69,
        '파란언더웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '50',
    '960822034'
    )
INSERT INTO items VALUES ('1158321844',
        'A~F컵 브라/노와이어/빅사이즈/브라/여성팬티',
        19300,
        5800,
        69,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '51',
    '1158321844'
    )
INSERT INTO items VALUES ('1887639648',
        '[푸마바디웨어][푸마] 남성 면스판 드로즈 5종 세트 택일',
        37900,
        32800,
        13,
        'AKmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '52',
    '1887639648'
    )
INSERT INTO items VALUES ('1742706702',
        '[비너스아르보](현대Hmall)[아르보by비너스]노와이어 브라팬티 세트1+1',
        26900,
        26580,
        1,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '53',
    '1742706702'
    )

INSERT INTO items VALUES ('1892961989',
        '[라페어][선택2] 백화점 동일  라페어 프리미엄 레이온 이너티셔츠 7종 ',
        49900,
        46500,
        6,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '54',
    '1892961989'
    )
INSERT INTO items VALUES ('236903924',
        '주니어브라/1.2.3단계별/학생/팬티/속옷/위생/런닝',
        23000,
        6900,
        70,
        '디에스미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '55',
    '236903924'
    )
INSERT INTO items VALUES ('949976014',
        '1+1 파자마특가/밍크/수면바지/특면/기모/실크/융',
        33000,
        9900,
        70,
        '주)언더라인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '56',
    '949976014'
    )
INSERT INTO items VALUES ('1986401550',
        '[발렌티노 크리스티](런칭가 69900) 발렌티노크리스티 에어로웜 최신상',
        49900,
        46910,
        5,
        '쇼핑엔티')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '57',
    '1986401550'
    )
INSERT INTO items VALUES ('1402083389',
        '[캘빈클라인]CK신상 남성언더웨어20종 1+1+1/남자팬티/드로우즈',
        38800,
        38800,
        0,
        '라라트레이딩')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '58',
    '1402083389'
    )
INSERT INTO items VALUES ('1618673767',
        '[캘빈클라인언더웨어]CK 남자 팬티 속옷 드로즈 3팩 Set 20종 1+1+1 신상',
        38800,
        38800,
        0,
        '라라트레이딩')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '59',
    '1618673767'
    )
INSERT INTO items VALUES ('1986401465',
        '[발렌티노 크리스티](런칭가 69900) 발렌티노크리스티 에어로웜 최신상',
        49900,
        47910,
        3,
        '쇼핑엔티')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '60',
    '1986401465'
    )
INSERT INTO items VALUES ('872148233',
        '[BYC]20-21년 BYC외 보디히트 남녀 발열기모내의내복타이즈',
        22000,
        19900,
        9,
        'PHIL-INTIMO')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '61',
    '872148233'
    )
INSERT INTO items VALUES ('123770070',
        '[비너스 자스민]노와이어브라7900원/브래지어/여자/여성속옷/빅사이즈',
        39600,
        11900,
        69,
        '비앤비미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '62',
    '123770070'
    )
INSERT INTO items VALUES ('754850271',
        '[비너스]빅사이즈속옷 C/D/E/F컵 브라팬티세트/여성속옷',
        18900,
        15900,
        15,
        '소울메이트언더웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '63',
    '754850271'
    )
INSERT INTO items VALUES ('1919389018',
        '[스위스밀리터리]스위스밀리터리 남자 모달 무봉제 팬티 4장 세트',
        26000,
        26000,
        0,
        '언더스미스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '64',
    '1919389018'
    )
INSERT INTO items VALUES ('627680298',
        '[어나더디]남녀 수면잠옷 빅사이즈 커플 파자마 홈웨어 오버핏',
        20000,
        14800,
        26,
        '어나더디')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '65',
    '627680298'
    )
INSERT INTO items VALUES ('679086901',
        '바닐라쿠브라팬티세트/ABCD컵/여성속옷/왕뽕/빅사이즈',
        10900,
        8540,
        21,
        '바닐라쿠')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '66',
    '679086901'
    )
INSERT INTO items VALUES ('865694037',
        '[BYC]BYC 보디히트 최다보유 신상내복 내의 기모 발열기모',
        36900,
        36900,
        0,
        'PHIL-INTIMO')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '67',
    '865694037'
    )
INSERT INTO items VALUES ('1262693500',
        '2+1양말 수면바지/커플잠옷/짱구/파자마/잠옷/원피스',
        19600,
        5900,
        69,
        '스토리몰2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '68',
    '1262693500'
    )
INSERT INTO items VALUES ('743897129',
        '드로즈/세트/남자/남성/팬티/95-130호/빅사이즈/사각',
        29900,
        29900,
        0,
        '★미즈넬★')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '69',
    '743897129'
    )
INSERT INTO items VALUES ('1784279536',
        '수맘 겨울 수면 기모 홈웨어 잠옷 파자마',
        9900,
        9900,
        0,
        '(수맘)')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '70',
    '1784279536'
    )
INSERT INTO items VALUES ('2001339832',
        '+세컨팬티3종 메리메by에블린 마드모아젤 Collection',
        139000,
        139000,
        0,
        '씨제이오쇼핑플러스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '71',
    '2001339832'
    )
INSERT INTO items VALUES ('1419869078',
        '여성속옷/브라팬티세트/ABC컵/볼륨업/노와이어/심리스',
        29900,
        24900,
        16,
        '래디쉬웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '72',
    '1419869078'
    )
INSERT INTO items VALUES ('1788141476',
        '[발레리][발레리] [VL-16]  데일리 실속 패키지 10종',
        45900,
        39030,
        14,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '73',
    '1788141476'
    )
INSERT INTO items VALUES ('1691991133',
        '[트라이]남성 참 편한 니트 트렁크/남자속옷/팬티 4종세트',
        19900,
        19900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '74',
    '1691991133'
    )
INSERT INTO items VALUES ('1720458825',
        '[스위스밀리터리]남자 팬티 세트 5장 /드로즈/남성팬티/남자속옷 세트',
        22000,
        22000,
        0,
        '언더스미스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '75',
    '1720458825'
    )
INSERT INTO items VALUES ('1925990293',
        '러빙리 심심가 커플잠옷 홈웨어 파자마세트 수면잠옷',
        18800,
        18800,
        0,
        '러빙리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '76',
    '1925990293'
    )
INSERT INTO items VALUES ('246972087',
        '여성팬티 1매/면팬티/빅사이즈/여성/여자/면스판/국산',
        8300,
        2500,
        69,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '77',
    '246972087'
    )
INSERT INTO items VALUES ('1793481170',
        '레이프릴코튼 뽀송 보정팬티 12종 패키지',
        39900,
        30920,
        22,
        '쇼핑엔티홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '78',
    '1793481170'
    )
INSERT INTO items VALUES ('1887235385',
        '[푸마][푸마바디웨어] [푸마] 남성 면스판 드로즈 5종 세트 택일 [ 인기상품리오더_115/12',
        37900,
        33480,
        11,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '79',
    '1887235385'
    )
INSERT INTO items VALUES ('216772071',
        '[물랑루즈]주니어팬티/드로즈/삼각/트렁크/아동속옷/학생/남자',
        33000,
        9900,
        70,
        '디에스미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '80',
    '216772071'
    )
INSERT INTO items VALUES ('1994552798',
        '[헤스떼벨][헤스떼벨] 수피마 코튼 브라팬티 패키지  3SET+랜덤 2SET',
        49900,
        49900,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '81',
    '1994552798'
    )
INSERT INTO items VALUES ('675804959',
        '[엠알키즈]아동 팬티 5매 4900원 유아 주니어 런닝 순면 속옷',
        32600,
        9800,
        69,
        '디에스미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '82',
    '675804959'
    )
INSERT INTO items VALUES ('1694731751',
        '[BYC]남녀 내복/내의/세트/발열/남자/여자/발열/기모',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '83',
    '1694731751'
    )

INSERT INTO items VALUES ('1899021909',
        '[아디다스]아디다스  정품 코튼 블랙에디션 드로즈 9종',
        99000,
        89100,
        10,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '84',
    '1899021909'
    )
INSERT INTO items VALUES ('1861550760',
        '[아디다스][아디다스] NEW 남성 코튼 트렁크 1종 스타일택일',
        13900,
        10940,
        21,
        '신세계몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '85',
    '1861550760'
    )
INSERT INTO items VALUES ('1441633365',
        '5+5/여성/여자/팬티/삼각/속옷/국산/요일/면/위생',
        9900,
        9900,
        0,
        '준란제리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '86',
    '1441633365'
    )
INSERT INTO items VALUES ('915562787',
        '6~10종 여성속옷 ABC컵 브라팬티세트 노와이어/볼륨업',
        26000,
        24840,
        4,
        '제이지몰.')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '87',
    '915562787'
    )
INSERT INTO items VALUES ('1978224793',
        '체크 여성 잠옷 세트 파자마 홈웨어 여자 실내 수면',
        13900,
        13900,
        0,
        '스마일배송')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '88',
    '1978224793'
    )
INSERT INTO items VALUES ('1924162569',
        '[코데즈컴바인]베이직브라팬티세트 6종택1',
        30000,
        24900,
        17,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '89',
    '1924162569'
    )
INSERT INTO items VALUES ('1840375935',
        '[아디다스][아디다스 언더웨어] [아디다스] 남성 아이스 쿨 패키지 드로즈 1종 택일',
        10900,
        10580,
        2,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '90',
    '1840375935'
    )
INSERT INTO items VALUES ('190794686',
        '[아날도바시니]3매7900원 남성 삼각 팬티 면 스판 남자 속옷 세트',
        43000,
        12900,
        70,
        '비앤비미니샵')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '91',
    '190794686'
    )
INSERT INTO items VALUES ('182630822',
        '[아날도바시니]드로즈1매2900원/남자/팬티/남성/속옷/사각/빅밴드',
        26300,
        7900,
        69,
        '란제리아')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '92',
    '182630822'
    )
INSERT INTO items VALUES ('1899383258',
        '아디다스 드로즈 패키지53차',
        99000,
        89100,
        10,
        '홈앤쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '93',
    '1899383258'
    )
INSERT INTO items VALUES ('1995160989',
        '[아디다스][아디다스 언더웨어] [아디다스] 남성 데일리 스페셜 드로즈 3종세트 6스타일 택일',
        23900,
        22210,
        7,
        '롯데아이몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '94',
    '1995160989'
    )
INSERT INTO items VALUES ('1903946559',
        '벨라폰테 20FW 벨라폰테 퓨징 헴 네모팬티',
        59900,
        52320,
        12,
        'SK스토아TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '95',
    '1903946559'
    )
INSERT INTO items VALUES ('1478133521',
        '브라썸/노와이어브라팬티세트/심리스/ABCD컵/여성속옷',
        36300,
        10900,
        69,
        '파란언더웨어')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '96',
    '1478133521'
    )
INSERT INTO items VALUES ('302409596',
        '[키즈키오]주니어 내의 내복 아동 남아 여아 초등학생 발열 기모',
        33000,
        9900,
        70,
        '한스속옷')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '97',
    '302409596'
    )
INSERT INTO items VALUES ('1924442281',
        '[플레이텍스]마지막물량 플레이텍스 플레이 노와이어 브라팬티세',
        169000,
        159000,
        5,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '98',
    '1924442281'
    )
INSERT INTO items VALUES ('1992222131',
        '새해최신상  FILA 휠라 시그니처에디션 노와이어 브',
        169900,
        169900,
        0,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '99',
    '1992222131'
    )
INSERT INTO items VALUES ('1920317809',
        '턴키남여공용 빅사이즈(26-44까지) 극세사밍크수면바지',
        10800,
        10320,
        4,
        '턴키')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('패션의류',
    '언더웨어',
    '100',
    '1920317809'
    )
http://corners.gmarket.co.kr/Bestsellers?viewType=G&groupCode=G02 신발/잡화
INSERT INTO items VALUES ('798413703',
        '[투투삭스]겨울 양말 균일가  패션양말/스니커즈/골지/학생',
        23000,
        6900,
        70,
        '투투삭스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '1',
    '798413703'
    )
INSERT INTO items VALUES ('1107162855',
        '[프롬산타]3+1 양말/롱삭스/수면 남자여자학생스니커즈덧신겨울',
        23000,
        6900,
        70,
        '프롬산타양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '2',
    '1107162855'
    )
INSERT INTO items VALUES ('1828501434',
        '글로벌 BT21 정품 신상 차차/로사/베베 슬리퍼/방한화',
        23000,
        6900,
        70,
        '슈라모드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '3',
    '1828501434'
    )
INSERT INTO items VALUES ('187896486',
        '1+1 14K 골드핀 피어싱 (Gold-Pin) / 써지컬 피어싱',
        17900,
        17900,
        0,
        '미니아트9')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '4',
    '187896486'
    )
INSERT INTO items VALUES ('1942767441',
        '겨울신발 털신발 방한화 패딩운동화 털운동화 스윙',
        33000,
        9900,
        70,
        '바이시유')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '5',
    '1942767441'
    )
INSERT INTO items VALUES ('1728610613',
        '[엔비]헤어 곱창 세트 밴드 머리끈 슈슈 똑딱핀 집게핀',
        32000,
        9900,
        69,
        '(주)엔비2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '6',
    '1728610613'
    )
INSERT INTO items VALUES ('630959840',
        '판매1위 2021 신상 은침귀걸이 롱 링 마스크목걸이',
        12900,
        3900,
        69,
        '워너비스톤')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '7',
    '630959840'
    )
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '8',
    '1945772215'
    )
INSERT INTO items VALUES ('305558244',
        '[페이퍼플레인]겨울 여성 부츠 방한화 운동화 신발 스니커즈 슬립온',
        45000,
        13500,
        70,
        '페이퍼플레인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '9',
    '305558244'
    )
INSERT INTO items VALUES ('1561051668',
        '스타일윙윙 여자 남자 양말 중목/발목/덧신/아동양말',
        23000,
        6900,
        70,
        '스타일윙윙')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '10',
    '1561051668'
    )
INSERT INTO items VALUES ('811227284',
        '[페이퍼플레인]겨울신발 털슬리퍼 실내화 거실화 털신 패딩슬리퍼',
        42600,
        12800,
        69,
        'SNRD')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '11',
    '811227284'
    )
INSERT INTO items VALUES ('1999209374',
        '팀버랜드  FW 부츠/워커/스니커즈 50종 클리어런스',
        218000,
        65400,
        70,
        '팀버랜드온라인공식몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '12',
    '1999209374'
    )
INSERT INTO items VALUES ('1174543480',
        '[무크]mook 20FW 시즌오프 부츠/로퍼/정장화 등 32%',
        120900,
        36900,
        69,
        'mook / 무크')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '13',
    '1174543480'
    )

INSERT INTO items VALUES ('1987605508',
        '[스프리스]여성 스프리스 겨울 쿠션 패딩부츠',
        59900,
        53910,
        10,
        'GS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '14',
    '1987605508'
    )
INSERT INTO items VALUES ('320522723',
        '힐슈빌 신상 부츠 털부츠 털단화 패딩부츠 방한화신발',
        32600,
        9800,
        69,
        '힐슈빌')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '15',
    '320522723'
    )
INSERT INTO items VALUES ('1872305729',
        '[바나바나]신년맞이 바나바나 신상품 및 인기상품 특별전 50종',
        89000,
        32900,
        63,
        'BanaBana')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '16',
    '1872305729'
    )
INSERT INTO items VALUES ('681475998',
        '데일리 에코백/캔버스백/크로스백/천가방/보조가방',
        33000,
        9900,
        70,
        '프롬헤븐')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '17',
    '681475998'
    )
INSERT INTO items VALUES ('1277558140',
        '[프롬산타]3+사은품 양말 선물세트 덧신 남자여자발목중목학생',
        23000,
        6900,
        70,
        '프롬산타양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '18',
    '1277558140'
    )
INSERT INTO items VALUES ('1774742160',
        '키높이 운동화 여성 스니커즈 유니크 신발 캐넌KJ03',
        52600,
        15800,
        69,
        '틱앤톡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '19',
    '1774742160'
    )
INSERT INTO items VALUES ('1555182529',
        '남자트레킹화 워킹화 등산화 패션운동화 남성신발 커플',
        23800,
        23570,
        0,
        '★ 더센스  ★')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '20',
    '1555182529'
    )
INSERT INTO items VALUES ('1130472838',
        '커플운동화/신발/등산화/스니커즈/런닝화',
        63900,
        19800,
        69,
        '슈즈스마트')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '21',
    '1130472838'
    )
INSERT INTO items VALUES ('731948340',
        '여성 머플러 목도리 목폴라 장갑 암워머 니트 모자',
        29000,
        8900,
        69,
        '(주)엔비2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '22',
    '731948340'
    )
INSERT INTO items VALUES ('852459334',
        '틱앤톡 여성 삭스부츠 앵클부츠 앵글 첼시 부츠 워커',
        49300,
        14800,
        69,
        '틱앤톡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '23',
    '852459334'
    )
INSERT INTO items VALUES ('734482203',
        '[페이퍼플레인]남녀공용 겨울 털신발 방한화 패딩슬립온 스니커즈',
        46300,
        13900,
        69,
        'SNRD')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '24',
    '734482203'
    )
INSERT INTO items VALUES ('1462990483',
        '[가나양말]남자 여자 발목 양말 뮬 블로퍼 덧신 페이크삭스',
        23000,
        6900,
        70,
        '가나양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '25',
    '1462990483'
    )
INSERT INTO items VALUES ('1855292323',
        '[내셔널지오그래픽][모다아울렛]신학기백팩/슈즈/볼캡 3만원대부터',
        69000,
        69000,
        0,
        'MODA아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '26',
    '1855292323'
    )
INSERT INTO items VALUES ('1545730130',
        '[뷰오케이]뷰오케이 안경 김서림방지 안경클리너',
        6000,
        6000,
        0,
        '뷰오케이')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '27',
    '1545730130'
    )
INSERT INTO items VALUES ('1498594869',
        '호피 호피 에코백 보드라운 원단~ 시즌핫한 아이템',
        52900,
        15900,
        69,
        '탐스백')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '28',
    '1498594869'
    )
INSERT INTO items VALUES ('1920052835',
        '[베어파우][베어파우] 로지(Rosy) 첼시 부츠',
        65000,
        61750,
        5,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '29',
    '1920052835'
    )
INSERT INTO items VALUES ('795935358',
        '신상 여성가방 2개 구매시 뽀글이 파우치 1개 증정',
        49600,
        14900,
        69,
        '애드에딧')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '30',
    '795935358'
    )
INSERT INTO items VALUES ('853982082',
        '신상 본품 1+1 /14K GP 진주 링 드롭귀걸이',
        33000,
        10000,
        69,
        '지오(geo)콜렉션')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '31',
    '853982082'
    )
INSERT INTO items VALUES ('1972094201',
        '여성 키높이 소가죽 방한화 털부츠 물량긴급공수',
        19900,
        19710,
        0,
        '슈플마켓')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '32',
    '1972094201'
    )
INSERT INTO items VALUES ('1976853331',
        '하이탑 트레킹운동화 DM702',
        33000,
        9900,
        70,
        '동호상사-')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '33',
    '1976853331'
    )
INSERT INTO items VALUES ('763098932',
        '사은품증정 14K골드 정품 귀걸이/팔찌/피어싱',
        66300,
        19900,
        69,
        '니지쥬얼리')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '34',
    '763098932'
    )
INSERT INTO items VALUES ('1491799783',
        '더빨강양말 남자여자 발목/중목/장목/겨울양말/학생',
        6900,
        6900,
        0,
        '더빨강양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '35',
    '1491799783'
    )
INSERT INTO items VALUES ('1960918140',
        '(더라 (The Rha)) (부산점)균일가 인기 BEST 밍크/폭스 퍼머플러 키링 6종1택',
        35000,
        29750,
        15,
        '신세계프리미엄아울렛')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '36',
    '1960918140'
    )
INSERT INTO items VALUES ('760282459',
        '[페이퍼플레인]운동화/스니커즈/에어쿠션/런닝화/키높이/PP1101',
        136000,
        40800,
        70,
        '페이퍼플레인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '37',
    '760282459'
    )
INSERT INTO items VALUES ('1673320912',
        '1+1 여성 남성 목폴라 넥워머 머플러 후드',
        26000,
        7900,
        69,
        '(주)엔비2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '38',
    '1673320912'
    )
INSERT INTO items VALUES ('1796968804',
        '(현대Hmall)[휠라] FILA 꾸미 라이트 GGUMI LIGHT PT 3종 키즈 스니커즈 아동 운동화 슬립온 (3RM01298)',
        34000,
        32710,
        3,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '39',
    '1796968804'
    )
INSERT INTO items VALUES ('1513306927',
        '꾸안꾸 라인이 예쁜 롱부츠/앵클/삭스 부츠/첼시/부티',
        33000,
        9900,
        70,
        '브리즈1')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '40',
    '1513306927'
    )
INSERT INTO items VALUES ('1965300152',
        '[프롬산타]롱롱골지 중목패션양말 5켤레',
        23000,
        6900,
        70,
        '프롬산타양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '41',
    '1965300152'
    )
INSERT INTO items VALUES ('1942121991',
        '(현대Hmall)[휠라] FILA 꾸미 GGUMI 3종 키즈 스니커즈 아동 운동화 슬립온 (3RM01156)',
        29000,
        27260,
        6,
        '현대Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '42',
    '1942121991'
    )
INSERT INTO items VALUES ('1506330206',
        '슬레진저 남여 털운동화/방한화/패딩슈즈/털신발/겨울',
        39600,
        12900,
        67,
        '댓츠마인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '43',
    '1506330206'
    )

INSERT INTO items VALUES ('1970559077',
        '[노스페이스]1 W BOOTIE CLASSIC SHORT (NS99K56) 여성 부띠 클래식 쇼트',
        101500,
        76130,
        24,
        '롯데백화점1관')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '44',
    '1970559077'
    )
INSERT INTO items VALUES ('1460519003',
        '[프로월드컵]22%추가쿠폰 아이젠부츠 패딩부츠 털슬리퍼/런닝화',
        65000,
        19800,
        69,
        '프로월드컵공식몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '45',
    '1460519003'
    )
INSERT INTO items VALUES ('1889312893',
        '[베어파우]+22% 베어파우(BEARPAW) 2020FW 양털슈즈 76종 택1',
        82000,
        25000,
        69,
        'wingsfoot')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '46',
    '1889312893'
    )
INSERT INTO items VALUES ('1995489859',
        '(단독) 1+1+1 김서림 방지 안경 닦이 안티포그 클리너/ 투디터(선글라스)',
        6900,
        6810,
        1,
        '롯데ON')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '47',
    '1995489859'
    )
INSERT INTO items VALUES ('1658729004',
        '[가나양말]남자 여자 학생 덧신 발목 중목 장목 스포츠 양말',
        23000,
        6900,
        70,
        '가나양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '48',
    '1658729004'
    )
INSERT INTO items VALUES ('1558351854',
        '[BT21]BT21 베베/페니/POP/로사/인형/차차 슬리퍼/방한화',
        23000,
        6900,
        70,
        '슈라모드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '49',
    '1558351854'
    )
INSERT INTO items VALUES ('1441705708',
        '[금강제화]20FW 겨울 여성 앵클부츠/삭스부츠/패딩슬립온 50종',
        96000,
        55000,
        42,
        '_금강제화')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '50',
    '1441705708'
    )
INSERT INTO items VALUES ('1874654493',
        '포나리나 2020 스텔라 플라이삭스 6.5cm 업(UP) 부츠',
        79000,
        79000,
        0,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '51',
    '1874654493'
    )
INSERT INTO items VALUES ('493534687',
        '신상 슬립온 플랫 단화 여성 키높이 운동화 스니커즈',
        56000,
        16800,
        70,
        '버니슈™')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '52',
    '493534687'
    )
INSERT INTO items VALUES ('1899380325',
        '[닥스ACC]닥스 가방/지갑/클러치/장지갑/숄더백/반지갑 +20%',
        314600,
        94400,
        69,
        'LF몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '53',
    '1899380325'
    )
INSERT INTO items VALUES ('365352895',
        '여성신발 슬립온 스니커즈 신발 단화 운동화 플랫슈즈',
        32600,
        9800,
        69,
        '틱앤톡')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '54',
    '365352895'
    )
INSERT INTO items VALUES ('1645478664',
        '[엘칸토]엘칸토 20FW 남녀 겨울슈즈 시즌오프세일',
        179000,
        55000,
        69,
        '엘칸토ELCANTO')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '55',
    '1645478664'
    )
INSERT INTO items VALUES ('2003205344',
        '스프리스 여성 쿠션패딩부츠',
        59900,
        59900,
        0,
        'NS홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '56',
    '2003205344'
    )
INSERT INTO items VALUES ('1920979773',
        '[슬레진저]겨울 방한화 털 패딩운동화 패딩 기모 신발  Low  Hi',
        19800,
        17270,
        12,
        '샵문스')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '57',
    '1920979773'
    )
INSERT INTO items VALUES ('1956839756',
        '[벤포트] 남여 스타 퍼 스니커즈',
        29800,
        29800,
        0,
        '롯데 홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '58',
    '1956839756'
    )
INSERT INTO items VALUES ('1925079295',
        '[닥스ACC]닥스 가방/지갑/클러치/장지갑/숄더백/모자 +25%',
        314600,
        94400,
        69,
        'LF몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '59',
    '1925079295'
    )
INSERT INTO items VALUES ('433166322',
        '디비노 방한화 남자 여성 털신 겨울신발 방한부츠 털',
        60000,
        59800,
        0,
        '링크홈쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '60',
    '433166322'
    )
INSERT INTO items VALUES ('1990920368',
        '[노스페이스화이트라벨](대구신세계)공용 눕시 부띠 NS99K71',
        101000,
        78780,
        22,
        '신세계백화점')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '61',
    '1990920368'
    )
INSERT INTO items VALUES ('1992284973',
        '신상공개 지오송지오 21SS 기모 쉐이핑 고탄력 팬츠 4종',
        69900,
        69900,
        0,
        'CJ오쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '62',
    '1992284973'
    )
INSERT INTO items VALUES ('397729569',
        '[가나양말]남자 여자 발목 덧신 페이크삭스 정장 스포츠 양말',
        21600,
        6500,
        69,
        '가나양말')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '63',
    '397729569'
    )
INSERT INTO items VALUES ('516224243',
        '단골언니 여성 신발 슬립온/스니커즈/운동화',
        42600,
        12800,
        69,
        '-단골언니-')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '64',
    '516224243'
    )
INSERT INTO items VALUES ('1846906010',
        '피에라벨라 SAGA 폭스 풀스킨 머플러 (초특가)',
        39900,
        38000,
        4,
        '신세계TV쇼핑')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '65',
    '1846906010'
    )
INSERT INTO items VALUES ('1956409060',
        '[아가타]아가타  여성 퍼 밴딩플랫_블랙 지금신기딱좋은플랫',
        13700,
        13290,
        2,
        '슈플마켓')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '66',
    '1956409060'
    )
INSERT INTO items VALUES ('1921180801',
        '20FW 마스케라 리얼 밍크 핸드메이드 니팅 모자+폭스퍼폼폼 (2종)',
        69900,
        69900,
        0,
        '현대홈쇼핑Hmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '67',
    '1921180801'
    )
INSERT INTO items VALUES ('861577112',
        '[이사도라]신상 퍼슈즈/워커/앵클/롱부츠 이사도라',
        29600,
        8900,
        69,
        '이사도라2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '68',
    '861577112'
    )
INSERT INTO items VALUES ('1487777111',
        '국산 10켤레 남자양말 패션 발목 덧신 중목 신사 정장',
        6500,
        6400,
        1,
        '하이언더바')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '69',
    '1487777111'
    )
INSERT INTO items VALUES ('240741538',
        '워커힐 플랫 통굽 워커 학생 구두 여성 첼시 삭스부츠',
        62600,
        18800,
        69,
        '★유즈★')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '70',
    '240741538'
    )
INSERT INTO items VALUES ('1503623516',
        '남자 겨울털신발 방한화 방한신발 트래킹화 겨울신발',
        21800,
        21700,
        0,
        '★ 더센스  ★')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '71',
    '1503623516'
    )
INSERT INTO items VALUES ('2005204239',
        '기모 골지 수면 양말 10개 세트 한파 방한',
        20900,
        9900,
        52,
        '(주)엔비2')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '72',
    '2005204239'
    )
INSERT INTO items VALUES ('1932350320',
        '[크록스]크록스 겨울 털슬리퍼 정품 크록스 크록밴드 인기샌들',
        31900,
        31900,
        0,
        'crocs')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '73',
    '1932350320'
    )

INSERT INTO items VALUES ('1899398517',
        '[헤지스ACC]헤지스 가방/지갑/클러치/장지갑/숄더백/반지갑 +20%',
        252000,
        75600,
        70,
        'LF몰')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '74',
    '1899398517'
    )
INSERT INTO items VALUES ('1284425058',
        '[디즈니]BT21 방한 슬리퍼 및 디즈니 인기 슬리퍼',
        33000,
        9900,
        70,
        '슈라모드')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '75',
    '1284425058'
    )
INSERT INTO items VALUES ('1975975358',
        '소렐 여성용 워커부츠 NL3039-010',
        29900,
        28460,
        4,
        'AKmall')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '76',
    '1975975358'
    )
INSERT INTO items VALUES ('301572732',
        '[가데옴므]천연소가죽 남성방한화 캐주얼남성구두 로퍼 정장구두',
        122600,
        36800,
        69,
        '페이퍼플레인')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '77',
    '301572732'
    )
INSERT INTO items VALUES ('1506382510',
        '카이맨 최고급 가죽 방한장갑 모음전/사슴 염소가죽',
        35000,
        35000,
        0,
        '인스타마트')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '78',
    '1506382510'
    )
INSERT INTO items VALUES ('167990203',
        '[마젤란]크로스백 메신저백 힙색 학생 여성 남성 여행용 가방',
        21800,
        19800,
        9,
        '더블유팝')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '79',
    '167990203'
    )
INSERT INTO items VALUES ('1999970888',
        '[크록스]겨울 털크록스 정품 털실내화 바야밴드 클로그 5종',
        31900,
        31900,
        0,
        'crocs')
INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('신발/잡화',
    'ALL',
    '80',
    '1999970888'
    )

AttributeError: 'NoneType' object has no attribute 'get_text'

In [137]:
def get_category(category_link, category_name) :
    print(category_link, category_name)
    res = requests.get(category_link)
    soup = BeautifulSoup(res.content, 'html.parser')
    
    get_items(soup, category_name, 'ALL')
    
    sub_categories = soup.select('div.navi.group ul li > a')
    for sub_category in sub_categories : 
        res = requests.get('http://corners.gmarket.co.kr/' + sub_category['href'])
        soup = BeautifulSoup(res.content, 'html.parser')
        print(category_name, sub_category.get_text())
        get_items(soup, category_name, sub_category.get_text())

In [140]:
def get_items(html, category_name, sub_category_name) :
#     items_result_list = list()
    best_item = html.select('div.best-list')
    
    if len(best_item[1].select('li')) > 0:
        for index, item in enumerate(best_item[1].select('li')) : 
            data_dict = dict()

            ranking = index + 1
            title = item.select_one('a.itemname')
            ori_price = item.select_one('div.o-price')
            dis_price = item.select_one('div.s-price strong span span')
            discount_percent = item.select_one('div.s-price em')

            res = requests.get(title['href'])
            soup = BeautifulSoup(res.content, 'html.parser')
            provider = soup.select_one('div.item-topinfo_headline > p > span.text__seller > a')
            
            if provider.get_text() == None or provider.get_text() == '' : 
                provider = ''
            else :
                provider = provider.get_text()

            if ori_price == None or ori_price.get_text() == '' :
                ori_price = dis_price

            if dis_price == None : 
                ori_price, dis_price = 0, 0

            ori_price = ori_price.get_text().replace(',', '').replace('원', '')
            dis_price = dis_price.get_text().replace(',', '').replace('원', '')

            if discount_percent == None or discount_percent.get_text() == '' :
                discount_percent = 0
            else : 
                discount_percent = discount_percent.get_text().replace('%', '')
            item_code = title['href'].split('=')[1].split('&')[0]
    #         http://item.gmarket.co.kr/Item?goodscode=1941616635&ver=637464012803685578

            data_dict['category_name'] = category_name
            data_dict['sub_category_name'] = sub_category_name
            data_dict['ranking'] = ranking
            data_dict['title'] = title.get_text()
            data_dict['ori_price'] = ori_price
            data_dict['dis_price'] = dis_price
            data_dict['discount_percent'] = discount_percent
            data_dict['provider'] = provider
            data_dict['item_code'] = item_code

            save_data(data_dict)

    #         print(str(item_code), category_name, sub_category_name, ranking, title.get_text(), ori_price, dis_price, discount_percent, provider)

In [135]:
def save_data(item_info) :
    
    sql = """SELECT COUNT(*) FROM items WHERE item_code = '""" + item_info['item_code'] + """';"""
    bestproducts.execute(sql)
    result = bestproducts.fetchone()
    if result[0] == 0 : 
        sql = """INSERT INTO items VALUES ('""" + item_info['item_code'] + """',
        '""" + item_info['title'] + """',
        """ + str(item_info['ori_price']) + """, 
        """ + str(item_info['dis_price']) + """,
        """ + str(item_info['discount_percent']) + """,
        '""" + item_info['provider'] + """')"""
        print (sql)
        bestproducts.execute(sql)
    
    
    
    sql = """INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('""" + item_info['category_name'] + """',
    '""" + item_info['sub_category_name'] + """',
    '""" + str(item_info['ranking']) + """', 
    '""" + item_info['item_code'] + """'
    )"""
    print(sql)
    bestproducts.execute(sql)

### INSERT 만들기

sql = """
CREATE TABLE ranking (
    num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    main_category VARCHAR(50) NOT NULL,
    sub_category VARCHAR(50) NOT NULL,
    item_ranking TINYINT UNSIGNED NOT NULL,
    item_code VARCHAR(20) NOT NULL,
    FOREIGN KEY (item_code) REFERENCES items(item_code)
);
"""

In [99]:
item_info = {'category_name': 'ALL', 'sub_category_name': 'ALL', 'ranking': 1, 'title': '[컬럼비아](광주신세계)3종 택일 컬럼비아 남성 가볍고 따뜻한 경량 다운 조끼 C14-WE0952', 'ori_price': '45000', 'dis_price': '32850', 'discount_percent': '27', 'provider': '신세계백화점', 'item_code': '1941616635'}

In [102]:
sql = """INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('
""" + item_info['category_name'] + """',
'""" + item_info['sub_category_name'] + """',
'""" + str(item_info['ranking']) + """', 
'""" + item_info['item_code'] + """'
)"""

In [103]:
sql.replace('\n', '')

"INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('ALL','ALL','1', '1941616635')"

### 목적 
- 실제로 데이터베이스를 사용하는 방법을 현업 스타일로 설명을 드리는 것
- SQL 강의 - 단순히 세세한 SQL 문법을 다 소개받고 끝 
- 현실 세계의 데이터를 어떻게 테이블로 정의할 것인가? 
- 어떻게 데이터를 넣을 것인가? (프로그래밍으로 넣는 것이 일반적임)
- 저장된 데이터를 분석한다. (SQL만 쓰는 경우 + 프로그래밍에서 데이터를 분석해서 풀스택으로 서비스화 한다.)

#### 기존 SQL 강의 : 단순히 세세한 SQL 문법을 다 소개받고 끝

In [ ]:
sql = """
CREATE TABLE items (
    item_code VARCHAR(20) NOT NULL PRIMARY KEY, 
    title VARCHAR(200) NOT NULL,
    ori_price INT NOT NULL,
    dis_price INT NOT NULL,
    discount_percent INT NOT NULL, 
    provider VARCHAR(200)
);
"""

In [104]:
sql = """INSERT INTO items (item_code, title, ori_price, dis_price, discount_percent, provider) VALUES ('
""" + item_info['item_code'] + """',
'""" + item_info['title'] + """',
""" + item_info['ori_price'] + """, 
""" + item_info['dis_price'] + """,
""" + item_info['discount_percent'] + """,
'""" + item_info['provider'] + """')"""

In [111]:
def save_data(item_info) :
    
    sql = """SELECT COUNT(*) FROM items WHERE item_code = '""" + item_info['item_code'] + """';"""
    bestproducts.execute(sql)
    result = bestproducts.fetchone()
    if result[0] == 0 : 
        sql = """INSERT INTO items VALUES ('""" + item_info['item_code'] + """',
        '""" + item_info['title'] + """',
        """ + str(item_info['ori_price']) + """, 
        """ + str(item_info['dis_price']) + """,
        """ + str(item_info['discount_percent']) + """,
        '""" + item_info['provider'] + """')"""
        print (sql)
        bestproducts.execute(sql)
    
    
    
    sql = """INSERT INTO ranking (main_category, sub_category, item_ranking, item_code) VALUES ('""" + item_info['category_name'] + """',
    '""" + item_info['sub_category_name'] + """',
    '""" + str(item_info['ranking']) + """', 
    '""" + item_info['item_code'] + """'
    )"""
    print(sql)
    bestproducts.execute(sql)

#### COUNT SQL 
- COUNT : 검색 결과의 row 수를 가져올 수 있는 SQL 문법이다. 
-SQL 예제 : SELECT COUNT(*) FROM items

sql = """SELECT COUNT(*) FROM items WHERE item_code = '""" + item_info['item_code'] + """';"""
bestproducts.execute(sql)
result = bestproducts.fetchone()
print(result[0])

In [108]:
sql = """SELECT COUNT(*) FROM items WHERE ite_code = '""" + item_info['item_code'] + """';"""

In [109]:
sql

"SELECT COUNT(*) FROM items WHERE ite_code = '1941616635';"